// Code generated by MockGen. DO NOT EDIT.
// Source: admissiongate.go
//
// Generated by this command:
//
//	mockgen -source=admissiongate.go -destination=mock/admissiongate_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/stovepipe/entity"
	admissiongate "github.com/uber/submitqueue/stovepipe/extension/admissiongate"
	gomock "go.uber.org/mock/gomock"
)

// MockGate is a mock of Gate interface.
type MockGate struct {
	ctrl     *gomock.Controller
	recorder *MockGateMockRecorder
	isgomock struct{}
}

// MockGateMockRecorder is the mock recorder for MockGate.
type MockGateMockRecorder struct {
	mock *MockGate
}

// NewMockGate creates a new mock instance.
func NewMockGate(ctrl *gomock.Controller) *MockGate {
	mock := &MockGate{ctrl: ctrl}
	mock.recorder = &MockGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGate) EXPECT() *MockGateMockRecorder {
	return m.recorder
}

// TryAdmit mocks base method.
func (m *MockGate) TryAdmit(ctx context.Context, request entity.Request) (admissiongate.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAdmit", ctx, request)
	ret0, _ := ret[0].(admissiongate.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryAdmit indicates an expected call of TryAdmit.
func (mr *MockGateMockRecorder) TryAdmit(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAdmit", reflect.TypeOf((*MockGate)(nil).TryAdmit), ctx, request)
}

// MockGates is a mock of Gates interface.
type MockGates struct {
	ctrl     *gomock.Controller
	recorder *MockGatesMockRecorder
	isgomock struct{}
}

// MockGatesMockRecorder is the mock recorder for MockGates.
type MockGatesMockRecorder struct {
	mock *MockGates
}

// NewMockGates creates a new mock instance.
func NewMockGates(ctrl *gomock.Controller) *MockGates {
	mock := &MockGates{ctrl: ctrl}
	mock.recorder = &MockGatesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGates) EXPECT() *MockGatesMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockGates) For(config admissiongate.Config) (admissiongate.Gate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", config)
	ret0, _ := ret[0].(admissiongate.Gate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockGatesMockRecorder) For(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockGates)(nil).For), config)
}
