load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "go_default_test",
    srcs = [
        "harness_test.go",
        "ingest_test.go",
        "list_test.go",
        "queue_status_test.go",
        "suite_test.go",
    ],
    data = [
        "//platform/extension/counter/mysql/schema",
        "//platform/extension/messagequeue/mysql/schema",
        "//service/stovepipe:docker-compose.yml",
        "//service/stovepipe/server:docker_test_context",
        "//stovepipe/extension/storage/mysql/schema",
    ],
    tags = [
        "e2e",
        "integration",
        "requires-network",
    ],
    deps = [
        "//api/stovepipe/protopb:go_default_library",
        "//stovepipe/core/queuepolicy:go_default_library",
        "//stovepipe/entity:go_default_library",
        "//stovepipe/extension/sourcecontrol:go_default_library",
        "//stovepipe/extension/sourcecontrol/fake:go_default_library",
        "//stovepipe/extension/storage:go_default_library",
        "//stovepipe/extension/storage/mysql:go_default_library",
        "//test/testutil:go_default_library",
        "@com_github_go_sql_driver_mysql//:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@com_github_stretchr_testify//suite:go_default_library",
        "@com_github_uber_go_tally//:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
        "@org_golang_google_protobuf//proto:go_default_library",
    ],
)
