// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: gateway.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
	v2 "go.uber.org/yarpc/encoding/protobuf/v2"
	"google.golang.org/protobuf/proto"
)

var _ = ioutil.NopCloser

// SubmitQueueGatewayYARPCClient is the YARPC client-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
	Land(context.Context, *LandRequest, ...yarpc.CallOption) (*LandResponse, error)
	Cancel(context.Context, *CancelRequest, ...yarpc.CallOption) (*CancelResponse, error)
	Status(context.Context, *StatusRequest, ...yarpc.CallOption) (*StatusResponse, error)
}

func newSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, anyResolver v2.AnyResolver, options ...v2.ClientOption) SubmitQueueGatewayYARPCClient {
	return &_SubmitQueueGatewayYARPCCaller{v2.NewStreamClient(
		v2.ClientParams{
			ServiceName:  "uber.submitqueue.gateway.SubmitQueueGateway",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSubmitQueueGatewayYARPCClient builds a new YARPC client for the SubmitQueueGateway service.
func NewSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, options ...v2.ClientOption) SubmitQueueGatewayYARPCClient {
	return newSubmitQueueGatewayYARPCClient(clientConfig, nil, options...)
}

// SubmitQueueGatewayYARPCServer is the YARPC server-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Land(context.Context, *LandRequest) (*LandResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

type buildSubmitQueueGatewayYARPCProceduresParams struct {
	Server      SubmitQueueGatewayYARPCServer
	AnyResolver v2.AnyResolver
}

func buildSubmitQueueGatewayYARPCProcedures(params buildSubmitQueueGatewayYARPCProceduresParams) []transport.Procedure {
	handler := &_SubmitQueueGatewayYARPCHandler{params.Server}
	return v2.BuildProcedures(
		v2.BuildProceduresParams{
			ServiceName: "uber.submitqueue.gateway.SubmitQueueGateway",
			UnaryHandlerParams: []v2.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newSubmitQueueGatewayServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Land",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Land,
							NewRequest:  newSubmitQueueGatewayServiceLandYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Cancel",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Cancel,
							NewRequest:  newSubmitQueueGatewayServiceCancelYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Status",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Status,
							NewRequest:  newSubmitQueueGatewayServiceStatusYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []v2.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []v2.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSubmitQueueGatewayYARPCProcedures prepares an implementation of the SubmitQueueGateway service for YARPC registration.
func BuildSubmitQueueGatewayYARPCProcedures(server SubmitQueueGatewayYARPCServer) []transport.Procedure {
	return buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{Server: server})
}

// FxSubmitQueueGatewayYARPCClientParams defines the input
// for NewFxSubmitQueueGatewayYARPCClient. It provides the
// paramaters to get a SubmitQueueGatewayYARPCClient in an
// Fx application.
type FxSubmitQueueGatewayYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver v2.AnyResolver      `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSubmitQueueGatewayYARPCClientResult defines the output
// of NewFxSubmitQueueGatewayYARPCClient. It provides a
// SubmitQueueGatewayYARPCClient to an Fx application.
type FxSubmitQueueGatewayYARPCClientResult struct {
	fx.Out

	Client SubmitQueueGatewayYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSubmitQueueGatewayYARPCClient provides a SubmitQueueGatewayYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCClient("service-name"),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCClient(name string, options ...v2.ClientOption) interface{} {
	return func(params FxSubmitQueueGatewayYARPCClientParams) FxSubmitQueueGatewayYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(v2.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSubmitQueueGatewayYARPCClientResult{
			Client: newSubmitQueueGatewayYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSubmitQueueGatewayYARPCProceduresParams defines the input
// for NewFxSubmitQueueGatewayYARPCProcedures. It provides the
// paramaters to get SubmitQueueGatewayYARPCServer procedures in an
// Fx application.
type FxSubmitQueueGatewayYARPCProceduresParams struct {
	fx.In

	Server      SubmitQueueGatewayYARPCServer
	AnyResolver v2.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSubmitQueueGatewayYARPCProceduresResult defines the output
// of NewFxSubmitQueueGatewayYARPCProcedures. It provides
// SubmitQueueGatewayYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSubmitQueueGatewayYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSubmitQueueGatewayYARPCProcedures provides SubmitQueueGatewayYARPCServer procedures to an Fx application.
// It expects a SubmitQueueGatewayYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCProcedures(),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCProcedures() interface{} {
	return func(params FxSubmitQueueGatewayYARPCProceduresParams) FxSubmitQueueGatewayYARPCProceduresResult {
		return FxSubmitQueueGatewayYARPCProceduresResult{
			Procedures: buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: reflection.ServerMeta{
				ServiceName:     "uber.submitqueue.gateway.SubmitQueueGateway",
				FileDescriptors: yarpcFileDescriptorClosuref1a937782ebbded5,
			},
		}
	}
}

type _SubmitQueueGatewayYARPCCaller struct {
	streamClient v2.StreamClient
}

func (c *_SubmitQueueGatewayYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newSubmitQueueGatewayServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Land(ctx context.Context, request *LandRequest, options ...yarpc.CallOption) (*LandResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Land", request, newSubmitQueueGatewayServiceLandYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*LandResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceLandYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Cancel(ctx context.Context, request *CancelRequest, options ...yarpc.CallOption) (*CancelResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Cancel", request, newSubmitQueueGatewayServiceCancelYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*CancelResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceCancelYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Status(ctx context.Context, request *StatusRequest, options ...yarpc.CallOption) (*StatusResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Status", request, newSubmitQueueGatewayServiceStatusYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*StatusResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceStatusYARPCResponse, responseMessage)
	}
	return response, err
}

type _SubmitQueueGatewayYARPCHandler struct {
	server SubmitQueueGatewayYARPCServer
}

func (h *_SubmitQueueGatewayYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Land(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *LandRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*LandRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceLandYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Land(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Cancel(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *CancelRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*CancelRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceCancelYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Cancel(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Status(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *StatusRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*StatusRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceStatusYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Status(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSubmitQueueGatewayServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newSubmitQueueGatewayServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

func newSubmitQueueGatewayServiceLandYARPCRequest() proto.Message {
	return &LandRequest{}
}

func newSubmitQueueGatewayServiceLandYARPCResponse() proto.Message {
	return &LandResponse{}
}

func newSubmitQueueGatewayServiceCancelYARPCRequest() proto.Message {
	return &CancelRequest{}
}

func newSubmitQueueGatewayServiceCancelYARPCResponse() proto.Message {
	return &CancelResponse{}
}

func newSubmitQueueGatewayServiceStatusYARPCRequest() proto.Message {
	return &StatusRequest{}
}

func newSubmitQueueGatewayServiceStatusYARPCResponse() proto.Message {
	return &StatusResponse{}
}

var (
	emptySubmitQueueGatewayServicePingYARPCRequest    = &PingRequest{}
	emptySubmitQueueGatewayServicePingYARPCResponse   = &PingResponse{}
	emptySubmitQueueGatewayServiceLandYARPCRequest    = &LandRequest{}
	emptySubmitQueueGatewayServiceLandYARPCResponse   = &LandResponse{}
	emptySubmitQueueGatewayServiceCancelYARPCRequest  = &CancelRequest{}
	emptySubmitQueueGatewayServiceCancelYARPCResponse = &CancelResponse{}
	emptySubmitQueueGatewayServiceStatusYARPCRequest  = &StatusRequest{}
	emptySubmitQueueGatewayServiceStatusYARPCResponse = &StatusResponse{}
)

var yarpcFileDescriptorClosuref1a937782ebbded5 = [][]byte{
	// gateway.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x51, 0x6b, 0xdb, 0x3c,
		0x14, 0x8d, 0xe3, 0xc4, 0x4d, 0xae, 0x93, 0x92, 0x4f, 0x94, 0x62, 0x42, 0x3f, 0x96, 0x6a, 0x6c,
		0x0d, 0x7b, 0x70, 0x21, 0x63, 0x5b, 0x59, 0x61, 0x90, 0x76, 0x6e, 0xf7, 0xd0, 0x96, 0xd6, 0x5e,
		0x19, 0x0c, 0x46, 0x51, 0x1c, 0xe1, 0x9a, 0xd5, 0x76, 0x6a, 0xc9, 0x1d, 0xd9, 0xf3, 0xf6, 0x33,
		0xf6, 0xbf, 0xf6, 0x73, 0x86, 0x25, 0xb9, 0x75, 0x60, 0x76, 0x1f, 0xf6, 0xa6, 0x7b, 0x75, 0xce,
		0xb9, 0x47, 0xd2, 0xbd, 0x36, 0xf4, 0x03, 0xc2, 0xe9, 0x37, 0xb2, 0xb4, 0x17, 0x69, 0xc2, 0x13,
		0x64, 0x65, 0x33, 0x9a, 0xda, 0x2c, 0x9b, 0x45, 0x21, 0xbf, 0xcd, 0x68, 0x46, 0x6d, 0xb5, 0x8f,
		0x77, 0xc0, 0x3c, 0x0f, 0xe3, 0xc0, 0xa5, 0xb7, 0x19, 0x65, 0x1c, 0x59, 0xb0, 0x16, 0x51, 0xc6,
		0x48, 0x40, 0x2d, 0x6d, 0xa4, 0x8d, 0xbb, 0x6e, 0x11, 0xe2, 0x9f, 0x1a, 0xf4, 0x24, 0x92, 0x2d,
		0x92, 0x98, 0xd1, 0x6a, 0x28, 0xda, 0x86, 0x1e, 0xa3, 0xe9, 0x5d, 0xe8, 0xd3, 0xab, 0x98, 0x44,
		0xd4, 0x6a, 0x8a, 0x6d, 0x53, 0xe5, 0xce, 0x48, 0x44, 0xd1, 0x16, 0x74, 0x79, 0x18, 0x51, 0xc6,
		0x49, 0xb4, 0xb0, 0xf4, 0x91, 0x36, 0xd6, 0xdd, 0x87, 0x04, 0x1a, 0x42, 0xe7, 0x3a, 0x61, 0x5c,
		0x90, 0x5b, 0x82, 0x7c, 0x1f, 0xe3, 0x2d, 0x30, 0x0e, 0xaf, 0x49, 0x1c, 0x50, 0x84, 0xa0, 0x95,
		0xa5, 0x21, 0xb3, 0xb4, 0x91, 0x3e, 0xee, 0xba, 0x62, 0x8d, 0x7f, 0x69, 0x60, 0x9e, 0x90, 0x78,
		0x5e, 0x9c, 0x67, 0x03, 0xda, 0xe2, 0xbc, 0xca, 0xa2, 0x0c, 0xd0, 0x1e, 0x18, 0xbe, 0xd0, 0x10,
		0xd6, 0xcc, 0xc9, 0xc8, 0xae, 0xba, 0x1f, 0x5b, 0xd6, 0x72, 0x15, 0x1e, 0xbd, 0x83, 0x0e, 0xe3,
		0x29, 0xe1, 0x34, 0x58, 0x0a, 0x67, 0xeb, 0x13, 0x5c, 0xcd, 0xf5, 0x14, 0xd2, 0xbd, 0xe7, 0x60,
		0x0c, 0x3d, 0x69, 0x4f, 0x5d, 0x22, 0x82, 0x16, 0xbb, 0x0d, 0xe7, 0xca, 0x9e, 0x58, 0xe3, 0x7d,
		0xe8, 0x1f, 0x92, 0xd8, 0xa7, 0x37, 0xc5, 0x21, 0xfe, 0x02, 0x42, 0x9b, 0x60, 0xa4, 0x94, 0xb0,
		0x24, 0x56, 0xb7, 0xab, 0x22, 0x3c, 0x80, 0xf5, 0x82, 0x2c, 0x4b, 0xe0, 0xa7, 0xd0, 0xf7, 0x38,
		0xe1, 0x19, 0xab, 0x91, 0xc3, 0xbf, 0x35, 0x58, 0x2f, 0x50, 0xca, 0xda, 0x26, 0x18, 0x4c, 0x64,
		0x14, 0x50, 0x45, 0xe8, 0x7f, 0x80, 0x1b, 0xc2, 0xf8, 0x15, 0x4d, 0xd3, 0x24, 0x55, 0xd5, 0xbb,
		0x79, 0xc6, 0xc9, 0x13, 0xc8, 0x85, 0x4e, 0x44, 0x39, 0x99, 0x13, 0x4e, 0x2c, 0x7d, 0xa4, 0x8f,
		0xcd, 0xc9, 0xeb, 0xba, 0x1b, 0x2a, 0x97, 0xb4, 0x4f, 0x15, 0xd1, 0x89, 0x79, 0xba, 0x74, 0xef,
		0x75, 0x86, 0xfb, 0xd0, 0x5f, 0xd9, 0x42, 0x03, 0xd0, 0xbf, 0xd2, 0xa5, 0x32, 0x96, 0x2f, 0xf3,
		0x87, 0xbe, 0x23, 0x37, 0x59, 0xd1, 0x6c, 0x32, 0x78, 0xdb, 0xdc, 0xd3, 0xf0, 0x36, 0xb4, 0xa5,
		0xb3, 0xea, 0xde, 0xa6, 0xb0, 0x79, 0x19, 0xa7, 0xd4, 0x4f, 0x82, 0x38, 0xfc, 0x4e, 0xe7, 0x17,
		0xb9, 0x47, 0xc9, 0x79, 0x05, 0x6d, 0x79, 0x4e, 0x4d, 0x34, 0xca, 0x93, 0xea, 0xa3, 0x08, 0xbc,
		0x2b, 0xd1, 0x0f, 0x6d, 0xd7, 0x2c, 0xb5, 0x1d, 0x26, 0xb0, 0xa1, 0xde, 0xe0, 0x2c, 0xe1, 0x47,
		0x49, 0x16, 0xcf, 0xff, 0xa9, 0x48, 0xf1, 0x8e, 0xcd, 0x87, 0x77, 0x7c, 0x31, 0x85, 0x4e, 0xd1,
		0x75, 0xc8, 0x84, 0xb5, 0xf7, 0xce, 0xd1, 0xf4, 0xf2, 0xe4, 0xe3, 0xa0, 0x81, 0x00, 0x0c, 0xd7,
		0x39, 0x98, 0x7a, 0xce, 0x40, 0x43, 0xff, 0x41, 0xdf, 0xbb, 0xb8, 0x9c, 0x7a, 0x1f, 0xae, 0x54,
		0xaa, 0x89, 0xba, 0xd0, 0x3e, 0x75, 0xdc, 0x63, 0x67, 0xa0, 0x4f, 0x7e, 0xe8, 0x80, 0x3c, 0x51,
		0x5b, 0xdc, 0xc3, 0xb1, 0x2c, 0x8d, 0x3e, 0x41, 0x2b, 0x1f, 0x7f, 0xf4, 0xac, 0xda, 0x5d, 0xe9,
		0x43, 0x32, 0x7c, 0xfe, 0x18, 0x4c, 0x75, 0x67, 0x23, 0x17, 0xce, 0x47, 0xa2, 0x4e, 0xb8, 0x34,
		0xd1, 0x75, 0xc2, 0xe5, 0xc9, 0xc2, 0x0d, 0xf4, 0x05, 0x0c, 0x39, 0x0a, 0x68, 0xa7, 0x66, 0xbe,
		0xcb, 0x93, 0x36, 0x1c, 0x3f, 0x0e, 0x2c, 0xcb, 0xcb, 0xf6, 0xad, 0x93, 0x5f, 0x99, 0xbc, 0x3a,
		0xf9, 0xd5, 0x49, 0xc0, 0x8d, 0x83, 0x00, 0xb6, 0xfc, 0x24, 0xaa, 0x24, 0x1c, 0xf4, 0xd4, 0xc3,
		0x9c, 0xe7, 0x1f, 0xf8, 0x73, 0xed, 0xf3, 0x9b, 0x20, 0xe4, 0xd7, 0xd9, 0xcc, 0xf6, 0x93, 0x68,
		0x37, 0x27, 0xed, 0x96, 0x48, 0x2b, 0x6b, 0x25, 0xb0, 0x2b, 0xfe, 0x0c, 0x8b, 0xd9, 0xcc, 0x10,
		0x8b, 0x97, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x41, 0x0f, 0xf0, 0x33, 0x06, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SubmitQueueGatewayYARPCClient {
			return NewSubmitQueueGatewayYARPCClient(clientConfig, v2.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
