// Code generated by MockGen. DO NOT EDIT.
// Source: recorder.go
//
// Generated by this command:
//
//	mockgen -source=recorder.go -destination=mock/recorder_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/stovepipe/entity"
	storage "github.com/uber/submitqueue/stovepipe/extension/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// RecordRequestState mocks base method.
func (m *MockRecorder) RecordRequestState(arg0 context.Context, arg1 storage.RequestLogStore, arg2 entity.Request, arg3 entity.RequestOutcomeReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRequestState", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRequestState indicates an expected call of RecordRequestState.
func (mr *MockRecorderMockRecorder) RecordRequestState(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequestState", reflect.TypeOf((*MockRecorder)(nil).RecordRequestState), arg0, arg1, arg2, arg3)
}
