# Bazel wrapper
BAZEL = ./tool/bazel

# Docker Compose wrapper
COMPOSE = docker-compose

# SubmitQueue compose files
COMPOSE_FILE = example/submitqueue/docker-compose.yml
GATEWAY_COMPOSE_FILE = example/submitqueue/gateway/server/docker-compose.yml
ORCHESTRATOR_COMPOSE_FILE = example/submitqueue/orchestrator/server/docker-compose.yml

# Fixed project name for local manual testing (tests use unique random names)
SUBMITQUEUE_LOCAL_PROJECT = submitqueue

# Stovepipe compose file (single Ping-only service)
STOVEPIPE_COMPOSE_FILE = example/stovepipe/docker-compose.yml

# Fixed project name for local manual testing (tests use unique random names)
STOVEPIPE_LOCAL_PROJECT = stovepipe

# Runway compose files
RUNWAY_COMPOSE_FILE = example/runway/server/docker-compose.yml

# Fixed project name for local manual testing (tests use unique random names)
RUNWAY_LOCAL_PROJECT = runway

# yamlfmt version for YAML formatting (override with: make fmt YAMLFMT_VERSION=v0.16.0)
YAMLFMT_VERSION ?= v0.16.0

# goimports version for Go formatting + import fixing
GOIMPORTS_VERSION ?= v0.33.0

# Proto packages: api/<domain>/<service> dirs whose protopb/ holds the generated
# stubs. Each is generated by Bazel into bazel-bin/tool/proto/api_<domain>_<service>/
# (the out_dir convention in tool/proto/BUILD.bazel) and copied back here. A
# package may hold multiple .proto files (e.g. an RPC contract plus messagequeue
# contracts); all generated stubs land in the same protopb/ dir.
PROTO_PACKAGES = api/base/change api/base/mergestrategy api/base/messagequeue api/runway/messagequeue api/runway api/submitqueue/gateway api/submitqueue/orchestrator api/stovepipe stovepipe/core/messagequeue

# Set REPO_ROOT for docker-compose
export REPO_ROOT := $(shell pwd)

# Fails if git working tree is dirty. Usage: $(call assert_clean,fix command)
define assert_clean
	@if ! git diff --quiet; then \
		echo "The following files need updating:" >&2; \
		git diff --name-only >&2; \
		echo "" >&2; \
		echo "Please run '$(1)' locally and commit the changes." >&2; \
		exit 1; \
	fi
endef

.PHONY: build build-all-linux build-runway-linux build-submitqueue-gateway-linux build-submitqueue-orchestrator-linux build-stovepipe-linux check-gazelle check-mocks check-tidy clean clean-proto deps e2e-test fmt gazelle integration-test integration-test-submitqueue-consumer integration-test-extensions integration-test-submitqueue-gateway integration-test-submitqueue-orchestrator license-fix lint lint-fmt lint-license local-init-runway-queue-schema local-init-stovepipe-schemas local-runway-start local-runway-stop local-submitqueue-clean local-submitqueue-gateway-start local-submitqueue-gateway-stop local-init-submitqueue-schemas local-submitqueue-logs local-submitqueue-orchestrator-start local-submitqueue-orchestrator-stop local-submitqueue-ps local-submitqueue-restart local-submitqueue-start local-stop local-stovepipe-logs local-stovepipe-start local-stovepipe-stop mocks proto query-deps query-targets run-client-runway run-client-submitqueue-gateway run-client-submitqueue-orchestrator run-client-stovepipe run-queue-admin test test-no-cache tidy tidy-bazel tidy-go help


build: ## Build all services and examples
	@echo "Building all targets with Bazel..."
	@$(BAZEL) build //...
	@echo "Build complete!"

# Build Linux binaries required for Docker containers
build-all-linux: build-submitqueue-gateway-linux build-submitqueue-orchestrator-linux build-stovepipe-linux build-runway-linux ## Build all Linux binaries for Docker
	@echo "All Linux binaries ready for Docker"

build-runway-linux: ## Build Runway Linux binary for Docker
	@echo "Building Runway Linux binary for Docker..."
	@$(BAZEL) build --platforms=@rules_go//go/toolchain:linux_amd64 //example/runway/server:runway
	@mkdir -p .docker-bin
	@cp -f bazel-bin/example/runway/server/runway_/runway .docker-bin/runway 2>/dev/null || \
	 cp -f bazel-bin/example/runway/server/runway .docker-bin/runway
	@echo "Runway Linux binary ready at .docker-bin/runway"

build-submitqueue-gateway-linux: ## Build Gateway Linux binary for Docker
	@echo "Building Gateway Linux binary for Docker..."
	@$(BAZEL) build --platforms=@rules_go//go/toolchain:linux_amd64 //example/submitqueue/gateway/server:gateway
	@mkdir -p .docker-bin
	@cp -f bazel-bin/example/submitqueue/gateway/server/gateway_/gateway .docker-bin/gateway 2>/dev/null || \
	 cp -f bazel-bin/example/submitqueue/gateway/server/gateway .docker-bin/gateway
	@echo "Gateway Linux binary ready at .docker-bin/gateway"

build-submitqueue-orchestrator-linux: ## Build Orchestrator Linux binary for Docker
	@echo "Building Orchestrator Linux binary for Docker..."
	@$(BAZEL) build --platforms=@rules_go//go/toolchain:linux_amd64 //example/submitqueue/orchestrator/server:orchestrator
	@mkdir -p .docker-bin
	@cp -f bazel-bin/example/submitqueue/orchestrator/server/orchestrator_/orchestrator .docker-bin/orchestrator 2>/dev/null || \
	 cp -f bazel-bin/example/submitqueue/orchestrator/server/orchestrator .docker-bin/orchestrator
	@echo "Orchestrator Linux binary ready at .docker-bin/orchestrator"

build-stovepipe-linux: ## Build Stovepipe Linux binary for Docker
	@echo "Building Stovepipe Linux binary for Docker..."
	@$(BAZEL) build --platforms=@rules_go//go/toolchain:linux_amd64 //example/stovepipe/server:stovepipe
	@mkdir -p .docker-bin
	@cp -f bazel-bin/example/stovepipe/server/stovepipe_/stovepipe .docker-bin/stovepipe 2>/dev/null || \
	 cp -f bazel-bin/example/stovepipe/server/stovepipe .docker-bin/stovepipe
	@echo "Stovepipe Linux binary ready at .docker-bin/stovepipe"

check-gazelle: ## Check BUILD.bazel files are up to date
	@echo "Running Gazelle to check BUILD files..."
	@$(BAZEL) run //:gazelle
	$(call assert_clean,make gazelle)
	@echo "BUILD files are up to date."

check-mocks: mocks ## Check mock files are up to date
	$(call assert_clean,make mocks)
	@echo "Mock files are up to date."

check-tidy: tidy ## Check that go.mod and MODULE.bazel are tidy
	$(call assert_clean,make tidy)
	@echo "Module files are up to date."

clean: ## Clean generated files and binaries
	@echo "Cleaning with Bazel..."
	@$(BAZEL) clean
	@rm -rf bin/
	@echo "Clean complete!"

clean-proto: ## Clean generated proto files
	@echo "Cleaning generated proto files..."
	@rm -f $(foreach p,$(PROTO_PACKAGES),$(p)/protopb/*.pb.go $(p)/protopb/*.pb.yarpc.go)
	@echo "Proto clean complete!"

deps: tidy-go ## Download and tidy Go dependencies
	@echo "Dependencies installed!"

e2e-test: build-all-linux ## Run end-to-end tests (hermetic, auto-builds binaries; runs in parallel)
	@echo "Running end-to-end tests (parallel)..."
	@$(BAZEL) test //test/e2e/... --test_output=errors

fmt: ## Format Go and YAML code
	@echo "Formatting Go code..."
	@find . -name '*.go' -not -path './pkg/*' -not -path './bazel-*' | xargs $(BAZEL) run @rules_go//go -- run golang.org/x/tools/cmd/goimports@$(GOIMPORTS_VERSION) -w
	@echo "Formatting YAML files..."
	@$(BAZEL) run @rules_go//go -- run github.com/google/yamlfmt/cmd/yamlfmt@$(YAMLFMT_VERSION)
	@echo "Formatting complete!"

gazelle: ## Update BUILD.bazel files
	@echo "Running Gazelle to update BUILD files..."
	@$(BAZEL) run //:gazelle

integration-test: build-all-linux ## Run all integration tests (auto-builds binaries; runs in parallel)
	@echo "Running all integration tests (parallel)..."
	@$(BAZEL) test //test/integration/... --test_output=errors

integration-test-submitqueue-consumer: ## Run Consumer integration tests
	@echo "Running Consumer integration tests..."
	@$(BAZEL) test //test/integration/submitqueue/core/consumer:go_default_test --test_output=streamed

integration-test-extensions: ## Run extension integration tests (runs in parallel)
	@echo "Running extension integration tests (parallel)..."
	@$(BAZEL) test //test/integration/submitqueue/extension/... //test/integration/extension/... --test_output=errors

integration-test-submitqueue-gateway: build-submitqueue-gateway-linux ## Run Gateway integration tests (auto-builds binary)
	@echo "Running Gateway integration tests..."
	@$(BAZEL) test //test/integration/submitqueue/gateway:go_default_test --test_output=streamed

integration-test-submitqueue-orchestrator: build-submitqueue-orchestrator-linux ## Run Orchestrator integration tests (auto-builds binary)
	@echo "Running Orchestrator integration tests..."
	@$(BAZEL) test //test/integration/submitqueue/orchestrator:go_default_test --test_output=streamed

license-fix: ## Add missing license headers to source files
	@$(BAZEL) run //tool/linter/licenseheader -- --fix

lint: lint-fmt lint-license ## Run all linters
	@echo "All lint checks passed."

lint-fmt: fmt ## Check code formatting (fails if unformatted)
	$(call assert_clean,make fmt)
	@echo "All code is properly formatted."

lint-license: ## Check license headers on all source files
	@$(BAZEL) run //tool/linter/licenseheader -- --check

local-submitqueue-clean: ## Stop and remove all local services, volumes, and images
	@echo "Cleaning all services and data..."
	@$(COMPOSE) -f $(COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) down -v --rmi local
	@echo "All services, volumes, and images removed."

local-submitqueue-gateway-start: build-submitqueue-gateway-linux ## Start Gateway service locally (Gateway + 2 MySQL databases)
	@echo "Starting Gateway with docker-compose..."
	@$(COMPOSE) -f $(GATEWAY_COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) up -d --build --wait
	@echo "Applying database schemas..."
	@$(MAKE) -s local-init-submitqueue-schemas
	@echo ""
	@echo "✅ Gateway is running!"
	@echo ""
	@$(COMPOSE) -f $(GATEWAY_COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) ps
	@echo ""
	@echo "Gateway gRPC port: $$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-gateway-service-1 8080 2>/dev/null | cut -d: -f2 || echo 'unknown')"
	@echo "MySQL App port:    $$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-app-1 3306 2>/dev/null | cut -d: -f2 || echo 'unknown')"
	@echo "MySQL Queue port:  $$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-queue-1 3306 2>/dev/null | cut -d: -f2 || echo 'unknown')"

local-submitqueue-gateway-stop: ## Stop Gateway service
	@echo "Stopping Gateway services..."
	@$(COMPOSE) -f $(GATEWAY_COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) down
	@echo "Gateway services stopped."

local-init-submitqueue-schemas: ## Manually apply all database schemas
	@echo "Applying storage schema to mysql-app..."
	@for file in submitqueue/extension/storage/mysql/schema/*.sql; do \
		echo "  - Applying $$(basename $$file)..."; \
		docker exec -i $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-app-1 mysql -uroot -proot submitqueue < $$file 2>&1 | grep -v "Using a password" || true; \
	done
	@echo "Applying counter schema to mysql-app..."
	@for file in platform/extension/counter/mysql/schema/*.sql; do \
		echo "  - Applying $$(basename $$file)..."; \
		docker exec -i $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-app-1 mysql -uroot -proot submitqueue < $$file 2>&1 | grep -v "Using a password" || true; \
	done
	@echo "Applying queue schema to mysql-queue..."
	@for file in platform/extension/messagequeue/mysql/schema/*.sql; do \
		echo "  - Applying $$(basename $$file)..."; \
		docker exec -i $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-queue-1 mysql -uroot -proot submitqueue < $$file 2>&1 | grep -v "Using a password" || true; \
	done
	@echo "✅ All schemas applied successfully"

local-init-runway-queue-schema: ## Apply queue schema only (mysql-queue) for Runway compose stacks
	@echo "Applying queue schema to mysql-queue (Runway; consumes the merge queues)..."
	@for file in platform/extension/messagequeue/mysql/schema/*.sql; do \
		echo "  - Applying $$(basename $$file)..."; \
		docker exec -i $(RUNWAY_LOCAL_PROJECT)-mysql-queue-1 mysql -uroot -proot submitqueue < $$file 2>&1 | grep -v "Using a password" || true; \
	done
	@echo "✅ Runway queue schema applied successfully"

local-init-stovepipe-schemas: ## Apply storage (mysql-app) and queue (mysql-queue) schemas for Stovepipe compose stacks
	@echo "Applying storage schema to mysql-app..."
	@for file in stovepipe/extension/storage/mysql/schema/*.sql; do \
		echo "  - Applying $$(basename $$file)..."; \
		docker exec -i $(STOVEPIPE_LOCAL_PROJECT)-mysql-app-1 mysql -uroot -proot submitqueue < $$file 2>&1 | grep -v "Using a password" || true; \
	done
	@echo "Applying queue schema to mysql-queue..."
	@for file in platform/extension/messagequeue/mysql/schema/*.sql; do \
		echo "  - Applying $$(basename $$file)..."; \
		docker exec -i $(STOVEPIPE_LOCAL_PROJECT)-mysql-queue-1 mysql -uroot -proot submitqueue < $$file 2>&1 | grep -v "Using a password" || true; \
	done
	@echo "✅ Stovepipe schemas applied successfully"

local-runway-start: build-runway-linux ## Start Runway locally (runway + MySQL queue)
	@echo "Starting Runway with compose..."
	@$(COMPOSE) -f $(RUNWAY_COMPOSE_FILE) -p $(RUNWAY_LOCAL_PROJECT) up -d --build --wait
	@echo "Applying queue schema to mysql-queue (no Runway app schema)..."
	@$(MAKE) -s local-init-runway-queue-schema
	@echo ""
	@echo "✅ Runway is running!"
	@echo ""
	@$(COMPOSE) -f $(RUNWAY_COMPOSE_FILE) -p $(RUNWAY_LOCAL_PROJECT) ps
	@echo ""
	@echo "Runway gRPC port: $$(docker port $(RUNWAY_LOCAL_PROJECT)-runway-service-1 8080 2>/dev/null | cut -d: -f2 || echo 'unknown')"
	@echo "MySQL Queue port: $$(docker port $(RUNWAY_LOCAL_PROJECT)-mysql-queue-1 3306 2>/dev/null | cut -d: -f2 || echo 'unknown')"

local-runway-stop: ## Stop Runway service
	@echo "Stopping Runway services..."
	@$(COMPOSE) -f $(RUNWAY_COMPOSE_FILE) -p $(RUNWAY_LOCAL_PROJECT) down
	@echo "Runway services stopped."

local-submitqueue-logs: ## View logs from all running services
	@$(COMPOSE) -f $(COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) logs -f

local-submitqueue-orchestrator-start: build-submitqueue-orchestrator-linux ## Start Orchestrator service locally (Orchestrator + 2 MySQL databases)
	@echo "Starting Orchestrator with docker-compose..."
	@$(COMPOSE) -f $(ORCHESTRATOR_COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) up -d --build --wait
	@echo "Applying database schemas..."
	@$(MAKE) -s local-init-submitqueue-schemas
	@echo ""
	@echo "✅ Orchestrator is running!"
	@echo ""
	@$(COMPOSE) -f $(ORCHESTRATOR_COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) ps
	@echo ""
	@echo "Orchestrator gRPC port: $$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-orchestrator-service-1 8080 2>/dev/null | cut -d: -f2 || echo 'unknown')"
	@echo "MySQL App port:         $$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-app-1 3306 2>/dev/null | cut -d: -f2 || echo 'unknown')"
	@echo "MySQL Queue port:       $$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-queue-1 3306 2>/dev/null | cut -d: -f2 || echo 'unknown')"

local-submitqueue-orchestrator-stop: ## Stop Orchestrator service
	@echo "Stopping Orchestrator services..."
	@$(COMPOSE) -f $(ORCHESTRATOR_COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) down
	@echo "Orchestrator services stopped."

local-submitqueue-ps: ## Show running containers and their ports
	@echo "Running containers and ports:"
	@echo ""
	@$(COMPOSE) -f $(COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) ps
	@echo ""
	@echo "📡 Service Endpoints:"
	@echo "  Gateway gRPC:      localhost:$$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-gateway-service-1 8080 2>/dev/null | cut -d: -f2 || echo 'not running')"
	@echo "  Orchestrator gRPC: localhost:$$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-orchestrator-service-1 8080 2>/dev/null | cut -d: -f2 || echo 'not running')"
	@echo ""
	@echo "🗄️  Database Endpoints:"
	@echo "  MySQL App:    localhost:$$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-app-1 3306 2>/dev/null | cut -d: -f2 || echo 'not running')"
	@echo "  MySQL Queue:  localhost:$$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-queue-1 3306 2>/dev/null | cut -d: -f2 || echo 'not running')"
	@echo ""
	@echo "💡 Usage:"
	@echo "  # Connect to MySQL App DB"
	@echo "  mysql -h127.0.0.1 -P$$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-mysql-app-1 3306 2>/dev/null | cut -d: -f2 || echo 'PORT') -uroot -proot submitqueue"
	@echo ""
	@echo "  # Call Gateway gRPC"
	@echo "  grpcurl -plaintext -d '{\"message\":\"test\"}' localhost:$$(docker port $(SUBMITQUEUE_LOCAL_PROJECT)-gateway-service-1 8080 2>/dev/null | cut -d: -f2 || echo 'PORT') submitqueue.SubmitQueueGateway/Ping"
	@echo ""
	@echo "  # View logs"
	@echo "  make local-submitqueue-logs"

local-submitqueue-restart: build-all-linux ## Restart all services (rebuild and restart)
	@echo "Restarting all services..."
	@$(COMPOSE) -f $(COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) restart
	@echo "Services restarted!"
	@make local-submitqueue-ps

local-submitqueue-start: build-all-linux ## Start full stack (Gateway + Orchestrator + MySQL)
	@echo "Starting full stack with docker-compose..."
	@$(COMPOSE) -f $(COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) up -d --build --wait
	@echo "Applying database schemas..."
	@$(MAKE) -s local-init-submitqueue-schemas
	@echo ""
	@echo "✅ Full stack is running!"
	@echo ""
	@make local-submitqueue-ps

local-stop: ## Stop all services (keep data)
	@echo "Stopping all services..."
	@$(COMPOSE) -f $(COMPOSE_FILE) -p $(SUBMITQUEUE_LOCAL_PROJECT) down
	@$(COMPOSE) -f $(STOVEPIPE_COMPOSE_FILE) -p $(STOVEPIPE_LOCAL_PROJECT) down
	@$(COMPOSE) -f $(RUNWAY_COMPOSE_FILE) -p $(RUNWAY_LOCAL_PROJECT) down
	@echo "Services stopped. Data volumes preserved."

local-stovepipe-logs: ## View logs from the running Stovepipe service
	@$(COMPOSE) -f $(STOVEPIPE_COMPOSE_FILE) -p $(STOVEPIPE_LOCAL_PROJECT) logs -f

local-stovepipe-start: build-stovepipe-linux ## Start Stovepipe service (gRPC service + MySQL storage + MySQL queue)
	@echo "Starting Stovepipe service with compose..."
	@$(COMPOSE) -f $(STOVEPIPE_COMPOSE_FILE) -p $(STOVEPIPE_LOCAL_PROJECT) up -d --build --wait
	@echo "Applying storage and queue schemas..."
	@$(MAKE) -s local-init-stovepipe-schemas
	@echo ""
	@echo "✅ Stovepipe service is running!"
	@echo ""
	@$(COMPOSE) -f $(STOVEPIPE_COMPOSE_FILE) -p $(STOVEPIPE_LOCAL_PROJECT) ps
	@echo ""
	@echo "Stovepipe gRPC port: $$(docker port $(STOVEPIPE_LOCAL_PROJECT)-stovepipe-service-1 8080 2>/dev/null | cut -d: -f2 || echo 'unknown')"

local-stovepipe-stop: ## Stop the Stovepipe service
	@echo "Stopping Stovepipe service..."
	@$(COMPOSE) -f $(STOVEPIPE_COMPOSE_FILE) -p $(STOVEPIPE_LOCAL_PROJECT) down
	@echo "Stovepipe service stopped."

mocks: ## Generate mock files using mockgen
	@echo "Generating mocks..."
	@$(BAZEL) run @rules_go//go -- generate ./submitqueue/extension/storage/... ./submitqueue/extension/buildrunner/... ./submitqueue/extension/changeprovider/... ./platform/extension/counter/... ./platform/extension/messagequeue/... ./submitqueue/extension/queueconfig/... ./submitqueue/extension/mergechecker/... ./submitqueue/extension/pusher/... ./submitqueue/extension/scorer/... ./submitqueue/extension/conflict/... ./platform/consumer/... ./stovepipe/extension/storage/... ./stovepipe/extension/sourcecontrol/...
	@echo "Mocks generated successfully!"

proto: ## Generate protobuf files from .proto definitions
	@echo "Generating protobuf files with Bazel..."
	@$(BAZEL) build //tool/proto:generated
	@set -e; for pkg in $(PROTO_PACKAGES); do \
	  out=$$(echo $$pkg | tr / _); \
	  mkdir -p $$pkg/protopb; \
	  for f in bazel-bin/tool/proto/$$out/*.go; do \
	    cp -f $$f $$pkg/protopb/$$(basename $$f); \
	    chmod 0644 $$pkg/protopb/$$(basename $$f); \
	  done; \
	done
	@$(BAZEL) run @rules_go//go -- run golang.org/x/tools/cmd/goimports@$(GOIMPORTS_VERSION) -w $(addsuffix /protopb,$(PROTO_PACKAGES))
	@echo "Protobuf files generated successfully!"

# Bazel query helpers
query-deps:
	@$(BAZEL) query 'deps(//example/submitqueue/gateway/server:gateway)'

query-targets:
	@$(BAZEL) query //...

# Run gateway client (connects to any running gateway service)
run-client-submitqueue-gateway:
	@$(BAZEL) run //example/submitqueue/gateway/client:gateway -- -addr $(or $(SERVER_ADDR),localhost:8081) -message "$(or $(MESSAGE),ping)"

# Run orchestrator client (connects to any running orchestrator service)
run-client-submitqueue-orchestrator:
	@$(BAZEL) run //example/submitqueue/orchestrator/client:orchestrator -- -addr $(or $(SERVER_ADDR),localhost:8082) -message "$(or $(MESSAGE),ping)"

# Run stovepipe client (connects to any running stovepipe service)
run-client-stovepipe:
	@$(BAZEL) run //example/stovepipe/client:stovepipe -- -addr $(or $(SERVER_ADDR),localhost:8083) -message "$(or $(MESSAGE),ping)"

# Run runway client (connects to any running runway service)
run-client-runway:
	@$(BAZEL) run //example/runway/client:runway -- -addr $(or $(SERVER_ADDR),localhost:8086) -message "$(or $(MESSAGE),ping)"

run-queue-admin: ## Run queue-admin CLI (use ARGS to pass arguments, e.g. make run-queue-admin ARGS="list-topics")
	@$(BAZEL) run //platform/extension/messagequeue/mysql/ctl -- $(ARGS)

test: ## Run unit tests
	@echo "Running unit tests..."
	@$(BAZEL) test //... --test_tag_filters=-manual,-integration || echo "No unit tests found (only integration tests exist)"

test-no-cache: ## Run unit tests without cache (force re-run)
	@echo "Running unit tests (no cache)..."
	@$(BAZEL) test //... --test_tag_filters=-manual,-integration --nocache_test_results

tidy: tidy-go tidy-bazel ## Run go mod tidy and bazel mod tidy

tidy-bazel: ## Run bazel mod tidy
	@echo "Running bazel mod tidy..."
	@$(BAZEL) mod tidy

tidy-go: ## Run go mod tidy
	@echo "Running go mod tidy..."
	@$(BAZEL) run @rules_go//go -- mod tidy -e

help: ## Show this help message
	@echo "Available targets:"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-30s\033[0m %s\n", $$1, $$2}'
