package storage

//go:generate mockgen -source=request_log_store.go -destination=mock/request_log_store.go -package=mock

import (
	"context"

	"github.com/uber/submitqueue/entity"
)

// RequestLogStore is an interface that defines methods for managing request log records in an append-only database.
// Request logs are used to reconcile request statuses with eventual consistency into a separate database from RequestStore.
type RequestLogStore interface {
	// Insert appends a new request log record. Timestamps should be generated by the caller and not modified by the implementation.
	Insert(ctx context.Context, log entity.RequestLog) error

	// List retrieves all request log records for a given request ID, ordered by timestamp ascending.
	// Returns ErrNotFound if no records exist for the given request ID.
	List(ctx context.Context, requestID string) ([]entity.RequestLog, error)
}
