// Copyright (c) 2025 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: merge.proto

package protopb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protopb "github.com/uber/submitqueue/api/base/change/protopb"
	protopb1 "github.com/uber/submitqueue/api/base/mergestrategy/protopb"
	_ "github.com/uber/submitqueue/api/base/messagequeue/protopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome is the overall result of applying a MergeRequest's ordered step
// sequence.
type Outcome int32

const (
	// OUTCOME_UNSPECIFIED is the zero value; a well-formed result never uses it.
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	// SUCCEEDED means the whole sequence applied cleanly: mergeable for a
	// dry-run check, merged for a committing merge.
	Outcome_SUCCEEDED Outcome = 1
	// FAILED means the sequence could not be applied: a conflict for a dry-run
	// check, a failed apply for a committing merge.
	Outcome_FAILED Outcome = 2
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "SUCCEEDED",
		2: "FAILED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"SUCCEEDED":           1,
		"FAILED":              2,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_merge_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_merge_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_merge_proto_rawDescGZIP(), []int{0}
}

// MergeStep is one step of an ordered merge: a single change applied with a
// strategy. Runway applies the steps of a request in order on top of the merge
// target; the ordering encodes the base-layering (earlier steps are the
// in-flight base, the last step is the candidate). A change may contain
// multiple URIs (e.g. stacked PRs that land together).
type MergeStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// step_id is an opaque, caller-assigned identifier for this step. Runway
	// treats it as an attribution token only -- it echoes it back per-step in
	// StepResult so a multi-step result is attributable -- and never interprets
	// its contents.
	StepId string `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// change is the code change to apply for this step. A change may carry
	// multiple URIs when the step represents stacked or grouped changes.
	Change *protopb.Change `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	// strategy is how this step's change is integrated into the merge target.
	Strategy      protopb1.Strategy `protobuf:"varint,3,opt,name=strategy,proto3,enum=uber.base.mergestrategy.Strategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeStep) Reset() {
	*x = MergeStep{}
	mi := &file_merge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeStep) ProtoMessage() {}

func (x *MergeStep) ProtoReflect() protoreflect.Message {
	mi := &file_merge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeStep.ProtoReflect.Descriptor instead.
func (*MergeStep) Descriptor() ([]byte, []int) {
	return file_merge_proto_rawDescGZIP(), []int{0}
}

func (x *MergeStep) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *MergeStep) GetChange() *protopb.Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *MergeStep) GetStrategy() protopb1.Strategy {
	if x != nil {
		return x.Strategy
	}
	return protopb1.Strategy(0)
}

// MergeRequest is the payload a client publishes to one of Runway's merge
// queues: the merge-conflict-check topic for a dry-run check, the merge topic
// for a committing merge. The id is owned by the client so it can record the
// in-flight work before publishing and correlate the asynchronous result;
// Runway echoes it back unchanged.
type MergeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the client-owned correlation id for this request (one per request).
	// Runway echoes it back on the result unchanged.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// queue_name is the caller-provided queue name the request belongs to.
	// Runway resolves the merge target and provider config per-queue from this
	// name; no target ref is passed.
	QueueName string `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	// steps is the ordered application sequence: in-flight steps first, the
	// candidate last. A single-element list expresses "candidate vs merge
	// target".
	Steps         []*MergeStep `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_merge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_merge_proto_rawDescGZIP(), []int{1}
}

func (x *MergeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MergeRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *MergeRequest) GetSteps() []*MergeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// StepOutput is a single output a merge step produced on the merge target.
type StepOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the VCS-neutral revision identifier -- a git commit SHA, a Mercurial
	// changeset hash, a Subversion revision number, a Perforce changelist, and so
	// on.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // (room to grow: author, committed_at, parent, ...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepOutput) Reset() {
	*x = StepOutput{}
	mi := &file_merge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepOutput) ProtoMessage() {}

func (x *StepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_merge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepOutput.ProtoReflect.Descriptor instead.
func (*StepOutput) Descriptor() ([]byte, []int) {
	return file_merge_proto_rawDescGZIP(), []int{2}
}

func (x *StepOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// StepResult reports what happened to a single MergeStep, so a multi-step result
// is attributable to the step that produced (or failed to produce) it.
type StepResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// step_id echoes the step_id of the step this result is for.
	StepId string `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// outputs are the revisions this step produced on the merge target, in
	// application order (the order the step created them on the target). Empty
	// for a dry-run check, for a change already present on the target, or for a
	// step that failed to apply.
	Outputs []*StepOutput `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// reason is a human-readable explanation when the step failed to apply.
	// Empty on success.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_merge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_merge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_merge_proto_rawDescGZIP(), []int{3}
}

func (x *StepResult) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepResult) GetOutputs() []*StepOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *StepResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// MergeResult is the payload Runway publishes to the corresponding signal queue
// (merge-conflict-check-signal for a check, merge-signal for a merge) once a
// request completes.
type MergeResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id echoes the client-owned correlation id from the request.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// outcome is SUCCEEDED if the whole ordered step sequence applied cleanly
	// (mergeable for a dry-run check, merged for a committing merge), FAILED
	// otherwise.
	Outcome Outcome `protobuf:"varint,2,opt,name=outcome,proto3,enum=uber.runway.messagequeue.Outcome" json:"outcome,omitempty"`
	// reason is a human-readable explanation when outcome is FAILED. Empty on
	// success.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// steps optionally reports per-step outcomes, in request order. A committing
	// merge populates each step's outputs with the revisions it produced; a
	// dry-run check leaves them empty.
	Steps         []*StepResult `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeResult) Reset() {
	*x = MergeResult{}
	mi := &file_merge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResult) ProtoMessage() {}

func (x *MergeResult) ProtoReflect() protoreflect.Message {
	mi := &file_merge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResult.ProtoReflect.Descriptor instead.
func (*MergeResult) Descriptor() ([]byte, []int) {
	return file_merge_proto_rawDescGZIP(), []int{4}
}

func (x *MergeResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MergeResult) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *MergeResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MergeResult) GetSteps() []*StepResult {
	if x != nil {
		return x.Steps
	}
	return nil
}

var File_merge_proto protoreflect.FileDescriptor

const file_merge_proto_rawDesc = "" +
	"\n" +
	"\vmerge.proto\x12\x18uber.runway.messagequeue\x1a\"api/base/change/proto/change.proto\x1a0api/base/mergestrategy/proto/mergestrategy.proto\x1a.api/base/messagequeue/proto/messagequeue.proto\"\x95\x01\n" +
	"\tMergeStep\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x120\n" +
	"\x06change\x18\x02 \x01(\v2\x18.uber.base.change.ChangeR\x06change\x12=\n" +
	"\bstrategy\x18\x03 \x01(\x0e2!.uber.base.mergestrategy.StrategyR\bstrategy\"\xa2\x01\n" +
	"\fMergeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x129\n" +
	"\x05steps\x18\x03 \x03(\v2#.uber.runway.messagequeue.MergeStepR\x05steps:(\x8a\xb5\x18\x14merge-conflict-check\x8a\xb5\x18\frunway-merge\"\x1c\n" +
	"\n" +
	"StepOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\n" +
	"StepResult\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12>\n" +
	"\aoutputs\x18\x02 \x03(\v2$.uber.runway.messagequeue.StepOutputR\aoutputs\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xdf\x01\n" +
	"\vMergeResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\aoutcome\x18\x02 \x01(\x0e2!.uber.runway.messagequeue.OutcomeR\aoutcome\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12:\n" +
	"\x05steps\x18\x04 \x03(\v2$.uber.runway.messagequeue.StepResultR\x05steps:/\x8a\xb5\x18\x1bmerge-conflict-check-signal\x8a\xb5\x18\fmerge-signal*=\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSUCCEEDED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02Bu\n" +
	"(com.uber.submitqueue.runway.messagequeueB\n" +
	"MergeProtoP\x01Z;github.com/uber/submitqueue/api/runway/messagequeue/protopbb\x06proto3"

var (
	file_merge_proto_rawDescOnce sync.Once
	file_merge_proto_rawDescData []byte
)

func file_merge_proto_rawDescGZIP() []byte {
	file_merge_proto_rawDescOnce.Do(func() {
		file_merge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merge_proto_rawDesc), len(file_merge_proto_rawDesc)))
	})
	return file_merge_proto_rawDescData
}

var file_merge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_merge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_merge_proto_goTypes = []any{
	(Outcome)(0),           // 0: uber.runway.messagequeue.Outcome
	(*MergeStep)(nil),      // 1: uber.runway.messagequeue.MergeStep
	(*MergeRequest)(nil),   // 2: uber.runway.messagequeue.MergeRequest
	(*StepOutput)(nil),     // 3: uber.runway.messagequeue.StepOutput
	(*StepResult)(nil),     // 4: uber.runway.messagequeue.StepResult
	(*MergeResult)(nil),    // 5: uber.runway.messagequeue.MergeResult
	(*protopb.Change)(nil), // 6: uber.base.change.Change
	(protopb1.Strategy)(0), // 7: uber.base.mergestrategy.Strategy
}
var file_merge_proto_depIdxs = []int32{
	6, // 0: uber.runway.messagequeue.MergeStep.change:type_name -> uber.base.change.Change
	7, // 1: uber.runway.messagequeue.MergeStep.strategy:type_name -> uber.base.mergestrategy.Strategy
	1, // 2: uber.runway.messagequeue.MergeRequest.steps:type_name -> uber.runway.messagequeue.MergeStep
	3, // 3: uber.runway.messagequeue.StepResult.outputs:type_name -> uber.runway.messagequeue.StepOutput
	0, // 4: uber.runway.messagequeue.MergeResult.outcome:type_name -> uber.runway.messagequeue.Outcome
	4, // 5: uber.runway.messagequeue.MergeResult.steps:type_name -> uber.runway.messagequeue.StepResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_merge_proto_init() }
func file_merge_proto_init() {
	if File_merge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merge_proto_rawDesc), len(file_merge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merge_proto_goTypes,
		DependencyIndexes: file_merge_proto_depIdxs,
		EnumInfos:         file_merge_proto_enumTypes,
		MessageInfos:      file_merge_proto_msgTypes,
	}.Build()
	File_merge_proto = out.File
	file_merge_proto_goTypes = nil
	file_merge_proto_depIdxs = nil
}
