// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: gateway.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// SubmitQueueGatewayYARPCClient is the YARPC client-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
	Land(context.Context, *LandRequest, ...yarpc.CallOption) (*LandResponse, error)
}

func newSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) SubmitQueueGatewayYARPCClient {
	return &_SubmitQueueGatewayYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.devexp.submitqueue.gateway.SubmitQueueGateway",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSubmitQueueGatewayYARPCClient builds a new YARPC client for the SubmitQueueGateway service.
func NewSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) SubmitQueueGatewayYARPCClient {
	return newSubmitQueueGatewayYARPCClient(clientConfig, nil, options...)
}

// SubmitQueueGatewayYARPCServer is the YARPC server-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Land(context.Context, *LandRequest) (*LandResponse, error)
}

type buildSubmitQueueGatewayYARPCProceduresParams struct {
	Server      SubmitQueueGatewayYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildSubmitQueueGatewayYARPCProcedures(params buildSubmitQueueGatewayYARPCProceduresParams) []transport.Procedure {
	handler := &_SubmitQueueGatewayYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.devexp.submitqueue.gateway.SubmitQueueGateway",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newSubmitQueueGatewayServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Land",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Land,
							NewRequest:  newSubmitQueueGatewayServiceLandYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSubmitQueueGatewayYARPCProcedures prepares an implementation of the SubmitQueueGateway service for YARPC registration.
func BuildSubmitQueueGatewayYARPCProcedures(server SubmitQueueGatewayYARPCServer) []transport.Procedure {
	return buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{Server: server})
}

// FxSubmitQueueGatewayYARPCClientParams defines the input
// for NewFxSubmitQueueGatewayYARPCClient. It provides the
// paramaters to get a SubmitQueueGatewayYARPCClient in an
// Fx application.
type FxSubmitQueueGatewayYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSubmitQueueGatewayYARPCClientResult defines the output
// of NewFxSubmitQueueGatewayYARPCClient. It provides a
// SubmitQueueGatewayYARPCClient to an Fx application.
type FxSubmitQueueGatewayYARPCClientResult struct {
	fx.Out

	Client SubmitQueueGatewayYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSubmitQueueGatewayYARPCClient provides a SubmitQueueGatewayYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCClient("service-name"),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxSubmitQueueGatewayYARPCClientParams) FxSubmitQueueGatewayYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSubmitQueueGatewayYARPCClientResult{
			Client: newSubmitQueueGatewayYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSubmitQueueGatewayYARPCProceduresParams defines the input
// for NewFxSubmitQueueGatewayYARPCProcedures. It provides the
// paramaters to get SubmitQueueGatewayYARPCServer procedures in an
// Fx application.
type FxSubmitQueueGatewayYARPCProceduresParams struct {
	fx.In

	Server      SubmitQueueGatewayYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSubmitQueueGatewayYARPCProceduresResult defines the output
// of NewFxSubmitQueueGatewayYARPCProcedures. It provides
// SubmitQueueGatewayYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSubmitQueueGatewayYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSubmitQueueGatewayYARPCProcedures provides SubmitQueueGatewayYARPCServer procedures to an Fx application.
// It expects a SubmitQueueGatewayYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCProcedures(),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCProcedures() interface{} {
	return func(params FxSubmitQueueGatewayYARPCProceduresParams) FxSubmitQueueGatewayYARPCProceduresResult {
		return FxSubmitQueueGatewayYARPCProceduresResult{
			Procedures: buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: SubmitQueueGatewayReflectionMeta,
		}
	}
}

// SubmitQueueGatewayReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var SubmitQueueGatewayReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.devexp.submitqueue.gateway.SubmitQueueGateway",
	FileDescriptors: yarpcFileDescriptorClosuref1a937782ebbded5,
}

type _SubmitQueueGatewayYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_SubmitQueueGatewayYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newSubmitQueueGatewayServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, protobuf.CastError(emptySubmitQueueGatewayServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Land(ctx context.Context, request *LandRequest, options ...yarpc.CallOption) (*LandResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Land", request, newSubmitQueueGatewayServiceLandYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*LandResponse)
	if !ok {
		return nil, protobuf.CastError(emptySubmitQueueGatewayServiceLandYARPCResponse, responseMessage)
	}
	return response, err
}

type _SubmitQueueGatewayYARPCHandler struct {
	server SubmitQueueGatewayYARPCServer
}

func (h *_SubmitQueueGatewayYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, protobuf.CastError(emptySubmitQueueGatewayServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Land(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *LandRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*LandRequest)
		if !ok {
			return nil, protobuf.CastError(emptySubmitQueueGatewayServiceLandYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Land(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSubmitQueueGatewayServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newSubmitQueueGatewayServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

func newSubmitQueueGatewayServiceLandYARPCRequest() proto.Message {
	return &LandRequest{}
}

func newSubmitQueueGatewayServiceLandYARPCResponse() proto.Message {
	return &LandResponse{}
}

var (
	emptySubmitQueueGatewayServicePingYARPCRequest  = &PingRequest{}
	emptySubmitQueueGatewayServicePingYARPCResponse = &PingResponse{}
	emptySubmitQueueGatewayServiceLandYARPCRequest  = &LandRequest{}
	emptySubmitQueueGatewayServiceLandYARPCResponse = &LandResponse{}
)

var yarpcFileDescriptorClosuref1a937782ebbded5 = [][]byte{
	// gateway.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4b, 0x6f, 0xd3, 0x40,
		0x10, 0xc7, 0xeb, 0xbc, 0x48, 0x26, 0xa1, 0x44, 0x4b, 0x15, 0x59, 0x11, 0x12, 0xa9, 0x91, 0x68,
		0x78, 0x39, 0x92, 0xb9, 0x22, 0xa1, 0x04, 0x4c, 0x38, 0x14, 0x94, 0xae, 0x93, 0x03, 0x5c, 0x2a,
		0x3f, 0x46, 0x8e, 0x25, 0xfc, 0x88, 0x77, 0x5d, 0x28, 0x77, 0x3e, 0x0d, 0xdf, 0x8a, 0x4f, 0x82,
		0xbc, 0x5e, 0xbb, 0xbe, 0x80, 0x73, 0x9b, 0x99, 0x9d, 0xdf, 0xce, 0x7f, 0x66, 0xd6, 0x86, 0xfb,
		0xbe, 0xcd, 0xf1, 0xbb, 0x7d, 0xab, 0x27, 0x69, 0xcc, 0x63, 0xf2, 0x38, 0x73, 0x30, 0xd5, 0x3d,
		0xbc, 0xc1, 0x1f, 0x89, 0xce, 0x32, 0x27, 0x0c, 0xf8, 0x21, 0xc3, 0x0c, 0x75, 0x99, 0xa6, 0x5d,
		0xc0, 0x70, 0x13, 0x44, 0x3e, 0xc5, 0x43, 0x86, 0x8c, 0x13, 0x15, 0xee, 0x85, 0xc8, 0x98, 0xed,
		0xa3, 0xaa, 0xcc, 0x94, 0xf9, 0x80, 0x96, 0xae, 0xf6, 0x4b, 0x81, 0x51, 0x91, 0xc9, 0x92, 0x38,
		0x62, 0xf8, 0xef, 0x54, 0x72, 0x0e, 0x23, 0x86, 0xe9, 0x4d, 0xe0, 0xe2, 0x75, 0x64, 0x87, 0xa8,
		0xb6, 0xc4, 0xf1, 0x50, 0xc6, 0x3e, 0xdb, 0x21, 0x92, 0x47, 0x30, 0xe0, 0x41, 0x88, 0x8c, 0xdb,
		0x61, 0xa2, 0xb6, 0x67, 0xca, 0xbc, 0x4d, 0xef, 0x02, 0x64, 0x0a, 0xfd, 0x7d, 0xcc, 0xb8, 0x80,
		0x3b, 0x02, 0xae, 0x7c, 0xcd, 0x80, 0xde, 0xbb, 0xbd, 0x1d, 0xf9, 0x48, 0x26, 0xd0, 0x63, 0x71,
		0x96, 0xba, 0x65, 0x7d, 0xe9, 0x91, 0x31, 0xb4, 0x03, 0x8f, 0xa9, 0xad, 0x59, 0x7b, 0x3e, 0xa0,
		0xb9, 0xa9, 0xfd, 0x56, 0x60, 0x78, 0x69, 0x47, 0x5e, 0xd9, 0xe5, 0x19, 0x74, 0xc5, 0x14, 0x24,
		0x58, 0x38, 0xe4, 0x2d, 0xf4, 0x5c, 0x71, 0xb3, 0x10, 0x3c, 0x34, 0x2e, 0xf4, 0x86, 0xe1, 0xe9,
		0x85, 0x10, 0x2a, 0x31, 0x62, 0x42, 0x9f, 0xf1, 0xd4, 0xe6, 0xe8, 0xdf, 0x0a, 0xd9, 0xa7, 0xc6,
		0xb3, 0xc6, 0x2b, 0x2c, 0x09, 0xd0, 0x0a, 0xd5, 0x34, 0x18, 0x15, 0x62, 0xe5, 0xa0, 0x09, 0x74,
		0xd8, 0x21, 0xf0, 0xa4, 0x58, 0x61, 0x6b, 0xe7, 0xd0, 0x35, 0xd3, 0x34, 0x4e, 0xff, 0xb3, 0xb0,
		0x6f, 0x30, 0xd9, 0x45, 0x29, 0xba, 0xb1, 0x1f, 0x05, 0x3f, 0xd1, 0xbb, 0xca, 0xcb, 0x16, 0xcc,
		0x1b, 0xe8, 0x62, 0x6e, 0x08, 0x62, 0x68, 0x3c, 0x6d, 0x14, 0x29, 0x30, 0x5a, 0x40, 0x77, 0xc3,
		0x6b, 0xd5, 0x86, 0xf7, 0x1c, 0xa1, 0x5f, 0xb6, 0x42, 0xce, 0x60, 0x6c, 0x6d, 0xe9, 0x72, 0x6b,
		0xae, 0xbf, 0x5c, 0xbf, 0x37, 0x3f, 0x2c, 0x77, 0x97, 0xdb, 0xf1, 0x09, 0x79, 0x08, 0x0f, 0xaa,
		0x28, 0x35, 0x57, 0x4b, 0xcb, 0x1c, 0x2b, 0x64, 0x0a, 0x93, 0x2a, 0x68, 0x5d, 0xed, 0x96, 0xd6,
		0xc7, 0xf2, 0xac, 0x45, 0x08, 0x9c, 0x56, 0x67, 0x9f, 0x4c, 0xba, 0x36, 0xc7, 0x6d, 0xe3, 0x8f,
		0x02, 0xc4, 0x12, 0x0a, 0x45, 0x3f, 0xeb, 0x42, 0x20, 0x41, 0xe8, 0xe4, 0x6f, 0x93, 0xbc, 0x6c,
		0x6c, 0xa5, 0xf6, 0xd8, 0xa7, 0xaf, 0x8e, 0xcc, 0x2e, 0xf6, 0xa0, 0x9d, 0xe4, 0x65, 0xf2, 0xcd,
		0x1c, 0x51, 0xa6, 0xf6, 0xda, 0x8e, 0x28, 0x53, 0x5f, 0xb7, 0x76, 0xb2, 0x72, 0xe0, 0x89, 0x1b,
		0x87, 0x4d, 0xd4, 0x6a, 0x24, 0xbb, 0xdf, 0xe4, 0x5f, 0xfa, 0x46, 0xf9, 0xfa, 0xc2, 0x0f, 0xf8,
		0x3e, 0x73, 0x74, 0x37, 0x0e, 0x17, 0x39, 0xbb, 0xa8, 0x41, 0x0b, 0x09, 0x2d, 0xc4, 0x6f, 0x21,
		0x71, 0x9c, 0x9e, 0x30, 0x5e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x34, 0x94, 0xc4, 0x30,
		0x04, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SubmitQueueGatewayYARPCClient {
			return NewSubmitQueueGatewayYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
