// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gateway.proto

package protopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubmitQueueGateway_Ping_FullMethodName   = "/uber.devexp.submitqueue.gateway.SubmitQueueGateway/Ping"
	SubmitQueueGateway_Land_FullMethodName   = "/uber.devexp.submitqueue.gateway.SubmitQueueGateway/Land"
	SubmitQueueGateway_Cancel_FullMethodName = "/uber.devexp.submitqueue.gateway.SubmitQueueGateway/Cancel"
)

// SubmitQueueGatewayClient is the client API for SubmitQueueGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubmitQueueGateway provides the gateway API
type SubmitQueueGatewayClient interface {
	// Ping returns a response indicating the service is alive
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Land lands a set of code changes into a target branch, performing the necessary validations across all other changes in the queue.
	// The processing is asynchronous and returns a LandResponse immediately. The land request is processed in the background.
	Land(ctx context.Context, in *LandRequest, opts ...grpc.CallOption) (*LandResponse, error)
	// Cancel cancels a previously submitted land request. The cancellation is asynchronous and
	// published to a queue for processing. No validation is performed on whether the request exists.
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
}

type submitQueueGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmitQueueGatewayClient(cc grpc.ClientConnInterface) SubmitQueueGatewayClient {
	return &submitQueueGatewayClient{cc}
}

func (c *submitQueueGatewayClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SubmitQueueGateway_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submitQueueGatewayClient) Land(ctx context.Context, in *LandRequest, opts ...grpc.CallOption) (*LandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LandResponse)
	err := c.cc.Invoke(ctx, SubmitQueueGateway_Land_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submitQueueGatewayClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, SubmitQueueGateway_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmitQueueGatewayServer is the server API for SubmitQueueGateway service.
// All implementations must embed UnimplementedSubmitQueueGatewayServer
// for forward compatibility.
//
// SubmitQueueGateway provides the gateway API
type SubmitQueueGatewayServer interface {
	// Ping returns a response indicating the service is alive
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Land lands a set of code changes into a target branch, performing the necessary validations across all other changes in the queue.
	// The processing is asynchronous and returns a LandResponse immediately. The land request is processed in the background.
	Land(context.Context, *LandRequest) (*LandResponse, error)
	// Cancel cancels a previously submitted land request. The cancellation is asynchronous and
	// published to a queue for processing. No validation is performed on whether the request exists.
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	mustEmbedUnimplementedSubmitQueueGatewayServer()
}

// UnimplementedSubmitQueueGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubmitQueueGatewayServer struct{}

func (UnimplementedSubmitQueueGatewayServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSubmitQueueGatewayServer) Land(context.Context, *LandRequest) (*LandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Land not implemented")
}
func (UnimplementedSubmitQueueGatewayServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedSubmitQueueGatewayServer) mustEmbedUnimplementedSubmitQueueGatewayServer() {}
func (UnimplementedSubmitQueueGatewayServer) testEmbeddedByValue()                            {}

// UnsafeSubmitQueueGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmitQueueGatewayServer will
// result in compilation errors.
type UnsafeSubmitQueueGatewayServer interface {
	mustEmbedUnimplementedSubmitQueueGatewayServer()
}

func RegisterSubmitQueueGatewayServer(s grpc.ServiceRegistrar, srv SubmitQueueGatewayServer) {
	// If the following call panics, it indicates UnimplementedSubmitQueueGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubmitQueueGateway_ServiceDesc, srv)
}

func _SubmitQueueGateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmitQueueGatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmitQueueGateway_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmitQueueGatewayServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmitQueueGateway_Land_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmitQueueGatewayServer).Land(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmitQueueGateway_Land_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmitQueueGatewayServer).Land(ctx, req.(*LandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmitQueueGateway_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmitQueueGatewayServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmitQueueGateway_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmitQueueGatewayServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubmitQueueGateway_ServiceDesc is the grpc.ServiceDesc for SubmitQueueGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubmitQueueGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uber.devexp.submitqueue.gateway.SubmitQueueGateway",
	HandlerType: (*SubmitQueueGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SubmitQueueGateway_Ping_Handler,
		},
		{
			MethodName: "Land",
			Handler:    _SubmitQueueGateway_Land_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _SubmitQueueGateway_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
