// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gateway.proto

package protopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Strategy defines the possible source control integration methods
type Strategy int32

const (
	// Default strategy (let server decide based on configuration)
	Strategy_DEFAULT Strategy = 0
	// Rebase commits onto target branch before landing
	Strategy_REBASE Strategy = 1
	// Same as REBASE but squash commits into a single commit before rebase
	Strategy_SQUASH_REBASE Strategy = 2
	// Merge commits into the target branch by creating a separate merge commit, preserving the commit history along with hashes
	Strategy_MERGE Strategy = 3
)

// Enum value maps for Strategy.
var (
	Strategy_name = map[int32]string{
		0: "DEFAULT",
		1: "REBASE",
		2: "SQUASH_REBASE",
		3: "MERGE",
	}
	Strategy_value = map[string]int32{
		"DEFAULT":       0,
		"REBASE":        1,
		"SQUASH_REBASE": 2,
		"MERGE":         3,
	}
)

func (x Strategy) Enum() *Strategy {
	p := new(Strategy)
	*p = x
	return p
}

func (x Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[0].Descriptor()
}

func (Strategy) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[0]
}

func (x Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Strategy.Descriptor instead.
func (Strategy) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

// RequestStatus defines the possible states of a land request.
type RequestStatus int32

const (
	// Unknown status. Should never be seen in the system.
	RequestStatus_UNKNOWN RequestStatus = 0
	// Initial state of a land request. Confirmed by the system but processing has not started.
	RequestStatus_NEW RequestStatus = 1
	// The request has been validated (duplicate check, merge check etc.) successfully.
	RequestStatus_VALIDATED RequestStatus = 2
	// The request is being processed.
	RequestStatus_PROCESSING RequestStatus = 3
	// The request has been successfully processed and landed. Terminal state.
	RequestStatus_LANDED RequestStatus = 4
	// The cancellation request has been accepted and is being processed.
	RequestStatus_CANCELLATION_ACCEPTED RequestStatus = 5
	// The request has been cancelled. Terminal state.
	RequestStatus_CANCELLED RequestStatus = 6
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "NEW",
		2: "VALIDATED",
		3: "PROCESSING",
		4: "LANDED",
		5: "CANCELLATION_ACCEPTED",
		6: "CANCELLED",
	}
	RequestStatus_value = map[string]int32{
		"UNKNOWN":               0,
		"NEW":                   1,
		"VALIDATED":             2,
		"PROCESSING":            3,
		"LANDED":                4,
		"CANCELLATION_ACCEPTED": 5,
		"CANCELLED":             6,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[1].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[1]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

// PingRequest is the request for the Ping method
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional message to include in the ping
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PingResponse is the response for the Ping method
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The response message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The service name that handled the request
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Timestamp of when the ping was received
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Hostname of the server that handled the request
	Hostname      string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// Change represents a code change identified by URIs from a code change provider (e.g., GitHub Pull Request, Phabricator Diff).
// The provider is extracted from the URI scheme.
type Change struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URIs identifying the change(s) to land (RFC 3986 compliant).
	// The scheme identifies the change provider, and the path contains provider-specific resource identifiers.
	//
	// GitHub is supported by default (though other providers can be added):
	//
	//	Template: "github://<org>/<repo>/pull/<pr>/<hash>"
	//	Example: "github://uber/submitqueue/pull/123/abc123def"
	//
	// SubmitQueue guarantees changes are landed in order with no other changes in between.
	// SubmitQueue does not guarantee each change is individually valid, but produces a validity marker on such changes.
	// The user is responsible for including all changes in a stack in order, starting from the earliest change.
	Uris          []string `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Change) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

// LandRequest defines a request to land (merge into target branch of the source control repository) a set of code changes.
type LandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the queue processing the land request. The queue should be defined in the configuration, otherwise an error is returned.
	Queue string `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// Change (such as a pull request) to land into the target branch. Target branch is defined by the queue configuration.
	Change *Change `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	// Source control integration strategy to use for this land operation. If not specified, the default queue strategy is used.
	Strategy      Strategy `protobuf:"varint,4,opt,name=strategy,proto3,enum=uber.devexp.submitqueue.gateway.Strategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandRequest) Reset() {
	*x = LandRequest{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandRequest) ProtoMessage() {}

func (x *LandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandRequest.ProtoReflect.Descriptor instead.
func (*LandRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *LandRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *LandRequest) GetChange() *Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *LandRequest) GetStrategy() Strategy {
	if x != nil {
		return x.Strategy
	}
	return Strategy_DEFAULT
}

// LandResponse defines the response to a land request.
type LandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique identifier for the land request. Used to track the land request lifecycle.
	Sqid          string `protobuf:"bytes,1,opt,name=sqid,proto3" json:"sqid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandResponse) Reset() {
	*x = LandResponse{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandResponse) ProtoMessage() {}

func (x *LandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandResponse.ProtoReflect.Descriptor instead.
func (*LandResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *LandResponse) GetSqid() string {
	if x != nil {
		return x.Sqid
	}
	return ""
}

// CancelRequest defines a request to cancel a previously submitted land request.
type CancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique identifier for the land request to cancel, as returned by Land.
	Sqid          string `protobuf:"bytes,1,opt,name=sqid,proto3" json:"sqid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRequest) GetSqid() string {
	if x != nil {
		return x.Sqid
	}
	return ""
}

// CancelResponse defines the response to a cancel request.
type CancelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique identifier for the land request that was cancelled.
	Sqid string `protobuf:"bytes,1,opt,name=sqid,proto3" json:"sqid,omitempty"`
	// Current status of the land request at the time of cancellation.
	CurrentStatus RequestStatus `protobuf:"varint,2,opt,name=current_status,json=currentStatus,proto3,enum=uber.devexp.submitqueue.gateway.RequestStatus" json:"current_status,omitempty"`
	// Optional error describing why the cancellation could not be completed.
	Error         *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *CancelResponse) GetSqid() string {
	if x != nil {
		return x.Sqid
	}
	return ""
}

func (x *CancelResponse) GetCurrentStatus() RequestStatus {
	if x != nil {
		return x.CurrentStatus
	}
	return RequestStatus_UNKNOWN
}

func (x *CancelResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Generic error with metadata. Each custom error type should extend this message.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Free text error message describing the error.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UnrecognizedQueueError is returned when a queue name is not recognized. Typically this indicates a typo in the queue name or server misconfiguration.
type UnrecognizedQueueError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Free text error message describing the error.
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Name of the queue that was not recognized.
	Queue         string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnrecognizedQueueError) Reset() {
	*x = UnrecognizedQueueError{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnrecognizedQueueError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnrecognizedQueueError) ProtoMessage() {}

func (x *UnrecognizedQueueError) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnrecognizedQueueError.ProtoReflect.Descriptor instead.
func (*UnrecognizedQueueError) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *UnrecognizedQueueError) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UnrecognizedQueueError) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x1fuber.devexp.submitqueue.gateway\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x85\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\x1c\n" +
	"\x06Change\x12\x12\n" +
	"\x04uris\x18\x01 \x03(\tR\x04uris\"\xab\x01\n" +
	"\vLandRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12?\n" +
	"\x06change\x18\x02 \x01(\v2'.uber.devexp.submitqueue.gateway.ChangeR\x06change\x12E\n" +
	"\bstrategy\x18\x04 \x01(\x0e2).uber.devexp.submitqueue.gateway.StrategyR\bstrategy\"\"\n" +
	"\fLandResponse\x12\x12\n" +
	"\x04sqid\x18\x01 \x01(\tR\x04sqid\"#\n" +
	"\rCancelRequest\x12\x12\n" +
	"\x04sqid\x18\x01 \x01(\tR\x04sqid\"\xb9\x01\n" +
	"\x0eCancelResponse\x12\x12\n" +
	"\x04sqid\x18\x01 \x01(\tR\x04sqid\x12U\n" +
	"\x0ecurrent_status\x18\x02 \x01(\x0e2..uber.devexp.submitqueue.gateway.RequestStatusR\rcurrentStatus\x12<\n" +
	"\x05error\x18\x03 \x01(\v2&.uber.devexp.submitqueue.gateway.ErrorR\x05error\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"l\n" +
	"\x16UnrecognizedQueueError\x12<\n" +
	"\x05error\x18\x01 \x01(\v2&.uber.devexp.submitqueue.gateway.ErrorR\x05error\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue*A\n" +
	"\bStrategy\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\n" +
	"\n" +
	"\x06REBASE\x10\x01\x12\x11\n" +
	"\rSQUASH_REBASE\x10\x02\x12\t\n" +
	"\x05MERGE\x10\x03*z\n" +
	"\rRequestStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\r\n" +
	"\tVALIDATED\x10\x02\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x03\x12\n" +
	"\n" +
	"\x06LANDED\x10\x04\x12\x19\n" +
	"\x15CANCELLATION_ACCEPTED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x062\xcf\x02\n" +
	"\x12SubmitQueueGateway\x12e\n" +
	"\x04Ping\x12,.uber.devexp.submitqueue.gateway.PingRequest\x1a-.uber.devexp.submitqueue.gateway.PingResponse\"\x00\x12e\n" +
	"\x04Land\x12,.uber.devexp.submitqueue.gateway.LandRequest\x1a-.uber.devexp.submitqueue.gateway.LandResponse\"\x00\x12k\n" +
	"\x06Cancel\x12..uber.devexp.submitqueue.gateway.CancelRequest\x1a/.uber.devexp.submitqueue.gateway.CancelResponse\"\x00Bb\n" +
	"#com.uber.devexp.submitqueue.gatewayB\fGatewayProtoP\x01Z+github.com/uber/submitqueue/gateway/protopbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gateway_proto_goTypes = []any{
	(Strategy)(0),                  // 0: uber.devexp.submitqueue.gateway.Strategy
	(RequestStatus)(0),             // 1: uber.devexp.submitqueue.gateway.RequestStatus
	(*PingRequest)(nil),            // 2: uber.devexp.submitqueue.gateway.PingRequest
	(*PingResponse)(nil),           // 3: uber.devexp.submitqueue.gateway.PingResponse
	(*Change)(nil),                 // 4: uber.devexp.submitqueue.gateway.Change
	(*LandRequest)(nil),            // 5: uber.devexp.submitqueue.gateway.LandRequest
	(*LandResponse)(nil),           // 6: uber.devexp.submitqueue.gateway.LandResponse
	(*CancelRequest)(nil),          // 7: uber.devexp.submitqueue.gateway.CancelRequest
	(*CancelResponse)(nil),         // 8: uber.devexp.submitqueue.gateway.CancelResponse
	(*Error)(nil),                  // 9: uber.devexp.submitqueue.gateway.Error
	(*UnrecognizedQueueError)(nil), // 10: uber.devexp.submitqueue.gateway.UnrecognizedQueueError
}
var file_gateway_proto_depIdxs = []int32{
	4, // 0: uber.devexp.submitqueue.gateway.LandRequest.change:type_name -> uber.devexp.submitqueue.gateway.Change
	0, // 1: uber.devexp.submitqueue.gateway.LandRequest.strategy:type_name -> uber.devexp.submitqueue.gateway.Strategy
	1, // 2: uber.devexp.submitqueue.gateway.CancelResponse.current_status:type_name -> uber.devexp.submitqueue.gateway.RequestStatus
	9, // 3: uber.devexp.submitqueue.gateway.CancelResponse.error:type_name -> uber.devexp.submitqueue.gateway.Error
	9, // 4: uber.devexp.submitqueue.gateway.UnrecognizedQueueError.error:type_name -> uber.devexp.submitqueue.gateway.Error
	2, // 5: uber.devexp.submitqueue.gateway.SubmitQueueGateway.Ping:input_type -> uber.devexp.submitqueue.gateway.PingRequest
	5, // 6: uber.devexp.submitqueue.gateway.SubmitQueueGateway.Land:input_type -> uber.devexp.submitqueue.gateway.LandRequest
	7, // 7: uber.devexp.submitqueue.gateway.SubmitQueueGateway.Cancel:input_type -> uber.devexp.submitqueue.gateway.CancelRequest
	3, // 8: uber.devexp.submitqueue.gateway.SubmitQueueGateway.Ping:output_type -> uber.devexp.submitqueue.gateway.PingResponse
	6, // 9: uber.devexp.submitqueue.gateway.SubmitQueueGateway.Land:output_type -> uber.devexp.submitqueue.gateway.LandResponse
	8, // 10: uber.devexp.submitqueue.gateway.SubmitQueueGateway.Cancel:output_type -> uber.devexp.submitqueue.gateway.CancelResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
