// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: gateway.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// SubmitQueueGatewayYARPCClient is the YARPC client-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
	Land(context.Context, *LandRequest, ...yarpc.CallOption) (*LandResponse, error)
	Cancel(context.Context, *CancelRequest, ...yarpc.CallOption) (*CancelResponse, error)
}

func newSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) SubmitQueueGatewayYARPCClient {
	return &_SubmitQueueGatewayYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.devexp.submitqueue.gateway.SubmitQueueGateway",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSubmitQueueGatewayYARPCClient builds a new YARPC client for the SubmitQueueGateway service.
func NewSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) SubmitQueueGatewayYARPCClient {
	return newSubmitQueueGatewayYARPCClient(clientConfig, nil, options...)
}

// SubmitQueueGatewayYARPCServer is the YARPC server-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Land(context.Context, *LandRequest) (*LandResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
}

type buildSubmitQueueGatewayYARPCProceduresParams struct {
	Server      SubmitQueueGatewayYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildSubmitQueueGatewayYARPCProcedures(params buildSubmitQueueGatewayYARPCProceduresParams) []transport.Procedure {
	handler := &_SubmitQueueGatewayYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.devexp.submitqueue.gateway.SubmitQueueGateway",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newSubmitQueueGatewayServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Land",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Land,
							NewRequest:  newSubmitQueueGatewayServiceLandYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Cancel",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Cancel,
							NewRequest:  newSubmitQueueGatewayServiceCancelYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSubmitQueueGatewayYARPCProcedures prepares an implementation of the SubmitQueueGateway service for YARPC registration.
func BuildSubmitQueueGatewayYARPCProcedures(server SubmitQueueGatewayYARPCServer) []transport.Procedure {
	return buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{Server: server})
}

// FxSubmitQueueGatewayYARPCClientParams defines the input
// for NewFxSubmitQueueGatewayYARPCClient. It provides the
// paramaters to get a SubmitQueueGatewayYARPCClient in an
// Fx application.
type FxSubmitQueueGatewayYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSubmitQueueGatewayYARPCClientResult defines the output
// of NewFxSubmitQueueGatewayYARPCClient. It provides a
// SubmitQueueGatewayYARPCClient to an Fx application.
type FxSubmitQueueGatewayYARPCClientResult struct {
	fx.Out

	Client SubmitQueueGatewayYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSubmitQueueGatewayYARPCClient provides a SubmitQueueGatewayYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCClient("service-name"),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxSubmitQueueGatewayYARPCClientParams) FxSubmitQueueGatewayYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSubmitQueueGatewayYARPCClientResult{
			Client: newSubmitQueueGatewayYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSubmitQueueGatewayYARPCProceduresParams defines the input
// for NewFxSubmitQueueGatewayYARPCProcedures. It provides the
// paramaters to get SubmitQueueGatewayYARPCServer procedures in an
// Fx application.
type FxSubmitQueueGatewayYARPCProceduresParams struct {
	fx.In

	Server      SubmitQueueGatewayYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSubmitQueueGatewayYARPCProceduresResult defines the output
// of NewFxSubmitQueueGatewayYARPCProcedures. It provides
// SubmitQueueGatewayYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSubmitQueueGatewayYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSubmitQueueGatewayYARPCProcedures provides SubmitQueueGatewayYARPCServer procedures to an Fx application.
// It expects a SubmitQueueGatewayYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCProcedures(),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCProcedures() interface{} {
	return func(params FxSubmitQueueGatewayYARPCProceduresParams) FxSubmitQueueGatewayYARPCProceduresResult {
		return FxSubmitQueueGatewayYARPCProceduresResult{
			Procedures: buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: SubmitQueueGatewayReflectionMeta,
		}
	}
}

// SubmitQueueGatewayReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var SubmitQueueGatewayReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.devexp.submitqueue.gateway.SubmitQueueGateway",
	FileDescriptors: yarpcFileDescriptorClosuref1a937782ebbded5,
}

type _SubmitQueueGatewayYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_SubmitQueueGatewayYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newSubmitQueueGatewayServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, protobuf.CastError(emptySubmitQueueGatewayServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Land(ctx context.Context, request *LandRequest, options ...yarpc.CallOption) (*LandResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Land", request, newSubmitQueueGatewayServiceLandYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*LandResponse)
	if !ok {
		return nil, protobuf.CastError(emptySubmitQueueGatewayServiceLandYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Cancel(ctx context.Context, request *CancelRequest, options ...yarpc.CallOption) (*CancelResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Cancel", request, newSubmitQueueGatewayServiceCancelYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*CancelResponse)
	if !ok {
		return nil, protobuf.CastError(emptySubmitQueueGatewayServiceCancelYARPCResponse, responseMessage)
	}
	return response, err
}

type _SubmitQueueGatewayYARPCHandler struct {
	server SubmitQueueGatewayYARPCServer
}

func (h *_SubmitQueueGatewayYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, protobuf.CastError(emptySubmitQueueGatewayServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Land(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *LandRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*LandRequest)
		if !ok {
			return nil, protobuf.CastError(emptySubmitQueueGatewayServiceLandYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Land(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Cancel(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *CancelRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*CancelRequest)
		if !ok {
			return nil, protobuf.CastError(emptySubmitQueueGatewayServiceCancelYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Cancel(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSubmitQueueGatewayServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newSubmitQueueGatewayServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

func newSubmitQueueGatewayServiceLandYARPCRequest() proto.Message {
	return &LandRequest{}
}

func newSubmitQueueGatewayServiceLandYARPCResponse() proto.Message {
	return &LandResponse{}
}

func newSubmitQueueGatewayServiceCancelYARPCRequest() proto.Message {
	return &CancelRequest{}
}

func newSubmitQueueGatewayServiceCancelYARPCResponse() proto.Message {
	return &CancelResponse{}
}

var (
	emptySubmitQueueGatewayServicePingYARPCRequest    = &PingRequest{}
	emptySubmitQueueGatewayServicePingYARPCResponse   = &PingResponse{}
	emptySubmitQueueGatewayServiceLandYARPCRequest    = &LandRequest{}
	emptySubmitQueueGatewayServiceLandYARPCResponse   = &LandResponse{}
	emptySubmitQueueGatewayServiceCancelYARPCRequest  = &CancelRequest{}
	emptySubmitQueueGatewayServiceCancelYARPCResponse = &CancelResponse{}
)

var yarpcFileDescriptorClosuref1a937782ebbded5 = [][]byte{
	// gateway.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcb, 0x6e, 0xd3, 0x4c,
		0x14, 0xc7, 0xe3, 0x5c, 0xdc, 0xe4, 0x38, 0xa9, 0xf2, 0x8d, 0x3e, 0x21, 0x2b, 0xaa, 0x44, 0xea,
		0x22, 0x1a, 0x6e, 0xb6, 0x14, 0xb6, 0x48, 0x28, 0x29, 0xa6, 0x2c, 0x0a, 0x4a, 0x6d, 0xb2, 0x61,
		0x53, 0x8d, 0x9d, 0x23, 0xc7, 0xa2, 0xbe, 0xc4, 0x33, 0x2e, 0x94, 0x3d, 0x4f, 0xc3, 0xc3, 0xf0,
		0x4a, 0xc8, 0xe3, 0x71, 0xeb, 0x05, 0xd4, 0xd9, 0x9d, 0x19, 0x9f, 0xdf, 0xfc, 0xff, 0xe7, 0x22,
		0xc3, 0x28, 0xa0, 0x1c, 0xbf, 0xd1, 0x5b, 0x33, 0xcd, 0x12, 0x9e, 0x90, 0xc7, 0xb9, 0x87, 0x99,
		0xb9, 0xc1, 0x1b, 0xfc, 0x9e, 0x9a, 0x2c, 0xf7, 0xa2, 0x90, 0xef, 0x72, 0xcc, 0xd1, 0x94, 0x69,
		0xc6, 0x29, 0x68, 0xab, 0x30, 0x0e, 0x1c, 0xdc, 0xe5, 0xc8, 0x38, 0xd1, 0xe1, 0x20, 0x42, 0xc6,
		0x68, 0x80, 0xba, 0x32, 0x55, 0x66, 0x03, 0xa7, 0x3a, 0x1a, 0x3f, 0x15, 0x18, 0x96, 0x99, 0x2c,
		0x4d, 0x62, 0x86, 0xff, 0x4e, 0x25, 0xc7, 0x30, 0x64, 0x98, 0xdd, 0x84, 0x3e, 0x5e, 0xc5, 0x34,
		0x42, 0xbd, 0x2d, 0x3e, 0x6b, 0xf2, 0xee, 0x13, 0x8d, 0x90, 0x1c, 0xc1, 0x80, 0x87, 0x11, 0x32,
		0x4e, 0xa3, 0x54, 0xef, 0x4c, 0x95, 0x59, 0xc7, 0xb9, 0xbf, 0x20, 0x13, 0xe8, 0x6f, 0x13, 0xc6,
		0x05, 0xdc, 0x15, 0xf0, 0xdd, 0xd9, 0x38, 0x02, 0xf5, 0x6c, 0x4b, 0xe3, 0x00, 0x09, 0x81, 0x6e,
		0x9e, 0x85, 0x4c, 0x57, 0xa6, 0x9d, 0xd9, 0xc0, 0x11, 0xb1, 0xf1, 0x4b, 0x01, 0xed, 0x82, 0xc6,
		0x9b, 0xaa, 0x9e, 0xff, 0xa1, 0x27, 0xea, 0x95, 0x16, 0xcb, 0x03, 0x79, 0x0b, 0xaa, 0x2f, 0xde,
		0x10, 0xd6, 0xb4, 0xf9, 0xa9, 0xd9, 0xd0, 0x26, 0xb3, 0x94, 0x74, 0x24, 0x46, 0x6c, 0xe8, 0x33,
		0x9e, 0x51, 0x8e, 0xc1, 0xad, 0x30, 0x78, 0x38, 0x7f, 0xd6, 0xf8, 0x84, 0x2b, 0x01, 0xe7, 0x0e,
		0x35, 0x0c, 0x18, 0x96, 0x66, 0x65, 0x4b, 0x09, 0x74, 0xd9, 0x2e, 0xdc, 0x48, 0xb3, 0x22, 0x36,
		0x4e, 0x60, 0x74, 0x46, 0x63, 0x1f, 0xaf, 0xab, 0x92, 0xfe, 0x96, 0xf4, 0x04, 0x0e, 0xab, 0xa4,
		0x07, 0x9e, 0x3a, 0x86, 0x9e, 0x9d, 0x65, 0x49, 0xf6, 0xc0, 0x94, 0xaf, 0xe1, 0xd1, 0x3a, 0xce,
		0xd0, 0x4f, 0x82, 0x38, 0xfc, 0x81, 0x9b, 0xcb, 0xa2, 0x82, 0x92, 0x79, 0x03, 0x3d, 0x2c, 0x02,
		0x41, 0x68, 0xf3, 0xa7, 0x8d, 0xf5, 0x0a, 0xcc, 0x29, 0xa1, 0xfb, 0x39, 0xb4, 0x6b, 0x73, 0x78,
		0xbe, 0x80, 0x7e, 0xd5, 0x15, 0xa2, 0xc1, 0xc1, 0x3b, 0xfb, 0xfd, 0x62, 0x7d, 0xf1, 0x79, 0xdc,
		0x22, 0x00, 0xaa, 0x63, 0x2f, 0x17, 0xae, 0x3d, 0x56, 0xc8, 0x7f, 0x30, 0x72, 0x2f, 0xd7, 0x0b,
		0xf7, 0xc3, 0x95, 0xbc, 0x6a, 0x93, 0x01, 0xf4, 0x3e, 0xda, 0xce, 0xb9, 0x3d, 0xee, 0xcc, 0x7f,
		0xb7, 0x81, 0xb8, 0x42, 0x5d, 0x78, 0x3d, 0x2f, 0xc5, 0x09, 0x42, 0xb7, 0x58, 0x56, 0xf2, 0xb2,
		0xd1, 0x66, 0x6d, 0xfb, 0x27, 0xaf, 0xf6, 0xcc, 0x2e, 0x7b, 0x6c, 0xb4, 0x0a, 0x99, 0x62, 0x80,
		0x7b, 0xc8, 0xd4, 0x96, 0x72, 0x0f, 0x99, 0xfa, 0x56, 0x18, 0x2d, 0xf2, 0x15, 0xd4, 0x72, 0xbc,
		0xc4, 0x6c, 0xde, 0xd4, 0xfa, 0xb2, 0x4c, 0xac, 0xbd, 0xf3, 0x2b, 0xb1, 0xa5, 0x07, 0x27, 0x7e,
		0x12, 0x35, 0x71, 0xcb, 0xa1, 0x6c, 0xf5, 0xaa, 0xf8, 0xcf, 0xac, 0x94, 0x2f, 0x2f, 0x82, 0x90,
		0x6f, 0x73, 0xcf, 0xf4, 0x93, 0xc8, 0x2a, 0x58, 0xab, 0x06, 0x59, 0x12, 0xb2, 0xc4, 0x4f, 0x29,
		0xf5, 0x3c, 0x55, 0x04, 0xaf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xdb, 0xc5, 0xbd, 0xae,
		0x04, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SubmitQueueGatewayYARPCClient {
			return NewSubmitQueueGatewayYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
