load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "gateway_lib",
    srcs = [
        "list_queues.go",
        "main.go",
    ],
    importpath = "github.com/uber/submitqueue/service/submitqueue/gateway/client",
    visibility = ["//visibility:private"],
    deps = [
        "//platform/base/change/github:go_default_library",
        "//submitqueue/client:go_default_library",
    ],
)

go_binary(
    name = "gateway",
    embed = [":gateway_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["list_queues_test.go"],
    embed = [":gateway_lib"],  # keep
    deps = [
        "//api/submitqueue/gateway/protopb:go_default_library",
        "//submitqueue/client:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
    ],
)
