load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gateway_lib",
    srcs = ["main.go"],
    importpath = "github.com/uber/submitqueue/service/submitqueue/gateway/client",
    visibility = ["//visibility:private"],
    deps = [
        "//platform/base/change/github:go_default_library",
        "//submitqueue/client:go_default_library",
    ],
)

go_binary(
    name = "gateway",
    embed = [":gateway_lib"],
    visibility = ["//visibility:public"],
)
