// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: stovepipe.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
	v2 "go.uber.org/yarpc/encoding/protobuf/v2"
	"google.golang.org/protobuf/proto"
)

var _ = ioutil.NopCloser

// StovepipeYARPCClient is the YARPC client-side interface for the Stovepipe service.
type StovepipeYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
	Ingest(context.Context, *IngestRequest, ...yarpc.CallOption) (*IngestResponse, error)
	GetProjectStatusByURI(context.Context, *GetProjectStatusByURIRequest, ...yarpc.CallOption) (*GetProjectStatusByURIResponse, error)
}

func newStovepipeYARPCClient(clientConfig transport.ClientConfig, anyResolver v2.AnyResolver, options ...v2.ClientOption) StovepipeYARPCClient {
	return &_StovepipeYARPCCaller{v2.NewStreamClient(
		v2.ClientParams{
			ServiceName:  "uber.submitqueue.stovepipe.Stovepipe",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewStovepipeYARPCClient builds a new YARPC client for the Stovepipe service.
func NewStovepipeYARPCClient(clientConfig transport.ClientConfig, options ...v2.ClientOption) StovepipeYARPCClient {
	return newStovepipeYARPCClient(clientConfig, nil, options...)
}

// StovepipeYARPCServer is the YARPC server-side interface for the Stovepipe service.
type StovepipeYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	GetProjectStatusByURI(context.Context, *GetProjectStatusByURIRequest) (*GetProjectStatusByURIResponse, error)
}

type buildStovepipeYARPCProceduresParams struct {
	Server      StovepipeYARPCServer
	AnyResolver v2.AnyResolver
}

func buildStovepipeYARPCProcedures(params buildStovepipeYARPCProceduresParams) []transport.Procedure {
	handler := &_StovepipeYARPCHandler{params.Server}
	return v2.BuildProcedures(
		v2.BuildProceduresParams{
			ServiceName: "uber.submitqueue.stovepipe.Stovepipe",
			UnaryHandlerParams: []v2.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newStovepipeServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Ingest",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ingest,
							NewRequest:  newStovepipeServiceIngestYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetProjectStatusByURI",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetProjectStatusByURI,
							NewRequest:  newStovepipeServiceGetProjectStatusByURIYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []v2.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []v2.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildStovepipeYARPCProcedures prepares an implementation of the Stovepipe service for YARPC registration.
func BuildStovepipeYARPCProcedures(server StovepipeYARPCServer) []transport.Procedure {
	return buildStovepipeYARPCProcedures(buildStovepipeYARPCProceduresParams{Server: server})
}

// FxStovepipeYARPCClientParams defines the input
// for NewFxStovepipeYARPCClient. It provides the
// paramaters to get a StovepipeYARPCClient in an
// Fx application.
type FxStovepipeYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver v2.AnyResolver      `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxStovepipeYARPCClientResult defines the output
// of NewFxStovepipeYARPCClient. It provides a
// StovepipeYARPCClient to an Fx application.
type FxStovepipeYARPCClientResult struct {
	fx.Out

	Client StovepipeYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxStovepipeYARPCClient provides a StovepipeYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxStovepipeYARPCClient("service-name"),
//	  ...
//	)
func NewFxStovepipeYARPCClient(name string, options ...v2.ClientOption) interface{} {
	return func(params FxStovepipeYARPCClientParams) FxStovepipeYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(v2.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxStovepipeYARPCClientResult{
			Client: newStovepipeYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxStovepipeYARPCProceduresParams defines the input
// for NewFxStovepipeYARPCProcedures. It provides the
// paramaters to get StovepipeYARPCServer procedures in an
// Fx application.
type FxStovepipeYARPCProceduresParams struct {
	fx.In

	Server      StovepipeYARPCServer
	AnyResolver v2.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxStovepipeYARPCProceduresResult defines the output
// of NewFxStovepipeYARPCProcedures. It provides
// StovepipeYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxStovepipeYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxStovepipeYARPCProcedures provides StovepipeYARPCServer procedures to an Fx application.
// It expects a StovepipeYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxStovepipeYARPCProcedures(),
//	  ...
//	)
func NewFxStovepipeYARPCProcedures() interface{} {
	return func(params FxStovepipeYARPCProceduresParams) FxStovepipeYARPCProceduresResult {
		return FxStovepipeYARPCProceduresResult{
			Procedures: buildStovepipeYARPCProcedures(buildStovepipeYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: reflection.ServerMeta{
				ServiceName:     "uber.submitqueue.stovepipe.Stovepipe",
				FileDescriptors: yarpcFileDescriptorClosurefabdb6b3c0b09022,
			},
		}
	}
}

type _StovepipeYARPCCaller struct {
	streamClient v2.StreamClient
}

func (c *_StovepipeYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newStovepipeServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_StovepipeYARPCCaller) Ingest(ctx context.Context, request *IngestRequest, options ...yarpc.CallOption) (*IngestResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ingest", request, newStovepipeServiceIngestYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*IngestResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServiceIngestYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_StovepipeYARPCCaller) GetProjectStatusByURI(ctx context.Context, request *GetProjectStatusByURIRequest, options ...yarpc.CallOption) (*GetProjectStatusByURIResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetProjectStatusByURI", request, newStovepipeServiceGetProjectStatusByURIYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetProjectStatusByURIResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServiceGetProjectStatusByURIYARPCResponse, responseMessage)
	}
	return response, err
}

type _StovepipeYARPCHandler struct {
	server StovepipeYARPCServer
}

func (h *_StovepipeYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_StovepipeYARPCHandler) Ingest(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *IngestRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*IngestRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServiceIngestYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ingest(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_StovepipeYARPCHandler) GetProjectStatusByURI(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetProjectStatusByURIRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetProjectStatusByURIRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServiceGetProjectStatusByURIYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetProjectStatusByURI(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newStovepipeServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newStovepipeServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

func newStovepipeServiceIngestYARPCRequest() proto.Message {
	return &IngestRequest{}
}

func newStovepipeServiceIngestYARPCResponse() proto.Message {
	return &IngestResponse{}
}

func newStovepipeServiceGetProjectStatusByURIYARPCRequest() proto.Message {
	return &GetProjectStatusByURIRequest{}
}

func newStovepipeServiceGetProjectStatusByURIYARPCResponse() proto.Message {
	return &GetProjectStatusByURIResponse{}
}

var (
	emptyStovepipeServicePingYARPCRequest                   = &PingRequest{}
	emptyStovepipeServicePingYARPCResponse                  = &PingResponse{}
	emptyStovepipeServiceIngestYARPCRequest                 = &IngestRequest{}
	emptyStovepipeServiceIngestYARPCResponse                = &IngestResponse{}
	emptyStovepipeServiceGetProjectStatusByURIYARPCRequest  = &GetProjectStatusByURIRequest{}
	emptyStovepipeServiceGetProjectStatusByURIYARPCResponse = &GetProjectStatusByURIResponse{}
)

var yarpcFileDescriptorClosurefabdb6b3c0b09022 = [][]byte{
	// stovepipe.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xea, 0x56,
		0x10, 0xc6, 0x10, 0x7e, 0x3c, 0x01, 0x82, 0x8e, 0xd2, 0xd4, 0x21, 0xa1, 0xa2, 0x96, 0xda, 0xd0,
		0xa8, 0x02, 0x35, 0xdd, 0xa4, 0x4b, 0x30, 0x4e, 0x82, 0x94, 0x52, 0xd7, 0x86, 0x4d, 0xbb, 0xb0,
		0x0c, 0x8c, 0x88, 0x9b, 0x18, 0x3b, 0x3e, 0xc7, 0x51, 0x93, 0x7d, 0xa5, 0xac, 0xfa, 0x40, 0x7d,
		0x93, 0x4a, 0xf7, 0x01, 0xee, 0x63, 0x5c, 0xd9, 0x3e, 0x36, 0x3f, 0xb9, 0x70, 0xaf, 0xee, 0xce,
		0xf3, 0x7d, 0x33, 0x73, 0x66, 0xbe, 0x39, 0x9e, 0x03, 0x07, 0x94, 0xb9, 0x4f, 0xe8, 0xd9, 0x1e,
		0xb6, 0x3d, 0xdf, 0x65, 0x2e, 0xa9, 0x07, 0x13, 0xf4, 0xdb, 0x34, 0x98, 0x38, 0x36, 0x7b, 0x0c,
		0x30, 0xc0, 0x76, 0xea, 0x21, 0x9f, 0xc1, 0xbe, 0x66, 0x2f, 0xe6, 0x3a, 0x3e, 0x06, 0x48, 0x19,
		0x91, 0xa0, 0xe8, 0x20, 0xa5, 0xd6, 0x1c, 0x25, 0xa1, 0x29, 0xb4, 0x44, 0x3d, 0x31, 0xe5, 0x7f,
		0x04, 0x28, 0xc7, 0x9e, 0xd4, 0x73, 0x17, 0x14, 0xb7, 0xbb, 0x92, 0x6f, 0xa1, 0x4c, 0xd1, 0x7f,
		0xb2, 0xa7, 0x68, 0x2e, 0x2c, 0x07, 0xa5, 0x6c, 0x44, 0xef, 0x73, 0x6c, 0x68, 0x39, 0x48, 0x4e,
		0x41, 0x64, 0xb6, 0x83, 0x94, 0x59, 0x8e, 0x27, 0xe5, 0x9a, 0x42, 0x2b, 0xa7, 0x2f, 0x01, 0x52,
		0x87, 0xd2, 0x9d, 0x4b, 0x59, 0x14, 0xbc, 0x17, 0x05, 0xa7, 0xb6, 0xfc, 0x1d, 0x54, 0x06, 0x8b,
		0x39, 0x52, 0x96, 0x94, 0x7c, 0x08, 0xf9, 0xa8, 0x29, 0x5e, 0x45, 0x6c, 0xc8, 0x4d, 0xa8, 0x26,
		0x6e, 0xbc, 0xde, 0x2a, 0x64, 0xed, 0x19, 0x77, 0xca, 0xda, 0x33, 0xf9, 0x3f, 0x01, 0x4e, 0xaf,
		0x91, 0x69, 0xbe, 0xfb, 0x17, 0x4e, 0x99, 0xc1, 0x2c, 0x16, 0xd0, 0xde, 0xf3, 0x58, 0x1f, 0xec,
		0x4c, 0x4c, 0x1a, 0x00, 0xd3, 0x3b, 0x6b, 0x31, 0x47, 0x33, 0xf0, 0x6d, 0xde, 0x9a, 0x18, 0x23,
		0x63, 0xdf, 0x26, 0x0d, 0x28, 0x7a, 0x71, 0xc6, 0xa8, 0x2d, 0xf1, 0x26, 0xa3, 0x27, 0xc0, 0xab,
		0x20, 0x90, 0x13, 0x10, 0x3d, 0x6b, 0x8e, 0x26, 0xb5, 0x5f, 0xe2, 0xd6, 0xf2, 0x7a, 0x29, 0x04,
		0x0c, 0xfb, 0x25, 0x4a, 0x1d, 0x91, 0xcc, 0xbd, 0xc7, 0x85, 0x94, 0x8f, 0x53, 0x87, 0xc8, 0x28,
		0x04, 0x7a, 0x00, 0x25, 0x93, 0xa7, 0x92, 0xef, 0xa1, 0xb2, 0x56, 0x78, 0x38, 0x8d, 0xe4, 0x5c,
		0x3e, 0x0d, 0x6e, 0x92, 0x1f, 0xe1, 0x60, 0xe2, 0xa3, 0x75, 0x1f, 0x66, 0x9e, 0xe1, 0xdc, 0xc7,
		0x78, 0x20, 0xc2, 0x4d, 0x46, 0xaf, 0x26, 0x44, 0x3f, 0xc2, 0x5f, 0x05, 0xa1, 0x47, 0xa0, 0x66,
		0x6e, 0xb8, 0xcb, 0xef, 0x73, 0xd0, 0xd8, 0xa2, 0x14, 0xd7, 0xb6, 0x01, 0xe0, 0xc7, 0xaa, 0x99,
		0xa9, 0xc6, 0x22, 0x47, 0x06, 0xb3, 0xa5, 0x92, 0xd9, 0xed, 0x4a, 0xe6, 0x36, 0x95, 0x3c, 0x86,
		0xd2, 0xc4, 0xa2, 0x31, 0x19, 0x5f, 0x82, 0x62, 0x68, 0x87, 0xd4, 0xaf, 0x50, 0x49, 0x8e, 0xa3,
		0xcc, 0x62, 0x18, 0x69, 0x55, 0xbd, 0x68, 0xb5, 0xb7, 0x5f, 0xf4, 0x36, 0x9f, 0x6a, 0x58, 0x3d,
		0xea, 0x65, 0x7f, 0xc5, 0x22, 0x5d, 0xa8, 0xfb, 0xe8, 0xb9, 0xd4, 0x66, 0xae, 0xff, 0xbc, 0xd9,
		0xbd, 0x54, 0xe0, 0x62, 0x49, 0x4b, 0x9f, 0xde, 0xa6, 0x6c, 0xe4, 0x12, 0x24, 0xae, 0xb7, 0xe9,
		0x23, 0x0d, 0x1e, 0x18, 0x35, 0xa7, 0xae, 0xe3, 0x3d, 0x20, 0x43, 0xa9, 0xd8, 0x14, 0x5a, 0x25,
		0xfd, 0x88, 0xf3, 0x7a, 0x4c, 0x2b, 0x9c, 0x25, 0x2a, 0x94, 0x38, 0x43, 0xa5, 0x52, 0x33, 0xd7,
		0xda, 0xbf, 0xf8, 0x61, 0x57, 0x1b, 0x6b, 0x43, 0xd0, 0xd3, 0x50, 0xf2, 0x3d, 0x1c, 0x2c, 0xf0,
		0x6f, 0x66, 0xae, 0x5c, 0x20, 0x31, 0x12, 0xad, 0x12, 0xc2, 0x5a, 0x7a, 0x89, 0x1a, 0x70, 0x62,
		0x6e, 0x6f, 0xf6, 0xfc, 0x7f, 0x01, 0xca, 0xab, 0x4a, 0x91, 0x06, 0x1c, 0xeb, 0xea, 0xef, 0x63,
		0xd5, 0x18, 0x99, 0xc6, 0xa8, 0x3b, 0x52, 0xcd, 0xf1, 0xd0, 0xd0, 0x54, 0x65, 0x70, 0x35, 0x50,
		0xfb, 0xb5, 0x0c, 0xa9, 0xc3, 0xd1, 0x3a, 0xdd, 0x55, 0x14, 0x55, 0x1b, 0xa9, 0xfd, 0x9a, 0x40,
		0x4e, 0x41, 0x5a, 0xe7, 0x34, 0xfd, 0x37, 0x45, 0x35, 0x8c, 0xc1, 0xf0, 0xba, 0x96, 0x25, 0x27,
		0xf0, 0xf5, 0x3a, 0x6b, 0x8c, 0x15, 0x45, 0x55, 0xfb, 0x6a, 0xbf, 0x96, 0x23, 0x12, 0x1c, 0xae,
		0x93, 0x57, 0xdd, 0xc1, 0xad, 0xda, 0xaf, 0xed, 0xbd, 0x0d, 0x53, 0xba, 0x43, 0x45, 0xbd, 0x0d,
		0xc9, 0xfc, 0xdb, 0x13, 0x8d, 0xb1, 0xa6, 0xea, 0x46, 0x94, 0xb4, 0x70, 0xf1, 0x2e, 0x0b, 0xa2,
		0x91, 0x08, 0x49, 0xfe, 0x84, 0xbd, 0x70, 0x9d, 0x91, 0xb3, 0x9d, 0x6a, 0x2f, 0x57, 0x63, 0xbd,
		0xf5, 0x69, 0xc7, 0xf8, 0x6f, 0x90, 0x33, 0xc4, 0x82, 0x42, 0xbc, 0x7d, 0xc8, 0xce, 0x61, 0xae,
		0x2d, 0xb2, 0xfa, 0xf9, 0xe7, 0xb8, 0xa6, 0x47, 0xfc, 0x2b, 0xc0, 0x57, 0x1f, 0xfd, 0x29, 0xc9,
		0xe5, 0xae, 0x3c, 0xbb, 0x36, 0x5e, 0xfd, 0x97, 0x2f, 0x88, 0x4c, 0x0a, 0xea, 0x21, 0x7c, 0x33,
		0x75, 0x9d, 0x1d, 0x19, 0x7a, 0xd5, 0x54, 0x7d, 0x2d, 0x7c, 0x97, 0x34, 0xe1, 0x8f, 0x9f, 0xe6,
		0x36, 0xbb, 0x0b, 0x26, 0xed, 0xa9, 0xeb, 0x74, 0xc2, 0xc0, 0xce, 0x4a, 0x60, 0xc7, 0xf2, 0xec,
		0x4e, 0x1a, 0xdc, 0x89, 0x9e, 0x32, 0x6f, 0x32, 0x29, 0x44, 0x1f, 0x3f, 0x7f, 0x08, 0x00, 0x00,
		0xff, 0xff, 0x42, 0x57, 0xf2, 0x92, 0xe6, 0x06, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) StovepipeYARPCClient {
			return NewStovepipeYARPCClient(clientConfig, v2.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
