// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: stovepipe.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
	v2 "go.uber.org/yarpc/encoding/protobuf/v2"
	"google.golang.org/protobuf/proto"
)

var _ = ioutil.NopCloser

// StovepipeYARPCClient is the YARPC client-side interface for the Stovepipe service.
type StovepipeYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
	Ingest(context.Context, *IngestRequest, ...yarpc.CallOption) (*IngestResponse, error)
}

func newStovepipeYARPCClient(clientConfig transport.ClientConfig, anyResolver v2.AnyResolver, options ...v2.ClientOption) StovepipeYARPCClient {
	return &_StovepipeYARPCCaller{v2.NewStreamClient(
		v2.ClientParams{
			ServiceName:  "uber.submitqueue.stovepipe.Stovepipe",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewStovepipeYARPCClient builds a new YARPC client for the Stovepipe service.
func NewStovepipeYARPCClient(clientConfig transport.ClientConfig, options ...v2.ClientOption) StovepipeYARPCClient {
	return newStovepipeYARPCClient(clientConfig, nil, options...)
}

// StovepipeYARPCServer is the YARPC server-side interface for the Stovepipe service.
type StovepipeYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
}

type buildStovepipeYARPCProceduresParams struct {
	Server      StovepipeYARPCServer
	AnyResolver v2.AnyResolver
}

func buildStovepipeYARPCProcedures(params buildStovepipeYARPCProceduresParams) []transport.Procedure {
	handler := &_StovepipeYARPCHandler{params.Server}
	return v2.BuildProcedures(
		v2.BuildProceduresParams{
			ServiceName: "uber.submitqueue.stovepipe.Stovepipe",
			UnaryHandlerParams: []v2.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newStovepipeServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Ingest",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ingest,
							NewRequest:  newStovepipeServiceIngestYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []v2.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []v2.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildStovepipeYARPCProcedures prepares an implementation of the Stovepipe service for YARPC registration.
func BuildStovepipeYARPCProcedures(server StovepipeYARPCServer) []transport.Procedure {
	return buildStovepipeYARPCProcedures(buildStovepipeYARPCProceduresParams{Server: server})
}

// FxStovepipeYARPCClientParams defines the input
// for NewFxStovepipeYARPCClient. It provides the
// paramaters to get a StovepipeYARPCClient in an
// Fx application.
type FxStovepipeYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver v2.AnyResolver      `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxStovepipeYARPCClientResult defines the output
// of NewFxStovepipeYARPCClient. It provides a
// StovepipeYARPCClient to an Fx application.
type FxStovepipeYARPCClientResult struct {
	fx.Out

	Client StovepipeYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxStovepipeYARPCClient provides a StovepipeYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxStovepipeYARPCClient("service-name"),
//	  ...
//	)
func NewFxStovepipeYARPCClient(name string, options ...v2.ClientOption) interface{} {
	return func(params FxStovepipeYARPCClientParams) FxStovepipeYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(v2.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxStovepipeYARPCClientResult{
			Client: newStovepipeYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxStovepipeYARPCProceduresParams defines the input
// for NewFxStovepipeYARPCProcedures. It provides the
// paramaters to get StovepipeYARPCServer procedures in an
// Fx application.
type FxStovepipeYARPCProceduresParams struct {
	fx.In

	Server      StovepipeYARPCServer
	AnyResolver v2.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxStovepipeYARPCProceduresResult defines the output
// of NewFxStovepipeYARPCProcedures. It provides
// StovepipeYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxStovepipeYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxStovepipeYARPCProcedures provides StovepipeYARPCServer procedures to an Fx application.
// It expects a StovepipeYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxStovepipeYARPCProcedures(),
//	  ...
//	)
func NewFxStovepipeYARPCProcedures() interface{} {
	return func(params FxStovepipeYARPCProceduresParams) FxStovepipeYARPCProceduresResult {
		return FxStovepipeYARPCProceduresResult{
			Procedures: buildStovepipeYARPCProcedures(buildStovepipeYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: reflection.ServerMeta{
				ServiceName:     "uber.submitqueue.stovepipe.Stovepipe",
				FileDescriptors: yarpcFileDescriptorClosurefabdb6b3c0b09022,
			},
		}
	}
}

type _StovepipeYARPCCaller struct {
	streamClient v2.StreamClient
}

func (c *_StovepipeYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newStovepipeServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_StovepipeYARPCCaller) Ingest(ctx context.Context, request *IngestRequest, options ...yarpc.CallOption) (*IngestResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ingest", request, newStovepipeServiceIngestYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*IngestResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServiceIngestYARPCResponse, responseMessage)
	}
	return response, err
}

type _StovepipeYARPCHandler struct {
	server StovepipeYARPCServer
}

func (h *_StovepipeYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_StovepipeYARPCHandler) Ingest(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *IngestRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*IngestRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServiceIngestYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ingest(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newStovepipeServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newStovepipeServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

func newStovepipeServiceIngestYARPCRequest() proto.Message {
	return &IngestRequest{}
}

func newStovepipeServiceIngestYARPCResponse() proto.Message {
	return &IngestResponse{}
}

var (
	emptyStovepipeServicePingYARPCRequest    = &PingRequest{}
	emptyStovepipeServicePingYARPCResponse   = &PingResponse{}
	emptyStovepipeServiceIngestYARPCRequest  = &IngestRequest{}
	emptyStovepipeServiceIngestYARPCResponse = &IngestResponse{}
)

var yarpcFileDescriptorClosurefabdb6b3c0b09022 = [][]byte{
	// stovepipe.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4e, 0xf3, 0x30,
		0x10, 0xc5, 0x3f, 0xb7, 0xfd, 0x0a, 0x9d, 0x96, 0x22, 0x59, 0x2c, 0xa2, 0x08, 0xa1, 0x12, 0x09,
		0xb5, 0xb0, 0x70, 0x04, 0xdc, 0xa0, 0x3b, 0x36, 0xa8, 0x0a, 0x3b, 0x58, 0x20, 0x27, 0x1d, 0xa5,
		0x5e, 0x38, 0x76, 0x63, 0xbb, 0x37, 0xe0, 0x74, 0x5c, 0x0a, 0xc5, 0xf9, 0x43, 0x59, 0xb4, 0xb0,
		0xf3, 0x8c, 0xdf, 0x4f, 0xf3, 0xde, 0x68, 0xe0, 0xdc, 0x58, 0xb5, 0x43, 0x2d, 0x34, 0x32, 0x5d,
		0x2a, 0xab, 0x68, 0xe8, 0x52, 0x2c, 0x99, 0x71, 0xa9, 0x14, 0x76, 0xeb, 0xd0, 0x21, 0xeb, 0x14,
		0xd1, 0x1c, 0xc6, 0x2b, 0x51, 0xe4, 0x09, 0x6e, 0x1d, 0x1a, 0x4b, 0x03, 0x38, 0x91, 0x68, 0x0c,
		0xcf, 0x31, 0x20, 0x33, 0xb2, 0x18, 0x25, 0x6d, 0x19, 0x7d, 0x10, 0x98, 0xd4, 0x4a, 0xa3, 0x55,
		0x61, 0xf0, 0xb0, 0x94, 0x5e, 0xc3, 0xc4, 0x60, 0xb9, 0x13, 0x19, 0xbe, 0x17, 0x5c, 0x62, 0xd0,
		0xf3, 0xdf, 0xe3, 0xa6, 0xf7, 0xcc, 0x25, 0xd2, 0x4b, 0x18, 0x59, 0x21, 0xd1, 0x58, 0x2e, 0x75,
		0xd0, 0x9f, 0x91, 0x45, 0x3f, 0xf9, 0x6e, 0xd0, 0x10, 0x4e, 0x37, 0xca, 0x58, 0x0f, 0x0f, 0x3c,
		0xdc, 0xd5, 0xd1, 0x0d, 0x9c, 0x3d, 0x15, 0x39, 0x1a, 0xdb, 0x5a, 0xbe, 0x80, 0xff, 0x3e, 0x54,
		0xe3, 0xa2, 0x2e, 0xa2, 0x19, 0x4c, 0x5b, 0x59, 0xe3, 0x77, 0x0a, 0x3d, 0xb1, 0x6e, 0x44, 0x3d,
		0xb1, 0x7e, 0xf8, 0x24, 0x30, 0x7a, 0x69, 0xf7, 0x40, 0xdf, 0x60, 0x50, 0xa5, 0xa3, 0x73, 0x76,
		0x78, 0x59, 0x6c, 0x6f, 0x53, 0xe1, 0xe2, 0x77, 0x61, 0x3d, 0x38, 0xfa, 0x47, 0x39, 0x0c, 0x6b,
		0x33, 0xf4, 0xf6, 0x18, 0xf5, 0x23, 0x57, 0x78, 0xf7, 0x17, 0x69, 0x3b, 0x62, 0x89, 0x70, 0x95,
		0x29, 0x79, 0x04, 0x59, 0x4e, 0xbb, 0xb0, 0xab, 0xea, 0x2a, 0x56, 0xe4, 0xf5, 0x3e, 0x17, 0x76,
		0xe3, 0x52, 0x96, 0x29, 0x19, 0x57, 0x60, 0xbc, 0x07, 0xc6, 0x5c, 0x8b, 0xb8, 0x83, 0x63, 0x7f,
		0x48, 0x3a, 0x4d, 0x87, 0xfe, 0xf1, 0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x6e, 0x43, 0xbc,
		0x64, 0x02, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) StovepipeYARPCClient {
			return NewStovepipeYARPCClient(clientConfig, v2.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
