// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: stovepipe.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
	v2 "go.uber.org/yarpc/encoding/protobuf/v2"
	"google.golang.org/protobuf/proto"
)

var _ = ioutil.NopCloser

// StovepipeYARPCClient is the YARPC client-side interface for the Stovepipe service.
type StovepipeYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
	Ingest(context.Context, *IngestRequest, ...yarpc.CallOption) (*IngestResponse, error)
	GetRequestHistoryByID(context.Context, *GetRequestHistoryByIDRequest, ...yarpc.CallOption) (*GetRequestHistoryByIDResponse, error)
	GetRequestHistoryByURI(context.Context, *GetRequestHistoryByURIRequest, ...yarpc.CallOption) (*GetRequestHistoryByURIResponse, error)
	GetProjectStatusByURI(context.Context, *GetProjectStatusByURIRequest, ...yarpc.CallOption) (*GetProjectStatusByURIResponse, error)
}

func newStovepipeYARPCClient(clientConfig transport.ClientConfig, anyResolver v2.AnyResolver, options ...v2.ClientOption) StovepipeYARPCClient {
	return &_StovepipeYARPCCaller{v2.NewStreamClient(
		v2.ClientParams{
			ServiceName:  "uber.submitqueue.stovepipe.Stovepipe",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewStovepipeYARPCClient builds a new YARPC client for the Stovepipe service.
func NewStovepipeYARPCClient(clientConfig transport.ClientConfig, options ...v2.ClientOption) StovepipeYARPCClient {
	return newStovepipeYARPCClient(clientConfig, nil, options...)
}

// StovepipeYARPCServer is the YARPC server-side interface for the Stovepipe service.
type StovepipeYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	GetRequestHistoryByID(context.Context, *GetRequestHistoryByIDRequest) (*GetRequestHistoryByIDResponse, error)
	GetRequestHistoryByURI(context.Context, *GetRequestHistoryByURIRequest) (*GetRequestHistoryByURIResponse, error)
	GetProjectStatusByURI(context.Context, *GetProjectStatusByURIRequest) (*GetProjectStatusByURIResponse, error)
}

type buildStovepipeYARPCProceduresParams struct {
	Server      StovepipeYARPCServer
	AnyResolver v2.AnyResolver
}

func buildStovepipeYARPCProcedures(params buildStovepipeYARPCProceduresParams) []transport.Procedure {
	handler := &_StovepipeYARPCHandler{params.Server}
	return v2.BuildProcedures(
		v2.BuildProceduresParams{
			ServiceName: "uber.submitqueue.stovepipe.Stovepipe",
			UnaryHandlerParams: []v2.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newStovepipeServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Ingest",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ingest,
							NewRequest:  newStovepipeServiceIngestYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetRequestHistoryByID",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetRequestHistoryByID,
							NewRequest:  newStovepipeServiceGetRequestHistoryByIDYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetRequestHistoryByURI",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetRequestHistoryByURI,
							NewRequest:  newStovepipeServiceGetRequestHistoryByURIYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetProjectStatusByURI",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetProjectStatusByURI,
							NewRequest:  newStovepipeServiceGetProjectStatusByURIYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []v2.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []v2.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildStovepipeYARPCProcedures prepares an implementation of the Stovepipe service for YARPC registration.
func BuildStovepipeYARPCProcedures(server StovepipeYARPCServer) []transport.Procedure {
	return buildStovepipeYARPCProcedures(buildStovepipeYARPCProceduresParams{Server: server})
}

// FxStovepipeYARPCClientParams defines the input
// for NewFxStovepipeYARPCClient. It provides the
// paramaters to get a StovepipeYARPCClient in an
// Fx application.
type FxStovepipeYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver v2.AnyResolver      `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxStovepipeYARPCClientResult defines the output
// of NewFxStovepipeYARPCClient. It provides a
// StovepipeYARPCClient to an Fx application.
type FxStovepipeYARPCClientResult struct {
	fx.Out

	Client StovepipeYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxStovepipeYARPCClient provides a StovepipeYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxStovepipeYARPCClient("service-name"),
//	  ...
//	)
func NewFxStovepipeYARPCClient(name string, options ...v2.ClientOption) interface{} {
	return func(params FxStovepipeYARPCClientParams) FxStovepipeYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(v2.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxStovepipeYARPCClientResult{
			Client: newStovepipeYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxStovepipeYARPCProceduresParams defines the input
// for NewFxStovepipeYARPCProcedures. It provides the
// paramaters to get StovepipeYARPCServer procedures in an
// Fx application.
type FxStovepipeYARPCProceduresParams struct {
	fx.In

	Server      StovepipeYARPCServer
	AnyResolver v2.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxStovepipeYARPCProceduresResult defines the output
// of NewFxStovepipeYARPCProcedures. It provides
// StovepipeYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxStovepipeYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxStovepipeYARPCProcedures provides StovepipeYARPCServer procedures to an Fx application.
// It expects a StovepipeYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxStovepipeYARPCProcedures(),
//	  ...
//	)
func NewFxStovepipeYARPCProcedures() interface{} {
	return func(params FxStovepipeYARPCProceduresParams) FxStovepipeYARPCProceduresResult {
		return FxStovepipeYARPCProceduresResult{
			Procedures: buildStovepipeYARPCProcedures(buildStovepipeYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: reflection.ServerMeta{
				ServiceName:     "uber.submitqueue.stovepipe.Stovepipe",
				FileDescriptors: yarpcFileDescriptorClosurefabdb6b3c0b09022,
			},
		}
	}
}

type _StovepipeYARPCCaller struct {
	streamClient v2.StreamClient
}

func (c *_StovepipeYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newStovepipeServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_StovepipeYARPCCaller) Ingest(ctx context.Context, request *IngestRequest, options ...yarpc.CallOption) (*IngestResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ingest", request, newStovepipeServiceIngestYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*IngestResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServiceIngestYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_StovepipeYARPCCaller) GetRequestHistoryByID(ctx context.Context, request *GetRequestHistoryByIDRequest, options ...yarpc.CallOption) (*GetRequestHistoryByIDResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetRequestHistoryByID", request, newStovepipeServiceGetRequestHistoryByIDYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetRequestHistoryByIDResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServiceGetRequestHistoryByIDYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_StovepipeYARPCCaller) GetRequestHistoryByURI(ctx context.Context, request *GetRequestHistoryByURIRequest, options ...yarpc.CallOption) (*GetRequestHistoryByURIResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetRequestHistoryByURI", request, newStovepipeServiceGetRequestHistoryByURIYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetRequestHistoryByURIResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServiceGetRequestHistoryByURIYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_StovepipeYARPCCaller) GetProjectStatusByURI(ctx context.Context, request *GetProjectStatusByURIRequest, options ...yarpc.CallOption) (*GetProjectStatusByURIResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetProjectStatusByURI", request, newStovepipeServiceGetProjectStatusByURIYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetProjectStatusByURIResponse)
	if !ok {
		return nil, v2.CastError(emptyStovepipeServiceGetProjectStatusByURIYARPCResponse, responseMessage)
	}
	return response, err
}

type _StovepipeYARPCHandler struct {
	server StovepipeYARPCServer
}

func (h *_StovepipeYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_StovepipeYARPCHandler) Ingest(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *IngestRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*IngestRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServiceIngestYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ingest(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_StovepipeYARPCHandler) GetRequestHistoryByID(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetRequestHistoryByIDRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetRequestHistoryByIDRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServiceGetRequestHistoryByIDYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetRequestHistoryByID(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_StovepipeYARPCHandler) GetRequestHistoryByURI(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetRequestHistoryByURIRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetRequestHistoryByURIRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServiceGetRequestHistoryByURIYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetRequestHistoryByURI(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_StovepipeYARPCHandler) GetProjectStatusByURI(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetProjectStatusByURIRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetProjectStatusByURIRequest)
		if !ok {
			return nil, v2.CastError(emptyStovepipeServiceGetProjectStatusByURIYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetProjectStatusByURI(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newStovepipeServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newStovepipeServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

func newStovepipeServiceIngestYARPCRequest() proto.Message {
	return &IngestRequest{}
}

func newStovepipeServiceIngestYARPCResponse() proto.Message {
	return &IngestResponse{}
}

func newStovepipeServiceGetRequestHistoryByIDYARPCRequest() proto.Message {
	return &GetRequestHistoryByIDRequest{}
}

func newStovepipeServiceGetRequestHistoryByIDYARPCResponse() proto.Message {
	return &GetRequestHistoryByIDResponse{}
}

func newStovepipeServiceGetRequestHistoryByURIYARPCRequest() proto.Message {
	return &GetRequestHistoryByURIRequest{}
}

func newStovepipeServiceGetRequestHistoryByURIYARPCResponse() proto.Message {
	return &GetRequestHistoryByURIResponse{}
}

func newStovepipeServiceGetProjectStatusByURIYARPCRequest() proto.Message {
	return &GetProjectStatusByURIRequest{}
}

func newStovepipeServiceGetProjectStatusByURIYARPCResponse() proto.Message {
	return &GetProjectStatusByURIResponse{}
}

var (
	emptyStovepipeServicePingYARPCRequest                    = &PingRequest{}
	emptyStovepipeServicePingYARPCResponse                   = &PingResponse{}
	emptyStovepipeServiceIngestYARPCRequest                  = &IngestRequest{}
	emptyStovepipeServiceIngestYARPCResponse                 = &IngestResponse{}
	emptyStovepipeServiceGetRequestHistoryByIDYARPCRequest   = &GetRequestHistoryByIDRequest{}
	emptyStovepipeServiceGetRequestHistoryByIDYARPCResponse  = &GetRequestHistoryByIDResponse{}
	emptyStovepipeServiceGetRequestHistoryByURIYARPCRequest  = &GetRequestHistoryByURIRequest{}
	emptyStovepipeServiceGetRequestHistoryByURIYARPCResponse = &GetRequestHistoryByURIResponse{}
	emptyStovepipeServiceGetProjectStatusByURIYARPCRequest   = &GetProjectStatusByURIRequest{}
	emptyStovepipeServiceGetProjectStatusByURIYARPCResponse  = &GetProjectStatusByURIResponse{}
)

var yarpcFileDescriptorClosurefabdb6b3c0b09022 = [][]byte{
	// stovepipe.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x73, 0xdb, 0x44,
		0x18, 0xb6, 0xe2, 0x3a, 0xb6, 0xde, 0x38, 0x4e, 0xd9, 0x81, 0x8c, 0xea, 0xd6, 0x9d, 0x20, 0x26,
		0xd4, 0x74, 0xc0, 0x1e, 0xca, 0xa5, 0x70, 0xa2, 0xa6, 0x4c, 0xed, 0x43, 0x19, 0x8f, 0x42, 0x39,
		0xc0, 0x41, 0xb3, 0x96, 0xde, 0x71, 0xb6, 0x8d, 0xb4, 0x8a, 0x76, 0x95, 0xa1, 0xbd, 0x71, 0x60,
		0xa6, 0x27, 0x66, 0xf8, 0x3b, 0x9c, 0xf8, 0x35, 0xfc, 0x0e, 0x66, 0x3f, 0x24, 0x27, 0xae, 0xad,
		0xb4, 0xb9, 0x69, 0x9f, 0xf7, 0x73, 0x9f, 0x7d, 0xf6, 0x5d, 0xc1, 0x81, 0x90, 0xfc, 0x02, 0x33,
		0x96, 0xe1, 0x28, 0xcb, 0xb9, 0xe4, 0xa4, 0x5f, 0x2c, 0x30, 0x1f, 0x89, 0x62, 0x91, 0x30, 0x79,
		0x5e, 0x60, 0x81, 0xa3, 0xca, 0xc3, 0x7f, 0x00, 0x7b, 0x73, 0x96, 0x2e, 0x03, 0x3c, 0x2f, 0x50,
		0x48, 0xe2, 0x41, 0x3b, 0x41, 0x21, 0xe8, 0x12, 0x3d, 0xe7, 0xc8, 0x19, 0xba, 0x41, 0xb9, 0xf4,
		0xff, 0x74, 0xa0, 0x6b, 0x3c, 0x45, 0xc6, 0x53, 0x81, 0xdb, 0x5d, 0xc9, 0xa7, 0xd0, 0x15, 0x98,
		0x5f, 0xb0, 0x08, 0xc3, 0x94, 0x26, 0xe8, 0xed, 0x68, 0xf3, 0x9e, 0xc5, 0x7e, 0xa2, 0x09, 0x92,
		0x7b, 0xe0, 0x4a, 0x96, 0xa0, 0x90, 0x34, 0xc9, 0xbc, 0xe6, 0x91, 0x33, 0x6c, 0x06, 0x2b, 0x80,
		0xf4, 0xa1, 0x73, 0xca, 0x85, 0xd4, 0xc1, 0xb7, 0x74, 0x70, 0xb5, 0xf6, 0x8f, 0x61, 0x7f, 0x96,
		0x2e, 0x51, 0xc8, 0xb2, 0xe5, 0x8f, 0xa1, 0xa5, 0x37, 0x65, 0xbb, 0x30, 0x0b, 0xff, 0x08, 0x7a,
		0xa5, 0x9b, 0xed, 0xb7, 0x07, 0x3b, 0x2c, 0xb6, 0x4e, 0x3b, 0x2c, 0xf6, 0x4f, 0xe0, 0xde, 0x33,
		0x2c, 0xb3, 0x4c, 0x99, 0x90, 0x3c, 0x7f, 0x3d, 0x79, 0x3d, 0x7b, 0x5a, 0x9b, 0x97, 0x0c, 0x00,
		0x72, 0xe3, 0x10, 0xb2, 0xd8, 0xee, 0xcc, 0xb5, 0xc8, 0x2c, 0xf6, 0x9f, 0xc1, 0x60, 0x43, 0xd2,
		0x17, 0xc1, 0xac, 0x3e, 0xeb, 0x6d, 0x68, 0x16, 0x39, 0xb3, 0xe9, 0xd4, 0xa7, 0xff, 0xaf, 0x03,
		0x5d, 0x1b, 0xff, 0xe3, 0x05, 0xa6, 0x92, 0xdc, 0x81, 0x0e, 0xaa, 0x8f, 0xb0, 0xda, 0x44, 0x5b,
		0xaf, 0x67, 0xb1, 0xe2, 0xbb, 0xe2, 0x2e, 0x4c, 0x84, 0x4e, 0xd3, 0x0c, 0xf6, 0x2a, 0xec, 0xb9,
		0x20, 0xc7, 0xb0, 0x5f, 0xb6, 0x2d, 0x24, 0x95, 0xa8, 0x39, 0x77, 0xa7, 0x8d, 0xa0, 0x6b, 0xe1,
		0x13, 0x85, 0x92, 0x43, 0x68, 0xe9, 0xa4, 0x86, 0xf5, 0x69, 0x23, 0x30, 0x4b, 0x72, 0x0c, 0x3d,
		0x5e, 0xc8, 0x88, 0x27, 0x18, 0xe6, 0x48, 0x05, 0x4f, 0xbd, 0x96, 0x6e, 0x61, 0xdf, 0xa2, 0x81,
		0x06, 0x27, 0x5d, 0x00, 0x1e, 0x45, 0x45, 0x9e, 0x63, 0x1a, 0xa1, 0x7f, 0x0e, 0xbd, 0xab, 0x44,
		0xac, 0x91, 0xe7, 0xac, 0x91, 0x47, 0xbe, 0x87, 0x5d, 0x5d, 0x4e, 0xed, 0xa0, 0x39, 0xdc, 0x7b,
		0x34, 0x1c, 0x6d, 0x17, 0xee, 0xe8, 0x32, 0x39, 0x81, 0x8d, 0xf3, 0xe9, 0x46, 0xfa, 0xd5, 0x99,
		0x5a, 0x11, 0xac, 0x4a, 0x38, 0x37, 0x2c, 0xf1, 0x12, 0xee, 0x6f, 0x3b, 0x61, 0x5b, 0x63, 0x0a,
		0xee, 0xa9, 0xc6, 0x19, 0x96, 0x65, 0x1e, 0xd6, 0x95, 0xb9, 0x9a, 0x2b, 0x58, 0x05, 0xfb, 0xff,
		0x38, 0x5a, 0xa3, 0xf3, 0x9c, 0xbf, 0xc4, 0x48, 0x1f, 0x51, 0x21, 0xde, 0x43, 0x4d, 0x03, 0x80,
		0xe8, 0x94, 0xa6, 0x4b, 0x0c, 0x57, 0xa2, 0x72, 0x0d, 0xf2, 0x22, 0x67, 0x64, 0x00, 0xed, 0xcc,
		0x64, 0xac, 0x54, 0x50, 0x02, 0x6f, 0x1d, 0x87, 0xdc, 0x05, 0x37, 0xa3, 0x4b, 0x0c, 0x05, 0x7b,
		0x63, 0x6e, 0x5f, 0x2b, 0xe8, 0x28, 0xe0, 0x84, 0xbd, 0xd1, 0xa9, 0xb5, 0x51, 0xf2, 0x57, 0x58,
		0x8a, 0x40, 0xbb, 0xff, 0xac, 0x80, 0x09, 0x40, 0x27, 0xb4, 0xa9, 0x7c, 0x0e, 0x1f, 0xd9, 0xc6,
		0x7f, 0xa1, 0x67, 0x2c, 0xa6, 0x92, 0xf1, 0x54, 0x0d, 0x8d, 0xb2, 0xb6, 0x15, 0xb1, 0x5d, 0x92,
		0x2f, 0xe1, 0x60, 0x91, 0x23, 0x7d, 0xa5, 0xb2, 0xc7, 0xb8, 0xcc, 0xd1, 0xcc, 0x0d, 0x67, 0xda,
		0x08, 0x7a, 0xa5, 0xe1, 0xa9, 0xc6, 0xdf, 0x3a, 0xce, 0x84, 0xc0, 0xed, 0x70, 0xcd, 0xdd, 0xff,
		0xaf, 0xa9, 0x4f, 0x7f, 0x13, 0x5b, 0xf6, 0x64, 0xae, 0xd1, 0x5f, 0xc5, 0xe6, 0xce, 0x76, 0x36,
		0x9b, 0xeb, 0x6c, 0xde, 0x81, 0xce, 0x82, 0x0a, 0x63, 0x34, 0xb3, 0xaa, 0xad, 0xd6, 0xca, 0xf4,
		0xd9, 0xfa, 0xa5, 0x33, 0x7c, 0x5d, 0xbd, 0x72, 0x3e, 0xec, 0x17, 0x59, 0x4c, 0x25, 0xc6, 0x21,
		0x95, 0xea, 0xf6, 0x82, 0xb9, 0xbd, 0x16, 0x7c, 0x22, 0x9f, 0x0b, 0xf2, 0x04, 0xfa, 0x39, 0x66,
		0x5c, 0x30, 0x25, 0x90, 0xf5, 0x7d, 0x7b, 0xbb, 0x96, 0x26, 0x6f, 0xe5, 0x33, 0x59, 0x27, 0x8c,
		0x3c, 0x06, 0xcf, 0x32, 0x1d, 0xe6, 0x28, 0x8a, 0x33, 0x29, 0xc2, 0x88, 0x27, 0xd9, 0x19, 0x4a,
		0xf4, 0xda, 0x47, 0xce, 0xb0, 0x13, 0x1c, 0x5a, 0x7b, 0x60, 0xcc, 0x3f, 0x58, 0x2b, 0x99, 0x41,
		0xc7, 0x5a, 0x84, 0xd7, 0xd1, 0x6a, 0xfe, 0xaa, 0x4e, 0xcd, 0xef, 0x9c, 0x79, 0x50, 0x85, 0x93,
		0xcf, 0xe1, 0x20, 0xc5, 0xdf, 0x65, 0x78, 0x49, 0x42, 0xae, 0x99, 0x23, 0x0a, 0x9e, 0x57, 0x32,
		0x1a, 0xc0, 0xdd, 0x70, 0xfb, 0x86, 0x1f, 0xfd, 0xd1, 0x02, 0xf7, 0xa4, 0x2c, 0x48, 0x7e, 0x83,
		0x5b, 0xea, 0x5d, 0x22, 0x0f, 0x6a, 0xbb, 0x5a, 0xbd, 0x71, 0xfd, 0xe1, 0xf5, 0x8e, 0x46, 0x2f,
		0x7e, 0x83, 0x50, 0xd8, 0x35, 0xcf, 0x08, 0xf9, 0xa2, 0x2e, 0xea, 0xca, 0x8b, 0xd4, 0x7f, 0xf8,
		0x3e, 0xae, 0x55, 0x89, 0xbf, 0x1c, 0xf8, 0x64, 0xe3, 0xd0, 0x22, 0x8f, 0xeb, 0xf2, 0xd4, 0xbd,
		0x5d, 0xfd, 0x6f, 0x6f, 0x10, 0x59, 0x35, 0xf4, 0xb7, 0x03, 0x87, 0x9b, 0x47, 0x1c, 0xf9, 0xd0,
		0xbc, 0xab, 0x51, 0xd5, 0xff, 0xee, 0x26, 0xa1, 0xeb, 0x24, 0xbd, 0x7b, 0xb7, 0xaf, 0x25, 0x69,
		0xeb, 0xf0, 0xbc, 0x96, 0xa4, 0xed, 0x83, 0xc4, 0x6f, 0x4c, 0x10, 0xee, 0x47, 0x3c, 0xa9, 0xc9,
		0x30, 0xe9, 0x55, 0x12, 0x9d, 0xab, 0xbf, 0xb0, 0xb9, 0xf3, 0xeb, 0xd7, 0x4b, 0x26, 0x4f, 0x8b,
		0xc5, 0x28, 0xe2, 0xc9, 0x58, 0x05, 0x8e, 0x2f, 0x05, 0x8e, 0x69, 0xc6, 0xc6, 0x55, 0xf0, 0x58,
		0xff, 0xb8, 0x65, 0x8b, 0xc5, 0xae, 0xfe, 0xf8, 0xe6, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac,
		0xda, 0x1e, 0xfe, 0xd4, 0x09, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) StovepipeYARPCClient {
			return NewStovepipeYARPCClient(clientConfig, v2.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
