load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["recorder.go"],
    importpath = "github.com/uber/submitqueue/stovepipe/core/requestlog",
    visibility = ["//visibility:public"],
    deps = [
        "//platform/metrics:go_default_library",
        "//stovepipe/entity:go_default_library",
        "//stovepipe/extension/storage:go_default_library",
        "@com_github_uber_go_tally//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["recorder_test.go"],
    embed = [":go_default_library"],
    deps = [
        "//stovepipe/entity:go_default_library",
        "//stovepipe/extension/storage:go_default_library",
        "//stovepipe/extension/storage/mock:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@com_github_uber_go_tally//:go_default_library",
        "@org_uber_go_mock//gomock:go_default_library",
    ],
)
