load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["http.go"],
    importpath = "github.com/uber/submitqueue/platform/errs/http",
    visibility = ["//visibility:public"],
    deps = [
        "//platform/errs:go_default_library",
        "//platform/http:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["http_test.go"],
    embed = [":go_default_library"],
    deps = [
        "//platform/errs:go_default_library",
        "//platform/errs/generic:go_default_library",
        "//platform/errs/mysql:go_default_library",
        "//platform/http:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
    ],
)
