// Code generated by MockGen. DO NOT EDIT.
// Source: projectstatus.go
//
// Generated by this command:
//
//	mockgen -source=projectstatus.go -destination=mock/projectstatus_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/stovepipe/entity"
	projectstatus "github.com/uber/submitqueue/stovepipe/extension/projectstatus"
	gomock "go.uber.org/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockResolver) Resolve(ctx context.Context, request entity.Request, terminalBuildID string) ([]projectstatus.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, request, terminalBuildID)
	ret0, _ := ret[0].([]projectstatus.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolverMockRecorder) Resolve(ctx, request, terminalBuildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolver)(nil).Resolve), ctx, request, terminalBuildID)
}

// MockResolverFactory is a mock of ResolverFactory interface.
type MockResolverFactory struct {
	ctrl     *gomock.Controller
	recorder *MockResolverFactoryMockRecorder
	isgomock struct{}
}

// MockResolverFactoryMockRecorder is the mock recorder for MockResolverFactory.
type MockResolverFactoryMockRecorder struct {
	mock *MockResolverFactory
}

// NewMockResolverFactory creates a new mock instance.
func NewMockResolverFactory(ctrl *gomock.Controller) *MockResolverFactory {
	mock := &MockResolverFactory{ctrl: ctrl}
	mock.recorder = &MockResolverFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolverFactory) EXPECT() *MockResolverFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockResolverFactory) For(cfg projectstatus.ResolverConfig) (projectstatus.Resolver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", cfg)
	ret0, _ := ret[0].(projectstatus.Resolver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockResolverFactoryMockRecorder) For(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockResolverFactory)(nil).For), cfg)
}
