// Code generated by MockGen. DO NOT EDIT.
// Source: build_runner.go
//
// Generated by this command:
//
//	mockgen -source=build_runner.go -destination=mock/build_runner_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/entity"
	buildrunner "github.com/uber/submitqueue/extension/buildrunner"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockFactory) New(cfg buildrunner.Config) (buildrunner.BuildRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", cfg)
	ret0, _ := ret[0].(buildrunner.BuildRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockFactoryMockRecorder) New(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockFactory)(nil).New), cfg)
}

// MockBuildRunner is a mock of BuildRunner interface.
type MockBuildRunner struct {
	ctrl     *gomock.Controller
	recorder *MockBuildRunnerMockRecorder
	isgomock struct{}
}

// MockBuildRunnerMockRecorder is the mock recorder for MockBuildRunner.
type MockBuildRunnerMockRecorder struct {
	mock *MockBuildRunner
}

// NewMockBuildRunner creates a new mock instance.
func NewMockBuildRunner(ctrl *gomock.Controller) *MockBuildRunner {
	mock := &MockBuildRunner{ctrl: ctrl}
	mock.recorder = &MockBuildRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildRunner) EXPECT() *MockBuildRunnerMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockBuildRunner) Cancel(ctx context.Context, buildID entity.BuildID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, buildID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBuildRunnerMockRecorder) Cancel(ctx, buildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBuildRunner)(nil).Cancel), ctx, buildID)
}

// Status mocks base method.
func (m *MockBuildRunner) Status(ctx context.Context, buildID entity.BuildID) (entity.BuildStatus, entity.BuildMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, buildID)
	ret0, _ := ret[0].(entity.BuildStatus)
	ret1, _ := ret[1].(entity.BuildMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Status indicates an expected call of Status.
func (mr *MockBuildRunnerMockRecorder) Status(ctx, buildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockBuildRunner)(nil).Status), ctx, buildID)
}

// Trigger mocks base method.
func (m *MockBuildRunner) Trigger(ctx context.Context, base, head []entity.Change, metadata entity.BuildMetadata) (entity.BuildID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trigger", ctx, base, head, metadata)
	ret0, _ := ret[0].(entity.BuildID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Trigger indicates an expected call of Trigger.
func (mr *MockBuildRunnerMockRecorder) Trigger(ctx, base, head, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trigger", reflect.TypeOf((*MockBuildRunner)(nil).Trigger), ctx, base, head, metadata)
}
