load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["githubtestrepo.go"],
    importpath = "github.com/uber/submitqueue/test/testutil/githubtestrepo",
    visibility = ["//visibility:public"],
    deps = [
        "//platform/http:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@org_golang_x_oauth2//:go_default_library",
    ],
)
