"""Hermetic protobuf code generation helpers."""

def _strip_proto_suffix(filename):
    if not filename.endswith(".proto"):
        fail("expected a .proto source, got {}".format(filename))
    return filename[:-len(".proto")]

def _go_proto_generated_files_impl(ctx):
    out_dir = ctx.attr.out_dir

    proto_toolchain = ctx.toolchains["@rules_proto//proto:toolchain_type"].proto
    protoc = proto_toolchain.proto_compiler

    tools = [
        protoc,
        ctx.executable._protoc_gen_go,
        ctx.executable._protoc_gen_go_grpc,
        ctx.executable._protoc_gen_yarpc_go,
    ]

    # Imported .proto files (e.g. the shared api/base contracts) must be present
    # in the sandbox and resolvable on the import path. They are generated by
    # their own target, so they are NOT passed as sources to compile here — they
    # only provide type/go_package information for the importing source.
    import_files = ctx.files.imports

    all_outputs = []

    # Generate independently per source so a package can hold multiple .proto
    # files (e.g. an RPC service contract alongside messagequeue contracts).
    for src in ctx.files.srcs:
        base = _strip_proto_suffix(src.basename)
        outputs = [ctx.actions.declare_file("{}/{}.pb.go".format(out_dir, base))]

        # protoc-gen-go-grpc and protoc-gen-yarpc-go-v2 only emit a file when the
        # source declares at least one service. Message-only contracts (e.g. the
        # shared api/base types) set gen_services = False so Bazel does not expect
        # outputs that protoc never produces.
        if ctx.attr.gen_services:
            outputs.append(ctx.actions.declare_file("{}/{}.pb.yarpc.go".format(out_dir, base)))
            outputs.append(ctx.actions.declare_file("{}/{}_grpc.pb.go".format(out_dir, base)))
        all_outputs.extend(outputs)

        args = ctx.actions.args()
        for opt in proto_toolchain.protoc_opts:
            args.add(opt)
        args.add("--plugin=protoc-gen-go={}".format(ctx.executable._protoc_gen_go.path))
        args.add("--go_out={}".format(outputs[0].dirname))
        args.add("--go_opt=paths=source_relative")
        if ctx.attr.gen_services:
            args.add("--plugin=protoc-gen-go-grpc={}".format(ctx.executable._protoc_gen_go_grpc.path))
            args.add("--plugin=protoc-gen-yarpc-go-v2={}".format(ctx.executable._protoc_gen_yarpc_go.path))
            args.add("--go-grpc_out={}".format(outputs[0].dirname))
            args.add("--go-grpc_opt=paths=source_relative")
            args.add("--yarpc-go-v2_out={}".format(outputs[0].dirname))
            args.add("--yarpc-go-v2_opt=paths=source_relative")

        # The source's own directory is listed first so its generated files stay
        # flat in out_dir (source_relative output collapses to the basename). The
        # exec root is added only when there are imports, so cross-package imports
        # written as repo-relative paths (e.g. "api/base/change/proto/change.proto")
        # resolve without nesting the primary source's output.
        args.add("--proto_path={}".format(src.dirname))
        if import_files:
            args.add("--proto_path=.")
        args.add(src.path)

        ctx.actions.run_shell(
            inputs = [src] + import_files,
            outputs = outputs,
            tools = tools,
            command = "mkdir -p {out_dir} && {protoc} \"$@\"".format(
                out_dir = outputs[0].dirname,
                protoc = protoc.executable.path,
            ),
            arguments = [args],
            mnemonic = "HermeticGoProto",
            progress_message = "Generating Go protobuf files for {}".format(src.short_path),
        )

    return [DefaultInfo(files = depset(all_outputs))]

go_proto_generated_files = rule(
    implementation = _go_proto_generated_files_impl,
    attrs = {
        "srcs": attr.label_list(
            allow_files = [".proto"],
            mandatory = True,
        ),
        "out_dir": attr.string(mandatory = True),
        "imports": attr.label_list(
            allow_files = [".proto"],
            default = [],
            doc = "Imported .proto files made available on the import path but not compiled here.",
        ),
        "gen_services": attr.bool(
            default = True,
            doc = "Whether to run the gRPC and YARPC generators. Set False for message-only contracts.",
        ),
        "_protoc_gen_go": attr.label(
            default = "@org_golang_google_protobuf//cmd/protoc-gen-go",
            executable = True,
            cfg = "exec",
        ),
        "_protoc_gen_go_grpc": attr.label(
            default = "@org_golang_google_grpc_cmd_protoc_gen_go_grpc//:protoc-gen-go-grpc",
            executable = True,
            cfg = "exec",
        ),
        "_protoc_gen_yarpc_go": attr.label(
            default = "@org_uber_go_yarpc//encoding/protobuf/protoc-gen-yarpc-go-v2",
            executable = True,
            cfg = "exec",
        ),
    },
    toolchains = ["@rules_proto//proto:toolchain_type"],
)
