// Copyright (c) 2025 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: batch.proto

package protopb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/uber/submitqueue/api/base/messagequeue/protopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Batch is the payload mergeconflictsignal publishes to the batch stage: only the request id travels. batch reloads the Request from storage.
type Batch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the request id to enroll in a batch. Format: "<queue>/<counter>".
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// queue is the name of the queue processing this work, carried so the
	// consumer can route by queue without loading state first. Empty on
	// payloads written before the field existed.
	Queue         string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_batch_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Batch) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

var File_batch_proto protoreflect.FileDescriptor

const file_batch_proto_rawDesc = "" +
	"\n" +
	"\vbatch.proto\x12\x1duber.submitqueue.messagequeue\x1a.api/base/messagequeue/proto/messagequeue.proto\"8\n" +
	"\x05Batch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue:\t\x8a\xb5\x18\x05batchB\x80\x01\n" +
	"-com.uber.submitqueue.submitqueue.messagequeueB\n" +
	"BatchProtoP\x01ZAgithub.com/uber/submitqueue/submitqueue/core/messagequeue/protopbb\x06proto3"

var (
	file_batch_proto_rawDescOnce sync.Once
	file_batch_proto_rawDescData []byte
)

func file_batch_proto_rawDescGZIP() []byte {
	file_batch_proto_rawDescOnce.Do(func() {
		file_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_batch_proto_rawDesc), len(file_batch_proto_rawDesc)))
	})
	return file_batch_proto_rawDescData
}

var file_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_batch_proto_goTypes = []any{
	(*Batch)(nil), // 0: uber.submitqueue.messagequeue.Batch
}
var file_batch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_batch_proto_init() }
func file_batch_proto_init() {
	if File_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_batch_proto_rawDesc), len(file_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_batch_proto_goTypes,
		DependencyIndexes: file_batch_proto_depIdxs,
		MessageInfos:      file_batch_proto_msgTypes,
	}.Build()
	File_batch_proto = out.File
	file_batch_proto_goTypes = nil
	file_batch_proto_depIdxs = nil
}
