// Copyright (c) 2025 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: start.proto

package protopb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protopb "github.com/uber/submitqueue/api/base/change/protopb"
	protopb1 "github.com/uber/submitqueue/api/base/mergestrategy/protopb"
	_ "github.com/uber/submitqueue/api/base/messagequeue/protopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Start is the payload the gateway publishes to the start stage: the
// gateway-owned land inputs and the minted request id. start persists a Request
// from these fields; producer and consumer do not share a store at this seam.
type Start struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the minted request id. Format: "<queue>/<counter>".
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// queue is the name of the queue processing the land request.
	Queue string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	// change is the set of code changes to land.
	Change *protopb.Change `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`
	// land_strategy is the source-control integration strategy for every URI of change.
	LandStrategy  protopb1.Strategy `protobuf:"varint,4,opt,name=land_strategy,json=landStrategy,proto3,enum=uber.base.mergestrategy.Strategy" json:"land_strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_start_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_start_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_start_proto_rawDescGZIP(), []int{0}
}

func (x *Start) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Start) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Start) GetChange() *protopb.Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *Start) GetLandStrategy() protopb1.Strategy {
	if x != nil {
		return x.LandStrategy
	}
	return protopb1.Strategy(0)
}

var File_start_proto protoreflect.FileDescriptor

const file_start_proto_rawDesc = "" +
	"\n" +
	"\vstart.proto\x12\x1duber.submitqueue.messagequeue\x1a\"api/base/change/proto/change.proto\x1a0api/base/mergestrategy/proto/mergestrategy.proto\x1a.api/base/messagequeue/proto/messagequeue.proto\"\xb2\x01\n" +
	"\x05Start\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x120\n" +
	"\x06change\x18\x03 \x01(\v2\x18.uber.base.change.ChangeR\x06change\x12F\n" +
	"\rland_strategy\x18\x04 \x01(\x0e2!.uber.base.mergestrategy.StrategyR\flandStrategy:\t\x8a\xb5\x18\x05startB\x80\x01\n" +
	"-com.uber.submitqueue.submitqueue.messagequeueB\n" +
	"StartProtoP\x01ZAgithub.com/uber/submitqueue/submitqueue/core/messagequeue/protopbb\x06proto3"

var (
	file_start_proto_rawDescOnce sync.Once
	file_start_proto_rawDescData []byte
)

func file_start_proto_rawDescGZIP() []byte {
	file_start_proto_rawDescOnce.Do(func() {
		file_start_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_start_proto_rawDesc), len(file_start_proto_rawDesc)))
	})
	return file_start_proto_rawDescData
}

var file_start_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_start_proto_goTypes = []any{
	(*Start)(nil),          // 0: uber.submitqueue.messagequeue.Start
	(*protopb.Change)(nil), // 1: uber.base.change.Change
	(protopb1.Strategy)(0), // 2: uber.base.mergestrategy.Strategy
}
var file_start_proto_depIdxs = []int32{
	1, // 0: uber.submitqueue.messagequeue.Start.change:type_name -> uber.base.change.Change
	2, // 1: uber.submitqueue.messagequeue.Start.land_strategy:type_name -> uber.base.mergestrategy.Strategy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_start_proto_init() }
func file_start_proto_init() {
	if File_start_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_start_proto_rawDesc), len(file_start_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_start_proto_goTypes,
		DependencyIndexes: file_start_proto_depIdxs,
		MessageInfos:      file_start_proto_msgTypes,
	}.Build()
	File_start_proto = out.File
	file_start_proto_goTypes = nil
	file_start_proto_depIdxs = nil
}
