// Code generated by MockGen. DO NOT EDIT.
// Source: consumergate.go
//
// Generated by this command:
//
//	mockgen -source=consumergate.go -destination=mock/consumergate_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	consumergate "github.com/uber/submitqueue/platform/extension/consumergate"
	gomock "go.uber.org/mock/gomock"
)

// MockGate is a mock of Gate interface.
type MockGate struct {
	ctrl     *gomock.Controller
	recorder *MockGateMockRecorder
	isgomock struct{}
}

// MockGateMockRecorder is the mock recorder for MockGate.
type MockGateMockRecorder struct {
	mock *MockGate
}

// NewMockGate creates a new mock instance.
func NewMockGate(ctrl *gomock.Controller) *MockGate {
	mock := &MockGate{ctrl: ctrl}
	mock.recorder = &MockGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGate) EXPECT() *MockGateMockRecorder {
	return m.recorder
}

// Enter mocks base method.
func (m *MockGate) Enter(ctx context.Context, key consumergate.Key) (consumergate.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enter", ctx, key)
	ret0, _ := ret[0].(consumergate.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enter indicates an expected call of Enter.
func (mr *MockGateMockRecorder) Enter(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enter", reflect.TypeOf((*MockGate)(nil).Enter), ctx, key)
}

// MockEntry is a mock of Entry interface.
type MockEntry struct {
	ctrl     *gomock.Controller
	recorder *MockEntryMockRecorder
	isgomock struct{}
}

// MockEntryMockRecorder is the mock recorder for MockEntry.
type MockEntryMockRecorder struct {
	mock *MockEntry
}

// NewMockEntry creates a new mock instance.
func NewMockEntry(ctrl *gomock.Controller) *MockEntry {
	mock := &MockEntry{ctrl: ctrl}
	mock.recorder = &MockEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntry) EXPECT() *MockEntryMockRecorder {
	return m.recorder
}

// Blocked mocks base method.
func (m *MockEntry) Blocked() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocked")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Blocked indicates an expected call of Blocked.
func (mr *MockEntryMockRecorder) Blocked() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocked", reflect.TypeOf((*MockEntry)(nil).Blocked))
}

// Watch mocks base method.
func (m *MockEntry) Watch(ctx context.Context, descriptor consumergate.DeliveryDescriptor) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, descriptor)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockEntryMockRecorder) Watch(ctx, descriptor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockEntry)(nil).Watch), ctx, descriptor)
}

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
	isgomock struct{}
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdmin) Close(ctx context.Context, key consumergate.Key, meta consumergate.Metadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, key, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAdminMockRecorder) Close(ctx, key, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdmin)(nil).Close), ctx, key, meta)
}

// ListParked mocks base method.
func (m *MockAdmin) ListParked(ctx context.Context, consumerGroup string) ([]consumergate.Parked, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParked", ctx, consumerGroup)
	ret0, _ := ret[0].([]consumergate.Parked)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParked indicates an expected call of ListParked.
func (mr *MockAdminMockRecorder) ListParked(ctx, consumerGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParked", reflect.TypeOf((*MockAdmin)(nil).ListParked), ctx, consumerGroup)
}

// Open mocks base method.
func (m *MockAdmin) Open(ctx context.Context, key consumergate.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockAdminMockRecorder) Open(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockAdmin)(nil).Open), ctx, key)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockFactory) For(cfg consumergate.Config) (consumergate.Gate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", cfg)
	ret0, _ := ret[0].(consumergate.Gate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockFactoryMockRecorder) For(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockFactory)(nil).For), cfg)
}
