// Code generated by MockGen. DO NOT EDIT.
// Source: speculator.go
//
// Generated by this command:
//
//	mockgen -source=speculator.go -destination=mock/speculator_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	speculator "github.com/uber/submitqueue/submitqueue/extension/speculation/speculator"
	gomock "go.uber.org/mock/gomock"
)

// MockSpeculator is a mock of Speculator interface.
type MockSpeculator struct {
	ctrl     *gomock.Controller
	recorder *MockSpeculatorMockRecorder
	isgomock struct{}
}

// MockSpeculatorMockRecorder is the mock recorder for MockSpeculator.
type MockSpeculatorMockRecorder struct {
	mock *MockSpeculator
}

// NewMockSpeculator creates a new mock instance.
func NewMockSpeculator(ctrl *gomock.Controller) *MockSpeculator {
	mock := &MockSpeculator{ctrl: ctrl}
	mock.recorder = &MockSpeculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpeculator) EXPECT() *MockSpeculatorMockRecorder {
	return m.recorder
}

// Speculate mocks base method.
func (m *MockSpeculator) Speculate(ctx context.Context, batches []entity.Batch, pathSets []entity.SpeculationPathSet) ([]entity.Speculation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Speculate", ctx, batches, pathSets)
	ret0, _ := ret[0].([]entity.Speculation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Speculate indicates an expected call of Speculate.
func (mr *MockSpeculatorMockRecorder) Speculate(ctx, batches, pathSets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Speculate", reflect.TypeOf((*MockSpeculator)(nil).Speculate), ctx, batches, pathSets)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockFactory) For(cfg speculator.Config) (speculator.Speculator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", cfg)
	ret0, _ := ret[0].(speculator.Speculator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockFactoryMockRecorder) For(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockFactory)(nil).For), cfg)
}
