// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=mock/controller_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	messagequeue "github.com/uber/submitqueue/platform/base/messagequeue"
	consumer "github.com/uber/submitqueue/platform/consumer"
	gomock "go.uber.org/mock/gomock"
)

// MockDelivery is a mock of Delivery interface.
type MockDelivery struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryMockRecorder
	isgomock struct{}
}

// MockDeliveryMockRecorder is the mock recorder for MockDelivery.
type MockDeliveryMockRecorder struct {
	mock *MockDelivery
}

// NewMockDelivery creates a new mock instance.
func NewMockDelivery(ctrl *gomock.Controller) *MockDelivery {
	mock := &MockDelivery{ctrl: ctrl}
	mock.recorder = &MockDeliveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelivery) EXPECT() *MockDeliveryMockRecorder {
	return m.recorder
}

// Attempt mocks base method.
func (m *MockDelivery) Attempt() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attempt")
	ret0, _ := ret[0].(int)
	return ret0
}

// Attempt indicates an expected call of Attempt.
func (mr *MockDeliveryMockRecorder) Attempt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attempt", reflect.TypeOf((*MockDelivery)(nil).Attempt))
}

// DeliveryID mocks base method.
func (m *MockDelivery) DeliveryID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryID")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeliveryID indicates an expected call of DeliveryID.
func (mr *MockDeliveryMockRecorder) DeliveryID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryID", reflect.TypeOf((*MockDelivery)(nil).DeliveryID))
}

// ExtendVisibilityTimeout mocks base method.
func (m *MockDelivery) ExtendVisibilityTimeout(ctx context.Context, durationMillis int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendVisibilityTimeout", ctx, durationMillis)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendVisibilityTimeout indicates an expected call of ExtendVisibilityTimeout.
func (mr *MockDeliveryMockRecorder) ExtendVisibilityTimeout(ctx, durationMillis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendVisibilityTimeout", reflect.TypeOf((*MockDelivery)(nil).ExtendVisibilityTimeout), ctx, durationMillis)
}

// Message mocks base method.
func (m *MockDelivery) Message() messagequeue.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message")
	ret0, _ := ret[0].(messagequeue.Message)
	return ret0
}

// Message indicates an expected call of Message.
func (mr *MockDeliveryMockRecorder) Message() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockDelivery)(nil).Message))
}

// Metadata mocks base method.
func (m *MockDelivery) Metadata() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockDeliveryMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockDelivery)(nil).Metadata))
}

// ReceivedAt mocks base method.
func (m *MockDelivery) ReceivedAt() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceivedAt")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ReceivedAt indicates an expected call of ReceivedAt.
func (mr *MockDeliveryMockRecorder) ReceivedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceivedAt", reflect.TypeOf((*MockDelivery)(nil).ReceivedAt))
}

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// ConsumerGroup mocks base method.
func (m *MockController) ConsumerGroup() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumerGroup")
	ret0, _ := ret[0].(string)
	return ret0
}

// ConsumerGroup indicates an expected call of ConsumerGroup.
func (mr *MockControllerMockRecorder) ConsumerGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerGroup", reflect.TypeOf((*MockController)(nil).ConsumerGroup))
}

// Name mocks base method.
func (m *MockController) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockControllerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockController)(nil).Name))
}

// Process mocks base method.
func (m *MockController) Process(ctx context.Context, delivery consumer.Delivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockControllerMockRecorder) Process(ctx, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockController)(nil).Process), ctx, delivery)
}

// TopicKey mocks base method.
func (m *MockController) TopicKey() consumer.TopicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopicKey")
	ret0, _ := ret[0].(consumer.TopicKey)
	return ret0
}

// TopicKey indicates an expected call of TopicKey.
func (mr *MockControllerMockRecorder) TopicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopicKey", reflect.TypeOf((*MockController)(nil).TopicKey))
}
