// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mock/storage_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	storage "github.com/uber/submitqueue/submitqueue/extension/storage"
	storage0 "github.com/uber/submitqueue/submitqueue/gateway/extension/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockFactory) For(config storage0.Config) (storage0.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", config)
	ret0, _ := ret[0].(storage0.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockFactoryMockRecorder) For(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockFactory)(nil).For), config)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetRequestLogStore mocks base method.
func (m *MockStorage) GetRequestLogStore() storage.RequestLogStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestLogStore")
	ret0, _ := ret[0].(storage.RequestLogStore)
	return ret0
}

// GetRequestLogStore indicates an expected call of GetRequestLogStore.
func (mr *MockStorageMockRecorder) GetRequestLogStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestLogStore", reflect.TypeOf((*MockStorage)(nil).GetRequestLogStore))
}

// GetRequestQueueSummaryStore mocks base method.
func (m *MockStorage) GetRequestQueueSummaryStore() storage.RequestQueueSummaryStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestQueueSummaryStore")
	ret0, _ := ret[0].(storage.RequestQueueSummaryStore)
	return ret0
}

// GetRequestQueueSummaryStore indicates an expected call of GetRequestQueueSummaryStore.
func (mr *MockStorageMockRecorder) GetRequestQueueSummaryStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestQueueSummaryStore", reflect.TypeOf((*MockStorage)(nil).GetRequestQueueSummaryStore))
}

// GetRequestSummaryStore mocks base method.
func (m *MockStorage) GetRequestSummaryStore() storage.RequestSummaryStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestSummaryStore")
	ret0, _ := ret[0].(storage.RequestSummaryStore)
	return ret0
}

// GetRequestSummaryStore indicates an expected call of GetRequestSummaryStore.
func (mr *MockStorageMockRecorder) GetRequestSummaryStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestSummaryStore", reflect.TypeOf((*MockStorage)(nil).GetRequestSummaryStore))
}

// GetRequestURIStore mocks base method.
func (m *MockStorage) GetRequestURIStore() storage.RequestURIStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestURIStore")
	ret0, _ := ret[0].(storage.RequestURIStore)
	return ret0
}

// GetRequestURIStore indicates an expected call of GetRequestURIStore.
func (mr *MockStorageMockRecorder) GetRequestURIStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestURIStore", reflect.TypeOf((*MockStorage)(nil).GetRequestURIStore))
}
