// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -source=delivery.go -destination=mock/delivery_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	messagequeue "github.com/uber/submitqueue/platform/base/messagequeue"
	gomock "go.uber.org/mock/gomock"
)

// MockDelivery is a mock of Delivery interface.
type MockDelivery struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryMockRecorder
	isgomock struct{}
}

// MockDeliveryMockRecorder is the mock recorder for MockDelivery.
type MockDeliveryMockRecorder struct {
	mock *MockDelivery
}

// NewMockDelivery creates a new mock instance.
func NewMockDelivery(ctrl *gomock.Controller) *MockDelivery {
	mock := &MockDelivery{ctrl: ctrl}
	mock.recorder = &MockDeliveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelivery) EXPECT() *MockDeliveryMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockDelivery) Ack(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockDeliveryMockRecorder) Ack(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockDelivery)(nil).Ack), ctx)
}

// Attempt mocks base method.
func (m *MockDelivery) Attempt() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attempt")
	ret0, _ := ret[0].(int)
	return ret0
}

// Attempt indicates an expected call of Attempt.
func (mr *MockDeliveryMockRecorder) Attempt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attempt", reflect.TypeOf((*MockDelivery)(nil).Attempt))
}

// DeliveryID mocks base method.
func (m *MockDelivery) DeliveryID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryID")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeliveryID indicates an expected call of DeliveryID.
func (mr *MockDeliveryMockRecorder) DeliveryID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryID", reflect.TypeOf((*MockDelivery)(nil).DeliveryID))
}

// ExtendVisibilityTimeout mocks base method.
func (m *MockDelivery) ExtendVisibilityTimeout(ctx context.Context, durationMillis int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendVisibilityTimeout", ctx, durationMillis)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendVisibilityTimeout indicates an expected call of ExtendVisibilityTimeout.
func (mr *MockDeliveryMockRecorder) ExtendVisibilityTimeout(ctx, durationMillis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendVisibilityTimeout", reflect.TypeOf((*MockDelivery)(nil).ExtendVisibilityTimeout), ctx, durationMillis)
}

// Message mocks base method.
func (m *MockDelivery) Message() messagequeue.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message")
	ret0, _ := ret[0].(messagequeue.Message)
	return ret0
}

// Message indicates an expected call of Message.
func (mr *MockDeliveryMockRecorder) Message() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockDelivery)(nil).Message))
}

// Metadata mocks base method.
func (m *MockDelivery) Metadata() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockDeliveryMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockDelivery)(nil).Metadata))
}

// Nack mocks base method.
func (m *MockDelivery) Nack(ctx context.Context, requeueAfterMillis int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nack", ctx, requeueAfterMillis)
	ret0, _ := ret[0].(error)
	return ret0
}

// Nack indicates an expected call of Nack.
func (mr *MockDeliveryMockRecorder) Nack(ctx, requeueAfterMillis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nack", reflect.TypeOf((*MockDelivery)(nil).Nack), ctx, requeueAfterMillis)
}

// ReceivedAt mocks base method.
func (m *MockDelivery) ReceivedAt() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceivedAt")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ReceivedAt indicates an expected call of ReceivedAt.
func (mr *MockDeliveryMockRecorder) ReceivedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceivedAt", reflect.TypeOf((*MockDelivery)(nil).ReceivedAt))
}

// Reject mocks base method.
func (m *MockDelivery) Reject(ctx context.Context, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockDeliveryMockRecorder) Reject(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockDelivery)(nil).Reject), ctx, reason)
}
