CREATE TABLE IF NOT EXISTS build (
    id VARCHAR(255) NOT NULL,
    batch_id VARCHAR(255) NOT NULL,
    status VARCHAR(64) NOT NULL,
    speculation_path_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
