// Code generated by MockGen. DO NOT EDIT.
// Source: validation_fact_store.go
//
// Generated by this command:
//
//	mockgen -source=validation_fact_store.go -destination=mock/validation_fact_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/stovepipe/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockValidationFactStore is a mock of ValidationFactStore interface.
type MockValidationFactStore struct {
	ctrl     *gomock.Controller
	recorder *MockValidationFactStoreMockRecorder
	isgomock struct{}
}

// MockValidationFactStoreMockRecorder is the mock recorder for MockValidationFactStore.
type MockValidationFactStoreMockRecorder struct {
	mock *MockValidationFactStore
}

// NewMockValidationFactStore creates a new mock instance.
func NewMockValidationFactStore(ctrl *gomock.Controller) *MockValidationFactStore {
	mock := &MockValidationFactStore{ctrl: ctrl}
	mock.recorder = &MockValidationFactStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationFactStore) EXPECT() *MockValidationFactStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockValidationFactStore) Create(ctx context.Context, fact entity.ValidationFact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, fact)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockValidationFactStoreMockRecorder) Create(ctx, fact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockValidationFactStore)(nil).Create), ctx, fact)
}

// Get mocks base method.
func (m *MockValidationFactStore) Get(ctx context.Context, uri, project string) (entity.ValidationFact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uri, project)
	ret0, _ := ret[0].(entity.ValidationFact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockValidationFactStoreMockRecorder) Get(ctx, uri, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockValidationFactStore)(nil).Get), ctx, uri, project)
}
