// Code generated by MockGen. DO NOT EDIT.
// Source: scorer.go
//
// Generated by this command:
//
//	mockgen -source=scorer.go -destination=mock/scorer_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	scorer "github.com/uber/submitqueue/submitqueue/extension/scorer"
	gomock "go.uber.org/mock/gomock"
)

// MockScorer is a mock of Scorer interface.
type MockScorer struct {
	ctrl     *gomock.Controller
	recorder *MockScorerMockRecorder
	isgomock struct{}
}

// MockScorerMockRecorder is the mock recorder for MockScorer.
type MockScorerMockRecorder struct {
	mock *MockScorer
}

// NewMockScorer creates a new mock instance.
func NewMockScorer(ctrl *gomock.Controller) *MockScorer {
	mock := &MockScorer{ctrl: ctrl}
	mock.recorder = &MockScorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScorer) EXPECT() *MockScorerMockRecorder {
	return m.recorder
}

// Score mocks base method.
func (m *MockScorer) Score(ctx context.Context, changes entity.BatchChanges) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Score", ctx, changes)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Score indicates an expected call of Score.
func (mr *MockScorerMockRecorder) Score(ctx, changes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Score", reflect.TypeOf((*MockScorer)(nil).Score), ctx, changes)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockFactory) For(cfg scorer.Config) (scorer.Scorer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", cfg)
	ret0, _ := ret[0].(scorer.Scorer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockFactoryMockRecorder) For(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockFactory)(nil).For), cfg)
}
