// Code generated by MockGen. DO NOT EDIT.
// Source: change_provider_store.go
//
// Generated by this command:
//
//	mockgen -source=change_provider_store.go -destination=mock/change_provider_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChangeProviderStore is a mock of ChangeProviderStore interface.
type MockChangeProviderStore struct {
	ctrl     *gomock.Controller
	recorder *MockChangeProviderStoreMockRecorder
	isgomock struct{}
}

// MockChangeProviderStoreMockRecorder is the mock recorder for MockChangeProviderStore.
type MockChangeProviderStoreMockRecorder struct {
	mock *MockChangeProviderStore
}

// NewMockChangeProviderStore creates a new mock instance.
func NewMockChangeProviderStore(ctrl *gomock.Controller) *MockChangeProviderStore {
	mock := &MockChangeProviderStore{ctrl: ctrl}
	mock.recorder = &MockChangeProviderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeProviderStore) EXPECT() *MockChangeProviderStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChangeProviderStore) Create(ctx context.Context, changeProvider entity.ChangeProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, changeProvider)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockChangeProviderStoreMockRecorder) Create(ctx, changeProvider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChangeProviderStore)(nil).Create), ctx, changeProvider)
}

// Get mocks base method.
func (m *MockChangeProviderStore) Get(ctx context.Context, requestID string) ([]entity.ChangeProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, requestID)
	ret0, _ := ret[0].([]entity.ChangeProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockChangeProviderStoreMockRecorder) Get(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockChangeProviderStore)(nil).Get), ctx, requestID)
}
