// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: gateway.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
	v2 "go.uber.org/yarpc/encoding/protobuf/v2"
	"google.golang.org/protobuf/proto"
)

var _ = ioutil.NopCloser

// SubmitQueueGatewayYARPCClient is the YARPC client-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
	ListQueues(context.Context, *ListQueuesRequest, ...yarpc.CallOption) (*ListQueuesResponse, error)
	Land(context.Context, *LandRequest, ...yarpc.CallOption) (*LandResponse, error)
	Cancel(context.Context, *CancelRequest, ...yarpc.CallOption) (*CancelResponse, error)
	GetRequestSummaryByID(context.Context, *GetRequestSummaryByIDRequest, ...yarpc.CallOption) (*GetRequestSummaryByIDResponse, error)
	GetRequestSummaryByChangeURI(context.Context, *GetRequestSummaryByChangeURIRequest, ...yarpc.CallOption) (*GetRequestSummaryByChangeURIResponse, error)
	List(context.Context, *ListRequest, ...yarpc.CallOption) (*ListResponse, error)
	GetRequestHistoryByID(context.Context, *GetRequestHistoryByIDRequest, ...yarpc.CallOption) (*GetRequestHistoryByIDResponse, error)
	GetRequestHistoryByChangeURI(context.Context, *GetRequestHistoryByChangeURIRequest, ...yarpc.CallOption) (*GetRequestHistoryByChangeURIResponse, error)
}

func newSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, anyResolver v2.AnyResolver, options ...v2.ClientOption) SubmitQueueGatewayYARPCClient {
	return &_SubmitQueueGatewayYARPCCaller{v2.NewStreamClient(
		v2.ClientParams{
			ServiceName:  "uber.submitqueue.gateway.SubmitQueueGateway",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSubmitQueueGatewayYARPCClient builds a new YARPC client for the SubmitQueueGateway service.
func NewSubmitQueueGatewayYARPCClient(clientConfig transport.ClientConfig, options ...v2.ClientOption) SubmitQueueGatewayYARPCClient {
	return newSubmitQueueGatewayYARPCClient(clientConfig, nil, options...)
}

// SubmitQueueGatewayYARPCServer is the YARPC server-side interface for the SubmitQueueGateway service.
type SubmitQueueGatewayYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	Land(context.Context, *LandRequest) (*LandResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	GetRequestSummaryByID(context.Context, *GetRequestSummaryByIDRequest) (*GetRequestSummaryByIDResponse, error)
	GetRequestSummaryByChangeURI(context.Context, *GetRequestSummaryByChangeURIRequest) (*GetRequestSummaryByChangeURIResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	GetRequestHistoryByID(context.Context, *GetRequestHistoryByIDRequest) (*GetRequestHistoryByIDResponse, error)
	GetRequestHistoryByChangeURI(context.Context, *GetRequestHistoryByChangeURIRequest) (*GetRequestHistoryByChangeURIResponse, error)
}

type buildSubmitQueueGatewayYARPCProceduresParams struct {
	Server      SubmitQueueGatewayYARPCServer
	AnyResolver v2.AnyResolver
}

func buildSubmitQueueGatewayYARPCProcedures(params buildSubmitQueueGatewayYARPCProceduresParams) []transport.Procedure {
	handler := &_SubmitQueueGatewayYARPCHandler{params.Server}
	return v2.BuildProcedures(
		v2.BuildProceduresParams{
			ServiceName: "uber.submitqueue.gateway.SubmitQueueGateway",
			UnaryHandlerParams: []v2.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newSubmitQueueGatewayServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "ListQueues",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.ListQueues,
							NewRequest:  newSubmitQueueGatewayServiceListQueuesYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Land",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Land,
							NewRequest:  newSubmitQueueGatewayServiceLandYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "Cancel",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.Cancel,
							NewRequest:  newSubmitQueueGatewayServiceCancelYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetRequestSummaryByID",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetRequestSummaryByID,
							NewRequest:  newSubmitQueueGatewayServiceGetRequestSummaryByIDYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetRequestSummaryByChangeURI",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetRequestSummaryByChangeURI,
							NewRequest:  newSubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "List",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.List,
							NewRequest:  newSubmitQueueGatewayServiceListYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetRequestHistoryByID",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetRequestHistoryByID,
							NewRequest:  newSubmitQueueGatewayServiceGetRequestHistoryByIDYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetRequestHistoryByChangeURI",
					Handler: v2.NewUnaryHandler(
						v2.UnaryHandlerParams{
							Handle:      handler.GetRequestHistoryByChangeURI,
							NewRequest:  newSubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []v2.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []v2.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSubmitQueueGatewayYARPCProcedures prepares an implementation of the SubmitQueueGateway service for YARPC registration.
func BuildSubmitQueueGatewayYARPCProcedures(server SubmitQueueGatewayYARPCServer) []transport.Procedure {
	return buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{Server: server})
}

// FxSubmitQueueGatewayYARPCClientParams defines the input
// for NewFxSubmitQueueGatewayYARPCClient. It provides the
// paramaters to get a SubmitQueueGatewayYARPCClient in an
// Fx application.
type FxSubmitQueueGatewayYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver v2.AnyResolver      `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSubmitQueueGatewayYARPCClientResult defines the output
// of NewFxSubmitQueueGatewayYARPCClient. It provides a
// SubmitQueueGatewayYARPCClient to an Fx application.
type FxSubmitQueueGatewayYARPCClientResult struct {
	fx.Out

	Client SubmitQueueGatewayYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSubmitQueueGatewayYARPCClient provides a SubmitQueueGatewayYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCClient("service-name"),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCClient(name string, options ...v2.ClientOption) interface{} {
	return func(params FxSubmitQueueGatewayYARPCClientParams) FxSubmitQueueGatewayYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(v2.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSubmitQueueGatewayYARPCClientResult{
			Client: newSubmitQueueGatewayYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSubmitQueueGatewayYARPCProceduresParams defines the input
// for NewFxSubmitQueueGatewayYARPCProcedures. It provides the
// paramaters to get SubmitQueueGatewayYARPCServer procedures in an
// Fx application.
type FxSubmitQueueGatewayYARPCProceduresParams struct {
	fx.In

	Server      SubmitQueueGatewayYARPCServer
	AnyResolver v2.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSubmitQueueGatewayYARPCProceduresResult defines the output
// of NewFxSubmitQueueGatewayYARPCProcedures. It provides
// SubmitQueueGatewayYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSubmitQueueGatewayYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSubmitQueueGatewayYARPCProcedures provides SubmitQueueGatewayYARPCServer procedures to an Fx application.
// It expects a SubmitQueueGatewayYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueGatewayYARPCProcedures(),
//	  ...
//	)
func NewFxSubmitQueueGatewayYARPCProcedures() interface{} {
	return func(params FxSubmitQueueGatewayYARPCProceduresParams) FxSubmitQueueGatewayYARPCProceduresResult {
		return FxSubmitQueueGatewayYARPCProceduresResult{
			Procedures: buildSubmitQueueGatewayYARPCProcedures(buildSubmitQueueGatewayYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: reflection.ServerMeta{
				ServiceName:     "uber.submitqueue.gateway.SubmitQueueGateway",
				FileDescriptors: yarpcFileDescriptorClosuref1a937782ebbded5,
			},
		}
	}
}

type _SubmitQueueGatewayYARPCCaller struct {
	streamClient v2.StreamClient
}

func (c *_SubmitQueueGatewayYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newSubmitQueueGatewayServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) ListQueues(ctx context.Context, request *ListQueuesRequest, options ...yarpc.CallOption) (*ListQueuesResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "ListQueues", request, newSubmitQueueGatewayServiceListQueuesYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*ListQueuesResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceListQueuesYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Land(ctx context.Context, request *LandRequest, options ...yarpc.CallOption) (*LandResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Land", request, newSubmitQueueGatewayServiceLandYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*LandResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceLandYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) Cancel(ctx context.Context, request *CancelRequest, options ...yarpc.CallOption) (*CancelResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Cancel", request, newSubmitQueueGatewayServiceCancelYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*CancelResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceCancelYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) GetRequestSummaryByID(ctx context.Context, request *GetRequestSummaryByIDRequest, options ...yarpc.CallOption) (*GetRequestSummaryByIDResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetRequestSummaryByID", request, newSubmitQueueGatewayServiceGetRequestSummaryByIDYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetRequestSummaryByIDResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestSummaryByIDYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) GetRequestSummaryByChangeURI(ctx context.Context, request *GetRequestSummaryByChangeURIRequest, options ...yarpc.CallOption) (*GetRequestSummaryByChangeURIResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetRequestSummaryByChangeURI", request, newSubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetRequestSummaryByChangeURIResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) List(ctx context.Context, request *ListRequest, options ...yarpc.CallOption) (*ListResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "List", request, newSubmitQueueGatewayServiceListYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*ListResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceListYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) GetRequestHistoryByID(ctx context.Context, request *GetRequestHistoryByIDRequest, options ...yarpc.CallOption) (*GetRequestHistoryByIDResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetRequestHistoryByID", request, newSubmitQueueGatewayServiceGetRequestHistoryByIDYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetRequestHistoryByIDResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestHistoryByIDYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_SubmitQueueGatewayYARPCCaller) GetRequestHistoryByChangeURI(ctx context.Context, request *GetRequestHistoryByChangeURIRequest, options ...yarpc.CallOption) (*GetRequestHistoryByChangeURIResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetRequestHistoryByChangeURI", request, newSubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetRequestHistoryByChangeURIResponse)
	if !ok {
		return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCResponse, responseMessage)
	}
	return response, err
}

type _SubmitQueueGatewayYARPCHandler struct {
	server SubmitQueueGatewayYARPCServer
}

func (h *_SubmitQueueGatewayYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) ListQueues(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *ListQueuesRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*ListQueuesRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceListQueuesYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.ListQueues(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Land(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *LandRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*LandRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceLandYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Land(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) Cancel(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *CancelRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*CancelRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceCancelYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Cancel(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) GetRequestSummaryByID(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetRequestSummaryByIDRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetRequestSummaryByIDRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestSummaryByIDYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetRequestSummaryByID(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) GetRequestSummaryByChangeURI(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetRequestSummaryByChangeURIRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetRequestSummaryByChangeURIRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetRequestSummaryByChangeURI(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) List(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *ListRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*ListRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceListYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.List(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) GetRequestHistoryByID(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetRequestHistoryByIDRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetRequestHistoryByIDRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestHistoryByIDYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetRequestHistoryByID(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_SubmitQueueGatewayYARPCHandler) GetRequestHistoryByChangeURI(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetRequestHistoryByChangeURIRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetRequestHistoryByChangeURIRequest)
		if !ok {
			return nil, v2.CastError(emptySubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetRequestHistoryByChangeURI(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSubmitQueueGatewayServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newSubmitQueueGatewayServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

func newSubmitQueueGatewayServiceListQueuesYARPCRequest() proto.Message {
	return &ListQueuesRequest{}
}

func newSubmitQueueGatewayServiceListQueuesYARPCResponse() proto.Message {
	return &ListQueuesResponse{}
}

func newSubmitQueueGatewayServiceLandYARPCRequest() proto.Message {
	return &LandRequest{}
}

func newSubmitQueueGatewayServiceLandYARPCResponse() proto.Message {
	return &LandResponse{}
}

func newSubmitQueueGatewayServiceCancelYARPCRequest() proto.Message {
	return &CancelRequest{}
}

func newSubmitQueueGatewayServiceCancelYARPCResponse() proto.Message {
	return &CancelResponse{}
}

func newSubmitQueueGatewayServiceGetRequestSummaryByIDYARPCRequest() proto.Message {
	return &GetRequestSummaryByIDRequest{}
}

func newSubmitQueueGatewayServiceGetRequestSummaryByIDYARPCResponse() proto.Message {
	return &GetRequestSummaryByIDResponse{}
}

func newSubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCRequest() proto.Message {
	return &GetRequestSummaryByChangeURIRequest{}
}

func newSubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCResponse() proto.Message {
	return &GetRequestSummaryByChangeURIResponse{}
}

func newSubmitQueueGatewayServiceListYARPCRequest() proto.Message {
	return &ListRequest{}
}

func newSubmitQueueGatewayServiceListYARPCResponse() proto.Message {
	return &ListResponse{}
}

func newSubmitQueueGatewayServiceGetRequestHistoryByIDYARPCRequest() proto.Message {
	return &GetRequestHistoryByIDRequest{}
}

func newSubmitQueueGatewayServiceGetRequestHistoryByIDYARPCResponse() proto.Message {
	return &GetRequestHistoryByIDResponse{}
}

func newSubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCRequest() proto.Message {
	return &GetRequestHistoryByChangeURIRequest{}
}

func newSubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCResponse() proto.Message {
	return &GetRequestHistoryByChangeURIResponse{}
}

var (
	emptySubmitQueueGatewayServicePingYARPCRequest                          = &PingRequest{}
	emptySubmitQueueGatewayServicePingYARPCResponse                         = &PingResponse{}
	emptySubmitQueueGatewayServiceListQueuesYARPCRequest                    = &ListQueuesRequest{}
	emptySubmitQueueGatewayServiceListQueuesYARPCResponse                   = &ListQueuesResponse{}
	emptySubmitQueueGatewayServiceLandYARPCRequest                          = &LandRequest{}
	emptySubmitQueueGatewayServiceLandYARPCResponse                         = &LandResponse{}
	emptySubmitQueueGatewayServiceCancelYARPCRequest                        = &CancelRequest{}
	emptySubmitQueueGatewayServiceCancelYARPCResponse                       = &CancelResponse{}
	emptySubmitQueueGatewayServiceGetRequestSummaryByIDYARPCRequest         = &GetRequestSummaryByIDRequest{}
	emptySubmitQueueGatewayServiceGetRequestSummaryByIDYARPCResponse        = &GetRequestSummaryByIDResponse{}
	emptySubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCRequest  = &GetRequestSummaryByChangeURIRequest{}
	emptySubmitQueueGatewayServiceGetRequestSummaryByChangeURIYARPCResponse = &GetRequestSummaryByChangeURIResponse{}
	emptySubmitQueueGatewayServiceListYARPCRequest                          = &ListRequest{}
	emptySubmitQueueGatewayServiceListYARPCResponse                         = &ListResponse{}
	emptySubmitQueueGatewayServiceGetRequestHistoryByIDYARPCRequest         = &GetRequestHistoryByIDRequest{}
	emptySubmitQueueGatewayServiceGetRequestHistoryByIDYARPCResponse        = &GetRequestHistoryByIDResponse{}
	emptySubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCRequest  = &GetRequestHistoryByChangeURIRequest{}
	emptySubmitQueueGatewayServiceGetRequestHistoryByChangeURIYARPCResponse = &GetRequestHistoryByChangeURIResponse{}
)

var yarpcFileDescriptorClosuref1a937782ebbded5 = [][]byte{
	// gateway.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcb, 0x6e, 0xdb, 0x46,
		0x17, 0x36, 0x75, 0xb3, 0x74, 0x24, 0xfb, 0xf7, 0x3f, 0x49, 0x53, 0x42, 0xb1, 0x11, 0x9b, 0x4d,
		0x1d, 0x01, 0x0d, 0xa4, 0xc0, 0x4d, 0x9b, 0xa2, 0x41, 0x02, 0xc4, 0x89, 0x73, 0x01, 0xea, 0xd4,
		0xa1, 0x6b, 0x04, 0x08, 0x50, 0x08, 0x23, 0xe9, 0x44, 0x26, 0x6c, 0x92, 0xf2, 0xcc, 0xc8, 0xad,
		0x8c, 0x2e, 0xba, 0xe9, 0xa6, 0xeb, 0xee, 0x8b, 0x3e, 0x4b, 0x17, 0x45, 0xdf, 0xaa, 0x98, 0x0b,
		0x29, 0xd2, 0x16, 0x19, 0xc5, 0xc9, 0x4a, 0x9c, 0x99, 0xf3, 0x9d, 0xfb, 0x7c, 0x73, 0x04, 0x4b,
		0x43, 0x2a, 0xf0, 0x27, 0x3a, 0x69, 0x8f, 0x58, 0x28, 0x42, 0x62, 0x8f, 0x7b, 0xc8, 0xda, 0x7c,
		0xdc, 0xf3, 0x3d, 0x71, 0x32, 0xc6, 0x31, 0xb6, 0xcd, 0x79, 0xd3, 0xa1, 0x23, 0xaf, 0xd3, 0xa3,
		0x1c, 0x3b, 0xfd, 0x43, 0x1a, 0x0c, 0xb1, 0xa3, 0x00, 0x66, 0xa1, 0xd1, 0xcd, 0x3b, 0xb1, 0x8c,
		0x8f, 0x6c, 0x88, 0x5c, 0x30, 0x2a, 0x70, 0x38, 0x31, 0xa2, 0xa9, 0x3d, 0x8d, 0x70, 0x6e, 0x41,
		0x7d, 0xcf, 0x0b, 0x86, 0x2e, 0x9e, 0x8c, 0x91, 0x0b, 0x62, 0xc3, 0xa2, 0x8f, 0x9c, 0xd3, 0x21,
		0xda, 0xd6, 0xba, 0xd5, 0xaa, 0xb9, 0xd1, 0xd2, 0xf9, 0xcd, 0x82, 0x86, 0x96, 0xe4, 0xa3, 0x30,
		0xe0, 0x98, 0x2d, 0x4a, 0x36, 0xa0, 0xc1, 0x91, 0x9d, 0x7a, 0x7d, 0xec, 0x06, 0xd4, 0x47, 0xbb,
		0xa0, 0x8e, 0xeb, 0x66, 0xef, 0x25, 0xf5, 0x91, 0xac, 0x42, 0x4d, 0x78, 0x3e, 0x72, 0x41, 0xfd,
		0x91, 0x5d, 0x5c, 0xb7, 0x5a, 0x45, 0x77, 0xba, 0x41, 0x9a, 0x50, 0x3d, 0x0c, 0xb9, 0x50, 0xe0,
		0x92, 0x02, 0xc7, 0x6b, 0xe7, 0x0f, 0x0b, 0xea, 0xdf, 0xd1, 0x60, 0x10, 0x79, 0x7c, 0x15, 0xca,
		0x2a, 0x4f, 0xc6, 0x09, 0xbd, 0x20, 0x77, 0xa0, 0xa2, 0x13, 0xa3, 0x8c, 0xd7, 0xb7, 0xec, 0xb6,
		0xca, 0xab, 0x4c, 0x4d, 0xdb, 0x64, 0xec, 0xb1, 0xfa, 0x71, 0x8d, 0x1c, 0x79, 0x00, 0xd5, 0x28,
		0x35, 0xca, 0xe6, 0xf2, 0xd6, 0x46, 0x02, 0x93, 0x4e, 0xdd, 0xbe, 0xf9, 0x70, 0x63, 0x88, 0xe3,
		0x40, 0x43, 0x7b, 0x65, 0xb2, 0x43, 0xa0, 0xc4, 0x4f, 0xbc, 0x81, 0xf1, 0x4a, 0x7d, 0x3b, 0xaf,
		0x60, 0xe9, 0x31, 0x0d, 0xfa, 0x78, 0x1c, 0xf9, 0x3e, 0x43, 0x88, 0x5c, 0x83, 0x0a, 0x43, 0xca,
		0xc3, 0xc0, 0xa4, 0xcd, 0xac, 0xa6, 0x71, 0x16, 0x13, 0x71, 0x3a, 0x2b, 0xb0, 0x1c, 0xa9, 0xd4,
		0x86, 0x9d, 0x7f, 0x0b, 0xb0, 0x6c, 0xf4, 0xef, 0x8f, 0x7d, 0x9f, 0xb2, 0xc9, 0x4c, 0x33, 0xb1,
		0xba, 0x42, 0x32, 0x6d, 0x37, 0xa0, 0xae, 0xd3, 0xd1, 0x1d, 0x33, 0x8f, 0xdb, 0xc5, 0xf5, 0x62,
		0xab, 0xe6, 0x82, 0xde, 0x3a, 0x60, 0x1e, 0x27, 0x37, 0x61, 0x99, 0x61, 0x1f, 0xbd, 0x53, 0x1c,
		0x74, 0xa9, 0xe8, 0xfa, 0x5c, 0xe5, 0xaa, 0xe8, 0x36, 0xa2, 0xdd, 0x47, 0x62, 0x97, 0xcb, 0x18,
		0xb8, 0xa0, 0x62, 0xcc, 0xed, 0xb2, 0x8e, 0x41, 0xaf, 0xc8, 0x1a, 0xc0, 0x31, 0xe5, 0xa2, 0x8b,
		0x8c, 0x85, 0xcc, 0xae, 0xa8, 0xb3, 0x9a, 0xdc, 0xd9, 0x91, 0x1b, 0xc4, 0x85, 0xaa, 0x8f, 0x82,
		0x0e, 0xa8, 0xa0, 0xf6, 0xe2, 0x7a, 0xb1, 0x55, 0xdf, 0xfa, 0xba, 0x9d, 0x75, 0x1d, 0xda, 0xe9,
		0x18, 0xdb, 0xbb, 0x06, 0xb8, 0x13, 0x08, 0x36, 0x71, 0x63, 0x3d, 0xcd, 0xfb, 0xb0, 0x94, 0x3a,
		0x22, 0x2b, 0x50, 0x3c, 0xc2, 0x89, 0xc9, 0x85, 0xfc, 0x94, 0xa9, 0x38, 0xa5, 0xc7, 0xd3, 0x54,
		0xa8, 0xc5, 0xb7, 0x85, 0x6f, 0x2c, 0xe7, 0x39, 0xac, 0x3e, 0x43, 0x91, 0xb6, 0xb4, 0x3d, 0x79,
		0xf1, 0x24, 0xaf, 0x7e, 0x33, 0x13, 0xeb, 0xf4, 0x61, 0x2d, 0x43, 0x93, 0xe9, 0x97, 0x6d, 0x58,
		0x64, 0xfa, 0x54, 0x69, 0xab, 0x6f, 0xb5, 0xe6, 0x0d, 0xdd, 0x8d, 0x80, 0xce, 0x1b, 0xf8, 0x6c,
		0x86, 0x11, 0xdd, 0xe7, 0x07, 0xee, 0x8b, 0xc8, 0xeb, 0x35, 0x80, 0x69, 0x91, 0x8d, 0xef, 0xb5,
		0xb8, 0xc6, 0x19, 0x01, 0x1c, 0xc3, 0xcd, 0x7c, 0xdd, 0x26, 0x8e, 0x27, 0x50, 0x35, 0xee, 0x70,
		0xdb, 0x52, 0x35, 0x9c, 0x3f, 0x90, 0x18, 0xe9, 0xfc, 0x2d, 0x2f, 0xb9, 0xc7, 0x45, 0xfe, 0x25,
		0xbf, 0x0b, 0x9f, 0x26, 0x9b, 0x31, 0x64, 0x5d, 0xfa, 0x56, 0x20, 0x93, 0x5d, 0x59, 0x50, 0x5d,
		0x79, 0x65, 0xda, 0x95, 0xdf, 0xb3, 0x47, 0xf2, 0x6c, 0x97, 0x93, 0xdb, 0x40, 0x62, 0x54, 0x0f,
		0xdf, 0x86, 0x0c, 0x25, 0x40, 0x73, 0xd0, 0x4a, 0x74, 0xb2, 0xad, 0x0e, 0x76, 0x39, 0xb9, 0x0e,
		0xb5, 0x11, 0x1d, 0x62, 0x97, 0x7b, 0x67, 0x9a, 0x8b, 0xca, 0x6e, 0x55, 0x6e, 0xec, 0x7b, 0x67,
		0x28, 0x33, 0xa9, 0x0e, 0x45, 0x78, 0x84, 0x81, 0xe9, 0x75, 0x25, 0xfe, 0x83, 0xdc, 0x70, 0x7e,
		0x81, 0x86, 0x0e, 0xe2, 0x63, 0xe6, 0x86, 0x6c, 0xc2, 0xff, 0x02, 0xfc, 0x59, 0x74, 0x13, 0x96,
		0x75, 0xa5, 0x96, 0xe4, 0xf6, 0x5e, 0x6c, 0xfd, 0x3a, 0x94, 0x5f, 0xa9, 0x34, 0x11, 0x28, 0x29,
		0x26, 0x35, 0x5d, 0xaa, 0x58, 0xf4, 0x0a, 0xfc, 0x5f, 0xba, 0xa6, 0x04, 0xb8, 0x31, 0xe5, 0xec,
		0x02, 0x49, 0x6e, 0x1a, 0xaf, 0xef, 0x41, 0x45, 0x79, 0x16, 0xf9, 0x7c, 0x23, 0xdb, 0x67, 0x85,
		0x74, 0x8d, 0x78, 0xfa, 0xf6, 0x3c, 0xf7, 0xb8, 0x08, 0x2f, 0x7b, 0x7b, 0xfe, 0x2a, 0x40, 0xc3,
		0x28, 0xd8, 0x39, 0xc5, 0x40, 0xc8, 0x17, 0x26, 0x7e, 0x2d, 0x64, 0xf5, 0x2c, 0x55, 0xbd, 0x7a,
		0xbc, 0x97, 0xe2, 0xa0, 0x42, 0x0e, 0x07, 0x15, 0xcf, 0x73, 0xd0, 0x5e, 0x82, 0x83, 0x4a, 0x2a,
		0xde, 0xbb, 0xd9, 0xf1, 0x26, 0x7d, 0xca, 0x62, 0x20, 0x19, 0xa6, 0x98, 0x8c, 0xd0, 0xb4, 0x87,
		0xfa, 0x96, 0x61, 0xa2, 0x04, 0x19, 0x0e, 0xd4, 0x8b, 0x0f, 0xe3, 0xaa, 0x6e, 0x92, 0x61, 0x52,
		0xd9, 0x36, 0x75, 0x7c, 0x08, 0x15, 0x65, 0x26, 0xaa, 0xe3, 0xe6, 0x7c, 0x71, 0xb9, 0x06, 0x95,
		0x66, 0x97, 0xd8, 0xc0, 0xc7, 0x61, 0x97, 0x41, 0xfc, 0x66, 0x19, 0xc5, 0x33, 0x9b, 0x63, 0x1a,
		0x41, 0xe1, 0x52, 0x11, 0x04, 0x49, 0x0e, 0x9b, 0x15, 0x81, 0xc9, 0xd4, 0x53, 0xa8, 0x1d, 0xaa,
		0x53, 0x0f, 0xe7, 0xbf, 0xa8, 0x46, 0x9f, 0x3b, 0x85, 0x3a, 0x1b, 0x50, 0xd6, 0x4d, 0x95, 0x3d,
		0x55, 0x21, 0x5c, 0x3b, 0x08, 0x18, 0xf6, 0xc3, 0x61, 0xe0, 0x9d, 0xe1, 0x40, 0x5d, 0x20, 0x8d,
		0xf9, 0x0a, 0xca, 0xba, 0x45, 0xf5, 0x73, 0x90, 0x73, 0xeb, 0x94, 0xbc, 0xab, 0xa5, 0x33, 0xf2,
		0xfb, 0xab, 0x05, 0x57, 0x8d, 0x9f, 0x2f, 0x43, 0xf1, 0x34, 0x1c, 0x07, 0x83, 0x0f, 0xb2, 0x12,
		0x55, 0xa7, 0x90, 0xa8, 0x4e, 0xba, 0xf0, 0xc5, 0x73, 0x85, 0xdf, 0xfa, 0xa7, 0x0a, 0x64, 0x5f,
		0xe9, 0x55, 0x41, 0x3e, 0xd3, 0x6a, 0xc9, 0x6b, 0x28, 0xc9, 0xa9, 0x92, 0x7c, 0x9e, 0x6d, 0x39,
		0x31, 0x9f, 0x36, 0x37, 0xdf, 0x25, 0x66, 0xa6, 0xa0, 0x05, 0xe2, 0x01, 0x4c, 0xc9, 0x8c, 0x7c,
		0x91, 0x8d, 0xbb, 0xc0, 0x83, 0xcd, 0xdb, 0xf3, 0x09, 0xc7, 0xa6, 0x5e, 0x43, 0x49, 0xce, 0x7e,
		0x79, 0x31, 0x24, 0x26, 0xd6, 0xbc, 0x18, 0x92, 0x23, 0xa4, 0xb3, 0x40, 0x7e, 0x84, 0x8a, 0x9e,
		0xee, 0xc8, 0xad, 0x6c, 0x4c, 0x6a, 0xa4, 0x6c, 0xb6, 0xde, 0x2d, 0x18, 0xab, 0xff, 0xdd, 0x82,
		0x4f, 0x66, 0x4e, 0x25, 0x24, 0x67, 0xee, 0xca, 0x1b, 0x88, 0x9a, 0xf7, 0xde, 0x1b, 0x17, 0x3b,
		0xf3, 0xa7, 0x35, 0x73, 0xd8, 0x8a, 0x6f, 0x27, 0x79, 0xf0, 0x5e, 0xba, 0xcf, 0xf3, 0x52, 0xf3,
		0xe1, 0x65, 0xe1, 0xa9, 0x32, 0x7b, 0x5c, 0xe4, 0x96, 0x79, 0x3a, 0xb3, 0xe4, 0x96, 0x39, 0x31,
		0x15, 0x5c, 0xa8, 0x43, 0x82, 0xbb, 0xe7, 0xab, 0xc3, 0xc5, 0xa7, 0x75, 0xbe, 0x3a, 0xcc, 0x78,
		0x24, 0x2e, 0xd4, 0xe1, 0x22, 0x4b, 0xce, 0x57, 0x87, 0xcc, 0xf7, 0x61, 0xbe, 0x3a, 0x64, 0x93,
		0xb3, 0xb3, 0xb0, 0x7d, 0x04, 0xab, 0xfd, 0xd0, 0xcf, 0x54, 0xb3, 0xdd, 0x30, 0xdc, 0xb2, 0x27,
		0xff, 0xe0, 0xee, 0x59, 0x6f, 0xee, 0x0f, 0x3d, 0x71, 0x38, 0xee, 0xb5, 0xfb, 0xa1, 0xdf, 0x91,
		0xa0, 0x4e, 0x02, 0xd4, 0x91, 0x7f, 0x98, 0x93, 0x6b, 0xa3, 0x44, 0xff, 0x63, 0x1e, 0xf5, 0x7a,
		0x15, 0xf5, 0xf1, 0xe5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x90, 0x8f, 0x2e, 0xa7, 0x0f,
		0x00, 0x00,
	},
	// api/base/change/proto/change.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0x2c, 0xc8, 0xd4,
		0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x4f, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0xd5, 0x2f, 0x28, 0xca, 0x2f,
		0xc9, 0x87, 0x72, 0xf4, 0xc0, 0x1c, 0x21, 0x81, 0xd2, 0xa4, 0xd4, 0x22, 0x3d, 0x90, 0x22, 0x3d,
		0x88, 0xb8, 0x92, 0x0c, 0x17, 0x9b, 0x33, 0x98, 0x25, 0x24, 0xc4, 0xc5, 0x52, 0x5a, 0x94, 0x59,
		0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x19, 0x04, 0x66, 0x3b, 0xa5, 0x71, 0x29, 0x24, 0xe7, 0xe7,
		0xea, 0x81, 0x75, 0x15, 0x97, 0x26, 0xe5, 0x66, 0x96, 0x14, 0x96, 0xa6, 0x96, 0xa6, 0x22, 0x9b,
		0xe0, 0xc4, 0x0d, 0xd1, 0x1f, 0x00, 0xb2, 0x20, 0x80, 0x31, 0xca, 0x38, 0x3d, 0xb3, 0x24, 0xa3,
		0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xa4, 0x4f, 0x1f, 0x49, 0x9f, 0x3e, 0x56, 0x27, 0x16,
		0x24, 0x25, 0xb1, 0x81, 0x19, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x91, 0x62, 0xef,
		0xc4, 0x00, 0x00, 0x00,
	},
	// api/base/mergestrategy/proto/mergestrategy.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x48, 0x2c, 0xc8, 0xd4,
		0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0xcf, 0x4d, 0x2d, 0x4a, 0x4f, 0x2d, 0x2e, 0x29, 0x4a, 0x2c, 0x49,
		0x4d, 0xaf, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x47, 0x15, 0xd3, 0x03, 0x8b, 0x09, 0x89, 0x97,
		0x26, 0xa5, 0x16, 0xe9, 0x81, 0xb4, 0xe8, 0xa1, 0x48, 0x6b, 0xf9, 0x71, 0x71, 0x04, 0x43, 0xd9,
		0x42, 0xdc, 0x5c, 0xec, 0x2e, 0xae, 0x6e, 0x8e, 0xa1, 0x3e, 0x21, 0x02, 0x0c, 0x42, 0x5c, 0x5c,
		0x6c, 0x41, 0xae, 0x4e, 0x8e, 0xc1, 0xae, 0x02, 0x8c, 0x42, 0x82, 0x5c, 0xbc, 0xc1, 0x81, 0xa1,
		0x8e, 0xc1, 0x1e, 0xf1, 0x50, 0x21, 0x26, 0x21, 0x4e, 0x2e, 0x56, 0x5f, 0xd7, 0x20, 0x77, 0x57,
		0x01, 0x66, 0x90, 0xb6, 0x80, 0x20, 0x7f, 0x5f, 0xff, 0x10, 0x57, 0x01, 0x16, 0xa7, 0x6a, 0x2e,
		0xf5, 0xe4, 0xfc, 0x5c, 0x3d, 0xb0, 0x75, 0xc5, 0xa5, 0x49, 0xb9, 0x99, 0x25, 0x85, 0xa5, 0xa9,
		0xa5, 0xa9, 0x58, 0xac, 0x76, 0x12, 0xf2, 0x05, 0x71, 0x61, 0xb6, 0x07, 0x80, 0xdc, 0x19, 0xc0,
		0x18, 0x65, 0x95, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x0f, 0x32, 0x45,
		0x1f, 0xc9, 0x14, 0x7d, 0x7c, 0xfe, 0x2e, 0x48, 0x4a, 0x62, 0x03, 0x33, 0x8c, 0x01, 0x01, 0x00,
		0x00, 0xff, 0xff, 0x7a, 0x05, 0x07, 0xe6, 0x20, 0x01, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SubmitQueueGatewayYARPCClient {
			return NewSubmitQueueGatewayYARPCClient(clientConfig, v2.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
