name: Run Bazel Test
description: Run Bazel test and show logs on failure

inputs:
  target:
    description: Bazel test target pattern
    required: true

runs:
  using: composite
  steps:
    - name: Run Bazel test
      shell: bash
      run: ./tool/bazel test ${{ inputs.target }} --test_output=errors

    - uses: ./.github/actions/logs
      if: always()
