// Code generated by MockGen. DO NOT EDIT.
// Source: prioritizer.go
//
// Generated by this command:
//
//	mockgen -source=prioritizer.go -destination=mock/prioritizer_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	prioritizer "github.com/uber/submitqueue/submitqueue/extension/prioritization/prioritizer"
	gomock "go.uber.org/mock/gomock"
)

// MockPrioritizer is a mock of Prioritizer interface.
type MockPrioritizer struct {
	ctrl     *gomock.Controller
	recorder *MockPrioritizerMockRecorder
	isgomock struct{}
}

// MockPrioritizerMockRecorder is the mock recorder for MockPrioritizer.
type MockPrioritizerMockRecorder struct {
	mock *MockPrioritizer
}

// NewMockPrioritizer creates a new mock instance.
func NewMockPrioritizer(ctrl *gomock.Controller) *MockPrioritizer {
	mock := &MockPrioritizer{ctrl: ctrl}
	mock.recorder = &MockPrioritizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrioritizer) EXPECT() *MockPrioritizerMockRecorder {
	return m.recorder
}

// Prioritize mocks base method.
func (m *MockPrioritizer) Prioritize(ctx context.Context) ([]entity.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prioritize", ctx)
	ret0, _ := ret[0].([]entity.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prioritize indicates an expected call of Prioritize.
func (mr *MockPrioritizerMockRecorder) Prioritize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prioritize", reflect.TypeOf((*MockPrioritizer)(nil).Prioritize), ctx)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockFactory) For(cfg prioritizer.Config) (prioritizer.Prioritizer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", cfg)
	ret0, _ := ret[0].(prioritizer.Prioritizer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// For indicates an expected call of For.
func (mr *MockFactoryMockRecorder) For(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockFactory)(nil).For), cfg)
}
