// Code generated by MockGen. DO NOT EDIT.
// Source: hook.go
//
// Generated by this command:
//
//	mockgen -source=hook.go -destination=mock/hook_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	hook "github.com/uber/submitqueue/api/base/hook"
	hook0 "github.com/uber/submitqueue/platform/extension/hook"
	gomock "go.uber.org/mock/gomock"
)

// MockHook is a mock of Hook interface.
type MockHook struct {
	ctrl     *gomock.Controller
	recorder *MockHookMockRecorder
	isgomock struct{}
}

// MockHookMockRecorder is the mock recorder for MockHook.
type MockHookMockRecorder struct {
	mock *MockHook
}

// NewMockHook creates a new mock instance.
func NewMockHook(ctrl *gomock.Controller) *MockHook {
	mock := &MockHook{ctrl: ctrl}
	mock.recorder = &MockHookMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHook) EXPECT() *MockHookMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockHook) Handle(ctx context.Context, event *hook.HookEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockHookMockRecorder) Handle(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockHook)(nil).Handle), ctx, event)
}

// Name mocks base method.
func (m *MockHook) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockHookMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockHook)(nil).Name))
}

// MockHooks is a mock of Hooks interface.
type MockHooks struct {
	ctrl     *gomock.Controller
	recorder *MockHooksMockRecorder
	isgomock struct{}
}

// MockHooksMockRecorder is the mock recorder for MockHooks.
type MockHooksMockRecorder struct {
	mock *MockHooks
}

// NewMockHooks creates a new mock instance.
func NewMockHooks(ctrl *gomock.Controller) *MockHooks {
	mock := &MockHooks{ctrl: ctrl}
	mock.recorder = &MockHooksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHooks) EXPECT() *MockHooksMockRecorder {
	return m.recorder
}

// For mocks base method.
func (m *MockHooks) For(event *hook.HookEvent) []hook0.Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", event)
	ret0, _ := ret[0].([]hook0.Hook)
	return ret0
}

// For indicates an expected call of For.
func (mr *MockHooksMockRecorder) For(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockHooks)(nil).For), event)
}
