// Code generated by MockGen. DO NOT EDIT.
// Source: batch_build_store.go
//
// Generated by this command:
//
//	mockgen -source=batch_build_store.go -destination=mock/batch_build_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchBuildStore is a mock of BatchBuildStore interface.
type MockBatchBuildStore struct {
	ctrl     *gomock.Controller
	recorder *MockBatchBuildStoreMockRecorder
	isgomock struct{}
}

// MockBatchBuildStoreMockRecorder is the mock recorder for MockBatchBuildStore.
type MockBatchBuildStoreMockRecorder struct {
	mock *MockBatchBuildStore
}

// NewMockBatchBuildStore creates a new mock instance.
func NewMockBatchBuildStore(ctrl *gomock.Controller) *MockBatchBuildStore {
	mock := &MockBatchBuildStore{ctrl: ctrl}
	mock.recorder = &MockBatchBuildStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchBuildStore) EXPECT() *MockBatchBuildStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBatchBuildStore) Create(ctx context.Context, batchBuild entity.BatchBuild) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, batchBuild)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBatchBuildStoreMockRecorder) Create(ctx, batchBuild any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBatchBuildStore)(nil).Create), ctx, batchBuild)
}

// Get mocks base method.
func (m *MockBatchBuildStore) Get(ctx context.Context, batchID string) (entity.BatchBuild, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, batchID)
	ret0, _ := ret[0].(entity.BatchBuild)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBatchBuildStoreMockRecorder) Get(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBatchBuildStore)(nil).Get), ctx, batchID)
}
