// Code generated by MockGen. DO NOT EDIT.
// Source: batch_dependent_store.go
//
// Generated by this command:
//
//	mockgen -source=batch_dependent_store.go -destination=mock/batch_dependent_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchDependentStore is a mock of BatchDependentStore interface.
type MockBatchDependentStore struct {
	ctrl     *gomock.Controller
	recorder *MockBatchDependentStoreMockRecorder
	isgomock struct{}
}

// MockBatchDependentStoreMockRecorder is the mock recorder for MockBatchDependentStore.
type MockBatchDependentStoreMockRecorder struct {
	mock *MockBatchDependentStore
}

// NewMockBatchDependentStore creates a new mock instance.
func NewMockBatchDependentStore(ctrl *gomock.Controller) *MockBatchDependentStore {
	mock := &MockBatchDependentStore{ctrl: ctrl}
	mock.recorder = &MockBatchDependentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchDependentStore) EXPECT() *MockBatchDependentStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBatchDependentStore) Create(ctx context.Context, batchDependent entity.BatchDependent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, batchDependent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBatchDependentStoreMockRecorder) Create(ctx, batchDependent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBatchDependentStore)(nil).Create), ctx, batchDependent)
}

// Get mocks base method.
func (m *MockBatchDependentStore) Get(ctx context.Context, batchID string) (entity.BatchDependent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, batchID)
	ret0, _ := ret[0].(entity.BatchDependent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBatchDependentStoreMockRecorder) Get(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBatchDependentStore)(nil).Get), ctx, batchID)
}

// UpdateDependents mocks base method.
func (m *MockBatchDependentStore) UpdateDependents(ctx context.Context, batchID string, oldVersion, newVersion int32, dependents []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDependents", ctx, batchID, oldVersion, newVersion, dependents)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDependents indicates an expected call of UpdateDependents.
func (mr *MockBatchDependentStoreMockRecorder) UpdateDependents(ctx, batchID, oldVersion, newVersion, dependents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDependents", reflect.TypeOf((*MockBatchDependentStore)(nil).UpdateDependents), ctx, batchID, oldVersion, newVersion, dependents)
}
