// Code generated by MockGen. DO NOT EDIT.
// Source: build_store.go
//
// Generated by this command:
//
//	mockgen -source=build_store.go -destination=mock/build_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildStore is a mock of BuildStore interface.
type MockBuildStore struct {
	ctrl     *gomock.Controller
	recorder *MockBuildStoreMockRecorder
	isgomock struct{}
}

// MockBuildStoreMockRecorder is the mock recorder for MockBuildStore.
type MockBuildStoreMockRecorder struct {
	mock *MockBuildStore
}

// NewMockBuildStore creates a new mock instance.
func NewMockBuildStore(ctrl *gomock.Controller) *MockBuildStore {
	mock := &MockBuildStore{ctrl: ctrl}
	mock.recorder = &MockBuildStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildStore) EXPECT() *MockBuildStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBuildStore) Create(ctx context.Context, build entity.Build) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, build)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBuildStoreMockRecorder) Create(ctx, build any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBuildStore)(nil).Create), ctx, build)
}

// Get mocks base method.
func (m *MockBuildStore) Get(ctx context.Context, id string) (entity.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBuildStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBuildStore)(nil).Get), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockBuildStore) UpdateStatus(ctx context.Context, id string, newStatus entity.BuildStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockBuildStoreMockRecorder) UpdateStatus(ctx, id, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockBuildStore)(nil).UpdateStatus), ctx, id, newStatus)
}
