// Code generated by MockGen. DO NOT EDIT.
// Source: queue_batch_state_store.go
//
// Generated by this command:
//
//	mockgen -source=queue_batch_state_store.go -destination=mock/queue_batch_state_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueBatchStateStore is a mock of QueueBatchStateStore interface.
type MockQueueBatchStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockQueueBatchStateStoreMockRecorder
	isgomock struct{}
}

// MockQueueBatchStateStoreMockRecorder is the mock recorder for MockQueueBatchStateStore.
type MockQueueBatchStateStoreMockRecorder struct {
	mock *MockQueueBatchStateStore
}

// NewMockQueueBatchStateStore creates a new mock instance.
func NewMockQueueBatchStateStore(ctrl *gomock.Controller) *MockQueueBatchStateStore {
	mock := &MockQueueBatchStateStore{ctrl: ctrl}
	mock.recorder = &MockQueueBatchStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueBatchStateStore) EXPECT() *MockQueueBatchStateStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockQueueBatchStateStore) Delete(ctx context.Context, queue string, state entity.BatchState, batchID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, queue, state, batchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueueBatchStateStoreMockRecorder) Delete(ctx, queue, state, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueueBatchStateStore)(nil).Delete), ctx, queue, state, batchID)
}

// List mocks base method.
func (m *MockQueueBatchStateStore) List(ctx context.Context, queue string, state entity.BatchState) ([]entity.QueueBatchState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, queue, state)
	ret0, _ := ret[0].([]entity.QueueBatchState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockQueueBatchStateStoreMockRecorder) List(ctx, queue, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQueueBatchStateStore)(nil).List), ctx, queue, state)
}

// Put mocks base method.
func (m *MockQueueBatchStateStore) Put(ctx context.Context, record entity.QueueBatchState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockQueueBatchStateStoreMockRecorder) Put(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockQueueBatchStateStore)(nil).Put), ctx, record)
}
