// Code generated by MockGen. DO NOT EDIT.
// Source: request_log_store.go
//
// Generated by this command:
//
//	mockgen -source=request_log_store.go -destination=mock/request_log_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestLogStore is a mock of RequestLogStore interface.
type MockRequestLogStore struct {
	ctrl     *gomock.Controller
	recorder *MockRequestLogStoreMockRecorder
	isgomock struct{}
}

// MockRequestLogStoreMockRecorder is the mock recorder for MockRequestLogStore.
type MockRequestLogStoreMockRecorder struct {
	mock *MockRequestLogStore
}

// NewMockRequestLogStore creates a new mock instance.
func NewMockRequestLogStore(ctrl *gomock.Controller) *MockRequestLogStore {
	mock := &MockRequestLogStore{ctrl: ctrl}
	mock.recorder = &MockRequestLogStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestLogStore) EXPECT() *MockRequestLogStoreMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockRequestLogStore) Insert(ctx context.Context, log entity.RequestLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRequestLogStoreMockRecorder) Insert(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRequestLogStore)(nil).Insert), ctx, log)
}

// List mocks base method.
func (m *MockRequestLogStore) List(ctx context.Context, requestID string) ([]entity.RequestLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, requestID)
	ret0, _ := ret[0].([]entity.RequestLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRequestLogStoreMockRecorder) List(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRequestLogStore)(nil).List), ctx, requestID)
}
