// Code generated by MockGen. DO NOT EDIT.
// Source: request_batch_store.go
//
// Generated by this command:
//
//	mockgen -source=request_batch_store.go -destination=mock/request_batch_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestBatchStore is a mock of RequestBatchStore interface.
type MockRequestBatchStore struct {
	ctrl     *gomock.Controller
	recorder *MockRequestBatchStoreMockRecorder
	isgomock struct{}
}

// MockRequestBatchStoreMockRecorder is the mock recorder for MockRequestBatchStore.
type MockRequestBatchStoreMockRecorder struct {
	mock *MockRequestBatchStore
}

// NewMockRequestBatchStore creates a new mock instance.
func NewMockRequestBatchStore(ctrl *gomock.Controller) *MockRequestBatchStore {
	mock := &MockRequestBatchStore{ctrl: ctrl}
	mock.recorder = &MockRequestBatchStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestBatchStore) EXPECT() *MockRequestBatchStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRequestBatchStore) Create(ctx context.Context, requestBatch entity.RequestBatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, requestBatch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRequestBatchStoreMockRecorder) Create(ctx, requestBatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRequestBatchStore)(nil).Create), ctx, requestBatch)
}

// Get mocks base method.
func (m *MockRequestBatchStore) Get(ctx context.Context, requestID string) (entity.RequestBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, requestID)
	ret0, _ := ret[0].(entity.RequestBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRequestBatchStoreMockRecorder) Get(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRequestBatchStore)(nil).Get), ctx, requestID)
}
