// Code generated by MockGen. DO NOT EDIT.
// Source: speculation_path_set_store.go
//
// Generated by this command:
//
//	mockgen -source=speculation_path_set_store.go -destination=mock/speculation_path_set_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/submitqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSpeculationPathSetStore is a mock of SpeculationPathSetStore interface.
type MockSpeculationPathSetStore struct {
	ctrl     *gomock.Controller
	recorder *MockSpeculationPathSetStoreMockRecorder
	isgomock struct{}
}

// MockSpeculationPathSetStoreMockRecorder is the mock recorder for MockSpeculationPathSetStore.
type MockSpeculationPathSetStoreMockRecorder struct {
	mock *MockSpeculationPathSetStore
}

// NewMockSpeculationPathSetStore creates a new mock instance.
func NewMockSpeculationPathSetStore(ctrl *gomock.Controller) *MockSpeculationPathSetStore {
	mock := &MockSpeculationPathSetStore{ctrl: ctrl}
	mock.recorder = &MockSpeculationPathSetStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpeculationPathSetStore) EXPECT() *MockSpeculationPathSetStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSpeculationPathSetStore) Create(ctx context.Context, set entity.SpeculationPathSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, set)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSpeculationPathSetStoreMockRecorder) Create(ctx, set any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSpeculationPathSetStore)(nil).Create), ctx, set)
}

// Get mocks base method.
func (m *MockSpeculationPathSetStore) Get(ctx context.Context, head string) (entity.SpeculationPathSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, head)
	ret0, _ := ret[0].(entity.SpeculationPathSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSpeculationPathSetStoreMockRecorder) Get(ctx, head any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSpeculationPathSetStore)(nil).Get), ctx, head)
}

// Update mocks base method.
func (m *MockSpeculationPathSetStore) Update(ctx context.Context, set entity.SpeculationPathSet, oldVersion, newVersion int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, set, oldVersion, newVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSpeculationPathSetStoreMockRecorder) Update(ctx, set, oldVersion, newVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSpeculationPathSetStore)(nil).Update), ctx, set, oldVersion, newVersion)
}
