load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["counter.go"],
    importpath = "github.com/uber/submitqueue/platform/extension/counter/mysql",
    visibility = ["//visibility:public"],
    deps = [
        "//platform/extension/counter:go_default_library",
        "//platform/metrics:go_default_library",
        "@com_github_uber_go_tally//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["counter_test.go"],
    embed = [":go_default_library"],
    deps = [
        "@com_github_data_dog_go_sqlmock//:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@com_github_uber_go_tally//:go_default_library",
    ],
)
