// Code generated by MockGen. DO NOT EDIT.
// Source: vcs.go
//
// Generated by this command:
//
//	mockgen -source=vcs.go -destination=mock/vcs_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/uber/submitqueue/pushqueue/entity"
	vcs "github.com/uber/submitqueue/pushqueue/extension/vcs"
	gomock "go.uber.org/mock/gomock"
)

// MockVCS is a mock of VCS interface.
type MockVCS struct {
	ctrl     *gomock.Controller
	recorder *MockVCSMockRecorder
	isgomock struct{}
}

// MockVCSMockRecorder is the mock recorder for MockVCS.
type MockVCSMockRecorder struct {
	mock *MockVCS
}

// NewMockVCS creates a new mock instance.
func NewMockVCS(ctrl *gomock.Controller) *MockVCS {
	mock := &MockVCS{ctrl: ctrl}
	mock.recorder = &MockVCSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVCS) EXPECT() *MockVCSMockRecorder {
	return m.recorder
}

// CheckMergeability mocks base method.
func (m *MockVCS) CheckMergeability(ctx context.Context, target entity.QueueTarget, items []entity.LandItem) ([]vcs.MergeabilityResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMergeability", ctx, target, items)
	ret0, _ := ret[0].([]vcs.MergeabilityResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMergeability indicates an expected call of CheckMergeability.
func (mr *MockVCSMockRecorder) CheckMergeability(ctx, target, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMergeability", reflect.TypeOf((*MockVCS)(nil).CheckMergeability), ctx, target, items)
}

// Finalize mocks base method.
func (m *MockVCS) Finalize(ctx context.Context, target entity.QueueTarget, items []entity.LandItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize", ctx, target, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finalize indicates an expected call of Finalize.
func (mr *MockVCSMockRecorder) Finalize(ctx, target, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockVCS)(nil).Finalize), ctx, target, items)
}

// Prepare mocks base method.
func (m *MockVCS) Prepare(ctx context.Context, target entity.QueueTarget, items []entity.LandItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", ctx, target, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prepare indicates an expected call of Prepare.
func (mr *MockVCSMockRecorder) Prepare(ctx, target, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockVCS)(nil).Prepare), ctx, target, items)
}

// Push mocks base method.
func (m *MockVCS) Push(ctx context.Context, target entity.QueueTarget, items []entity.LandItem) (vcs.PushResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, target, items)
	ret0, _ := ret[0].(vcs.PushResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Push indicates an expected call of Push.
func (mr *MockVCSMockRecorder) Push(ctx, target, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockVCS)(nil).Push), ctx, target, items)
}
