// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: stovepipe.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// SubmitQueueStovepipeYARPCClient is the YARPC client-side interface for the SubmitQueueStovepipe service.
type SubmitQueueStovepipeYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
}

func newSubmitQueueStovepipeYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) SubmitQueueStovepipeYARPCClient {
	return &_SubmitQueueStovepipeYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.submitqueue.stovepipe.SubmitQueueStovepipe",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSubmitQueueStovepipeYARPCClient builds a new YARPC client for the SubmitQueueStovepipe service.
func NewSubmitQueueStovepipeYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) SubmitQueueStovepipeYARPCClient {
	return newSubmitQueueStovepipeYARPCClient(clientConfig, nil, options...)
}

// SubmitQueueStovepipeYARPCServer is the YARPC server-side interface for the SubmitQueueStovepipe service.
type SubmitQueueStovepipeYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

type buildSubmitQueueStovepipeYARPCProceduresParams struct {
	Server      SubmitQueueStovepipeYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildSubmitQueueStovepipeYARPCProcedures(params buildSubmitQueueStovepipeYARPCProceduresParams) []transport.Procedure {
	handler := &_SubmitQueueStovepipeYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.submitqueue.stovepipe.SubmitQueueStovepipe",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newSubmitQueueStovepipeServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSubmitQueueStovepipeYARPCProcedures prepares an implementation of the SubmitQueueStovepipe service for YARPC registration.
func BuildSubmitQueueStovepipeYARPCProcedures(server SubmitQueueStovepipeYARPCServer) []transport.Procedure {
	return buildSubmitQueueStovepipeYARPCProcedures(buildSubmitQueueStovepipeYARPCProceduresParams{Server: server})
}

// FxSubmitQueueStovepipeYARPCClientParams defines the input
// for NewFxSubmitQueueStovepipeYARPCClient. It provides the
// paramaters to get a SubmitQueueStovepipeYARPCClient in an
// Fx application.
type FxSubmitQueueStovepipeYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSubmitQueueStovepipeYARPCClientResult defines the output
// of NewFxSubmitQueueStovepipeYARPCClient. It provides a
// SubmitQueueStovepipeYARPCClient to an Fx application.
type FxSubmitQueueStovepipeYARPCClientResult struct {
	fx.Out

	Client SubmitQueueStovepipeYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSubmitQueueStovepipeYARPCClient provides a SubmitQueueStovepipeYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueStovepipeYARPCClient("service-name"),
//	  ...
//	)
func NewFxSubmitQueueStovepipeYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxSubmitQueueStovepipeYARPCClientParams) FxSubmitQueueStovepipeYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSubmitQueueStovepipeYARPCClientResult{
			Client: newSubmitQueueStovepipeYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSubmitQueueStovepipeYARPCProceduresParams defines the input
// for NewFxSubmitQueueStovepipeYARPCProcedures. It provides the
// paramaters to get SubmitQueueStovepipeYARPCServer procedures in an
// Fx application.
type FxSubmitQueueStovepipeYARPCProceduresParams struct {
	fx.In

	Server      SubmitQueueStovepipeYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSubmitQueueStovepipeYARPCProceduresResult defines the output
// of NewFxSubmitQueueStovepipeYARPCProcedures. It provides
// SubmitQueueStovepipeYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSubmitQueueStovepipeYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSubmitQueueStovepipeYARPCProcedures provides SubmitQueueStovepipeYARPCServer procedures to an Fx application.
// It expects a SubmitQueueStovepipeYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueStovepipeYARPCProcedures(),
//	  ...
//	)
func NewFxSubmitQueueStovepipeYARPCProcedures() interface{} {
	return func(params FxSubmitQueueStovepipeYARPCProceduresParams) FxSubmitQueueStovepipeYARPCProceduresResult {
		return FxSubmitQueueStovepipeYARPCProceduresResult{
			Procedures: buildSubmitQueueStovepipeYARPCProcedures(buildSubmitQueueStovepipeYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: SubmitQueueStovepipeReflectionMeta,
		}
	}
}

// SubmitQueueStovepipeReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var SubmitQueueStovepipeReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.submitqueue.stovepipe.SubmitQueueStovepipe",
	FileDescriptors: yarpcFileDescriptorClosurefabdb6b3c0b09022,
}

type _SubmitQueueStovepipeYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_SubmitQueueStovepipeYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newSubmitQueueStovepipeServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, protobuf.CastError(emptySubmitQueueStovepipeServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

type _SubmitQueueStovepipeYARPCHandler struct {
	server SubmitQueueStovepipeYARPCServer
}

func (h *_SubmitQueueStovepipeYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, protobuf.CastError(emptySubmitQueueStovepipeServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSubmitQueueStovepipeServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newSubmitQueueStovepipeServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

var (
	emptySubmitQueueStovepipeServicePingYARPCRequest  = &PingRequest{}
	emptySubmitQueueStovepipeServicePingYARPCResponse = &PingResponse{}
)

var yarpcFileDescriptorClosurefabdb6b3c0b09022 = [][]byte{
	// stovepipe.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
		0x10, 0x86, 0x31, 0xad, 0x80, 0x5e, 0x2b, 0x90, 0x2c, 0x86, 0x28, 0x42, 0xa8, 0x64, 0x69, 0x16,
		0x1c, 0x09, 0xde, 0xa0, 0x0f, 0x80, 0x42, 0xba, 0xc1, 0x80, 0xec, 0xe8, 0x94, 0x7a, 0x70, 0xec,
		0xe6, 0xec, 0xbe, 0x01, 0xef, 0x8d, 0xe2, 0xd2, 0xd0, 0x25, 0x74, 0xf3, 0x9d, 0xff, 0x4f, 0xfa,
		0x3f, 0x1b, 0xee, 0xc8, 0xdb, 0x3d, 0x3a, 0xed, 0x50, 0xb8, 0xce, 0x7a, 0xcb, 0xd3, 0xa0, 0xb0,
		0x13, 0x14, 0x94, 0xd1, 0x7e, 0x17, 0x30, 0xa0, 0x18, 0x12, 0xd9, 0x0a, 0xe6, 0xa5, 0x6e, 0x9b,
		0x0a, 0x77, 0x01, 0xc9, 0xf3, 0x04, 0xae, 0x0d, 0x12, 0xc9, 0x06, 0x13, 0xb6, 0x64, 0xf9, 0xac,
		0x3a, 0x8e, 0xd9, 0x37, 0x83, 0xc5, 0x21, 0x49, 0xce, 0xb6, 0x84, 0xe3, 0x51, 0xfe, 0x04, 0x0b,
		0xc2, 0x6e, 0xaf, 0x6b, 0xfc, 0x6a, 0xa5, 0xc1, 0xe4, 0x32, 0x5e, 0xcf, 0x7f, 0x77, 0x6f, 0xd2,
		0x20, 0x7f, 0x80, 0x99, 0xd7, 0x06, 0xc9, 0x4b, 0xe3, 0x92, 0xc9, 0x92, 0xe5, 0x93, 0xea, 0x6f,
		0xc1, 0x53, 0xb8, 0xd9, 0x5a, 0xf2, 0x11, 0x9e, 0x46, 0x78, 0x98, 0x5f, 0x08, 0xee, 0x37, 0xd1,
		0xe4, 0xbd, 0x37, 0xd9, 0x1c, 0x45, 0xf8, 0x27, 0x4c, 0xfb, 0x7a, 0x7c, 0x25, 0xc6, 0x6d, 0xc5,
		0x89, 0x6a, 0x9a, 0x9f, 0x0f, 0x1e, 0x4c, 0xb3, 0x8b, 0xb5, 0x84, 0xc7, 0xda, 0x9a, 0x7f, 0x80,
		0xf5, 0xed, 0xd0, 0xa4, 0xec, 0xdf, 0xbc, 0x64, 0x1f, 0xcf, 0x8d, 0xf6, 0xdb, 0xa0, 0x44, 0x6d,
		0x4d, 0xd1, 0x83, 0xc5, 0x09, 0x58, 0x0c, 0x60, 0x11, 0xbf, 0xc8, 0x29, 0x75, 0x15, 0x0f, 0xaf,
		0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xd3, 0x2a, 0x7a, 0xbe, 0x01, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SubmitQueueStovepipeYARPCClient {
			return NewSubmitQueueStovepipeYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
