// Copyright (c) 2025 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: stovepipe.proto

package protopb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubmitQueueStovepipe_Ping_FullMethodName = "/uber.submitqueue.stovepipe.SubmitQueueStovepipe/Ping"
)

// SubmitQueueStovepipeClient is the client API for SubmitQueueStovepipe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubmitQueueStovepipe provides the stovepipe API
type SubmitQueueStovepipeClient interface {
	// Ping returns a response indicating the service is alive
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type submitQueueStovepipeClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmitQueueStovepipeClient(cc grpc.ClientConnInterface) SubmitQueueStovepipeClient {
	return &submitQueueStovepipeClient{cc}
}

func (c *submitQueueStovepipeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SubmitQueueStovepipe_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmitQueueStovepipeServer is the server API for SubmitQueueStovepipe service.
// All implementations must embed UnimplementedSubmitQueueStovepipeServer
// for forward compatibility.
//
// SubmitQueueStovepipe provides the stovepipe API
type SubmitQueueStovepipeServer interface {
	// Ping returns a response indicating the service is alive
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedSubmitQueueStovepipeServer()
}

// UnimplementedSubmitQueueStovepipeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubmitQueueStovepipeServer struct{}

func (UnimplementedSubmitQueueStovepipeServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSubmitQueueStovepipeServer) mustEmbedUnimplementedSubmitQueueStovepipeServer() {}
func (UnimplementedSubmitQueueStovepipeServer) testEmbeddedByValue()                              {}

// UnsafeSubmitQueueStovepipeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmitQueueStovepipeServer will
// result in compilation errors.
type UnsafeSubmitQueueStovepipeServer interface {
	mustEmbedUnimplementedSubmitQueueStovepipeServer()
}

func RegisterSubmitQueueStovepipeServer(s grpc.ServiceRegistrar, srv SubmitQueueStovepipeServer) {
	// If the following call pancis, it indicates UnimplementedSubmitQueueStovepipeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubmitQueueStovepipe_ServiceDesc, srv)
}

func _SubmitQueueStovepipe_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmitQueueStovepipeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmitQueueStovepipe_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmitQueueStovepipeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubmitQueueStovepipe_ServiceDesc is the grpc.ServiceDesc for SubmitQueueStovepipe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubmitQueueStovepipe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uber.submitqueue.stovepipe.SubmitQueueStovepipe",
	HandlerType: (*SubmitQueueStovepipeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SubmitQueueStovepipe_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stovepipe.proto",
}
