load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "find.go",
        "list.go",
        "transition.go",
    ],
    importpath = "github.com/uber/submitqueue/submitqueue/core/batch",
    visibility = ["//visibility:public"],
    deps = [
        "//submitqueue/entity:go_default_library",
        "//submitqueue/extension/storage:go_default_library",
        "@org_golang_x_sync//errgroup:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "find_test.go",
        "list_test.go",
        "transition_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//submitqueue/entity:go_default_library",
        "//submitqueue/extension/storage:go_default_library",
        "//submitqueue/extension/storage/mock:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@org_uber_go_mock//gomock:go_default_library",
    ],
)
