load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["hook.go"],
    importpath = "github.com/uber/submitqueue/platform/extension/hook/noop",
    visibility = ["//visibility:public"],
    deps = [
        "//api/base/hook:go_default_library",
        "//platform/extension/hook:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["hook_test.go"],
    embed = [":go_default_library"],
    deps = [
        "//api/base/hook:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
    ],
)
