// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: orchestrator.proto

package protopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// SubmitQueueOrchestratorYARPCClient is the YARPC client-side interface for the SubmitQueueOrchestrator service.
type SubmitQueueOrchestratorYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
}

func newSubmitQueueOrchestratorYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) SubmitQueueOrchestratorYARPCClient {
	return &_SubmitQueueOrchestratorYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.submitqueue.orchestrator.SubmitQueueOrchestrator",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSubmitQueueOrchestratorYARPCClient builds a new YARPC client for the SubmitQueueOrchestrator service.
func NewSubmitQueueOrchestratorYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) SubmitQueueOrchestratorYARPCClient {
	return newSubmitQueueOrchestratorYARPCClient(clientConfig, nil, options...)
}

// SubmitQueueOrchestratorYARPCServer is the YARPC server-side interface for the SubmitQueueOrchestrator service.
type SubmitQueueOrchestratorYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

type buildSubmitQueueOrchestratorYARPCProceduresParams struct {
	Server      SubmitQueueOrchestratorYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildSubmitQueueOrchestratorYARPCProcedures(params buildSubmitQueueOrchestratorYARPCProceduresParams) []transport.Procedure {
	handler := &_SubmitQueueOrchestratorYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.submitqueue.orchestrator.SubmitQueueOrchestrator",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newSubmitQueueOrchestratorServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSubmitQueueOrchestratorYARPCProcedures prepares an implementation of the SubmitQueueOrchestrator service for YARPC registration.
func BuildSubmitQueueOrchestratorYARPCProcedures(server SubmitQueueOrchestratorYARPCServer) []transport.Procedure {
	return buildSubmitQueueOrchestratorYARPCProcedures(buildSubmitQueueOrchestratorYARPCProceduresParams{Server: server})
}

// FxSubmitQueueOrchestratorYARPCClientParams defines the input
// for NewFxSubmitQueueOrchestratorYARPCClient. It provides the
// paramaters to get a SubmitQueueOrchestratorYARPCClient in an
// Fx application.
type FxSubmitQueueOrchestratorYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSubmitQueueOrchestratorYARPCClientResult defines the output
// of NewFxSubmitQueueOrchestratorYARPCClient. It provides a
// SubmitQueueOrchestratorYARPCClient to an Fx application.
type FxSubmitQueueOrchestratorYARPCClientResult struct {
	fx.Out

	Client SubmitQueueOrchestratorYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSubmitQueueOrchestratorYARPCClient provides a SubmitQueueOrchestratorYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueOrchestratorYARPCClient("service-name"),
//	  ...
//	)
func NewFxSubmitQueueOrchestratorYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxSubmitQueueOrchestratorYARPCClientParams) FxSubmitQueueOrchestratorYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSubmitQueueOrchestratorYARPCClientResult{
			Client: newSubmitQueueOrchestratorYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSubmitQueueOrchestratorYARPCProceduresParams defines the input
// for NewFxSubmitQueueOrchestratorYARPCProcedures. It provides the
// paramaters to get SubmitQueueOrchestratorYARPCServer procedures in an
// Fx application.
type FxSubmitQueueOrchestratorYARPCProceduresParams struct {
	fx.In

	Server      SubmitQueueOrchestratorYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSubmitQueueOrchestratorYARPCProceduresResult defines the output
// of NewFxSubmitQueueOrchestratorYARPCProcedures. It provides
// SubmitQueueOrchestratorYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSubmitQueueOrchestratorYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSubmitQueueOrchestratorYARPCProcedures provides SubmitQueueOrchestratorYARPCServer procedures to an Fx application.
// It expects a SubmitQueueOrchestratorYARPCServer to be present in the container.
//
//	fx.Provide(
//	  protopb.NewFxSubmitQueueOrchestratorYARPCProcedures(),
//	  ...
//	)
func NewFxSubmitQueueOrchestratorYARPCProcedures() interface{} {
	return func(params FxSubmitQueueOrchestratorYARPCProceduresParams) FxSubmitQueueOrchestratorYARPCProceduresResult {
		return FxSubmitQueueOrchestratorYARPCProceduresResult{
			Procedures: buildSubmitQueueOrchestratorYARPCProcedures(buildSubmitQueueOrchestratorYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: SubmitQueueOrchestratorReflectionMeta,
		}
	}
}

// SubmitQueueOrchestratorReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var SubmitQueueOrchestratorReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.submitqueue.orchestrator.SubmitQueueOrchestrator",
	FileDescriptors: yarpcFileDescriptorClosure96b6e6782baaa298,
}

type _SubmitQueueOrchestratorYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_SubmitQueueOrchestratorYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newSubmitQueueOrchestratorServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, protobuf.CastError(emptySubmitQueueOrchestratorServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

type _SubmitQueueOrchestratorYARPCHandler struct {
	server SubmitQueueOrchestratorYARPCServer
}

func (h *_SubmitQueueOrchestratorYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, protobuf.CastError(emptySubmitQueueOrchestratorServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSubmitQueueOrchestratorServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newSubmitQueueOrchestratorServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

var (
	emptySubmitQueueOrchestratorServicePingYARPCRequest  = &PingRequest{}
	emptySubmitQueueOrchestratorServicePingYARPCResponse = &PingResponse{}
)

var yarpcFileDescriptorClosure96b6e6782baaa298 = [][]byte{
	// orchestrator.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
		0x10, 0xc6, 0x31, 0xad, 0x80, 0x5e, 0xbb, 0xe0, 0x85, 0xa8, 0x02, 0xa9, 0xcd, 0x42, 0x05, 0x92,
		0x83, 0xe0, 0x0d, 0xfa, 0x00, 0x10, 0xc2, 0xc6, 0x82, 0xec, 0xe8, 0x94, 0x18, 0xc9, 0x71, 0xea,
		0xb3, 0x99, 0x58, 0x79, 0x6f, 0x14, 0x97, 0x3f, 0x5e, 0x88, 0xd8, 0x7c, 0xe7, 0xef, 0x27, 0xdd,
		0x4f, 0x1f, 0x70, 0xeb, 0xea, 0x16, 0xc9, 0x3b, 0xe9, 0xad, 0x13, 0xbd, 0xb3, 0xde, 0xf2, 0x8b,
		0xa0, 0xd0, 0x09, 0x0a, 0xca, 0x68, 0xbf, 0x0b, 0x18, 0x50, 0xa4, 0xa1, 0xfc, 0x12, 0xe6, 0xa5,
		0xee, 0x9a, 0x0a, 0x77, 0x01, 0xc9, 0xf3, 0x0c, 0x8e, 0x0d, 0x12, 0xc9, 0x06, 0x33, 0xb6, 0x62,
		0x9b, 0x59, 0xf5, 0x3d, 0xe6, 0x1f, 0x0c, 0x16, 0xfb, 0x24, 0xf5, 0xb6, 0x23, 0xfc, 0x3b, 0xca,
		0xd7, 0xb0, 0x20, 0x74, 0x6f, 0xba, 0xc6, 0x97, 0x4e, 0x1a, 0xcc, 0x0e, 0xe3, 0xf7, 0xfc, 0x6b,
		0x77, 0x2f, 0x0d, 0xf2, 0x73, 0x98, 0x79, 0x6d, 0x90, 0xbc, 0x34, 0x7d, 0x36, 0x59, 0xb1, 0xcd,
		0xa4, 0xfa, 0x5d, 0xf0, 0x25, 0x9c, 0xb4, 0x96, 0x7c, 0x84, 0xa7, 0x11, 0xfe, 0x99, 0x6f, 0xdf,
		0xe1, 0xec, 0x29, 0xca, 0x3c, 0x0e, 0x32, 0x0f, 0x89, 0x0b, 0x97, 0x30, 0x1d, 0x2e, 0xe4, 0x57,
		0x62, 0xd4, 0x59, 0x24, 0xc2, 0xcb, 0xeb, 0x7f, 0x65, 0xf7, 0xca, 0xf9, 0xc1, 0xf6, 0x15, 0xd6,
		0xb5, 0x35, 0xe3, 0xcc, 0xf6, 0x34, 0xbd, 0xaa, 0x1c, 0x5a, 0x28, 0xd9, 0xf3, 0x4d, 0xa3, 0x7d,
		0x1b, 0x94, 0xa8, 0xad, 0x29, 0x06, 0xbc, 0x48, 0xf0, 0x22, 0xc5, 0x8b, 0xd8, 0x5b, 0xaf, 0xd4,
		0x51, 0x7c, 0xdc, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x86, 0x7a, 0x29, 0x9c, 0xd6, 0x01, 0x00,
		0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SubmitQueueOrchestratorYARPCClient {
			return NewSubmitQueueOrchestratorYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
