packages:
  - api
  - service/*
  - submitqueue
  - stovepipe
  - test/e2e/stovepipe
  - test/package/react18

hoist: false

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - esbuild

linkWorkspacePackages: true
